packages:
  - 'packages/*'
  - 'settlement-pipelines/'
allowBuilds:
  bigint-buffer: true
  bufferutil: true
  esbuild: true
  node-hid: true
  unrs-resolver: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - '@marinade.finance/anchor-common@5.1.2'
  - '@marinade.finance/bankrun-utils@5.1.2'
  - '@marinade.finance/cli-common@5.1.2'
  - '@marinade.finance/config-common@5.1.2'
  - '@marinade.finance/ds-sam-calc@0.2.0'
  - '@marinade.finance/ds-sam-sdk@0.2.0'
  - '@marinade.finance/ts-common@5.1.2'
  - '@marinade.finance/web3js-1x-testing@5.1.2'
  - '@marinade.finance/web3js-1x@5.1.2'
overrides:
  glob@<8: ^10.3.10
  rpc-websockets: ^10.0.1
  utf-8-validate: ^6.0.6
  uuid: ^11.1.0
peerDependencyRules:
  allowedVersions:
    jest: '29'
    '@coral-xyz/anchor': '0.31'
