---
- LowCreditsSettlement:
    meta:
      funder: ValidatorBond
    min_settlement_lamports: 100000000 # 0.1 SOL
    grace_low_credits_bps: 100 # 1 %
    covered_range_bps: [0, 2000] # 0 % - 20 %
- LowCreditsSettlement:
    meta:
      funder: Marinade
    min_settlement_lamports: 100000000 # 0.1 SOL
    covered_range_bps: [2000, 10000] # 20 % - 100 %
# TODO: some better name (staker income decrease, penalty, harm, error impact)?
- StakerRevenueImpactSettlement:
    meta:
      funder: ValidatorBond
    min_settlement_lamports: 10000000 # 0.01 SOL TODO: ensure it is the right value
    covered_range_bps: [0, 10000] # 0 % - 100 %
