[scripts]
# recursive call: pnpm test -> anchor test -> pnpm _test
# using solana-bankrun for testing (--runInBand is needed, see https://github.com/kevinheavey/solana-bankrun/issues/2)
test = "pnpm _test"

[test.validator]
slots_per_epoch = "32"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"  
program = "fixtures/programs/metaplex_token_metadata_program.so"

[[test.validator.account_dir]]
directory = "fixtures/accounts"

[[test.validator.account_dir]]
directory = "fixtures/accounts/settlement-pipelines"
