/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  ClusterFilter,
  Context,
  Program,
  PublicKey,
} from '@metaplex-foundation/umi';
import {
  getValidatorBondsErrorFromCode,
  getValidatorBondsErrorFromName,
} from '../errors';

export const VALIDATOR_BONDS_PROGRAM_ID =
  'vbondsKbsC4QSLQQnn6ngZvkqfywn6KgEeQbkGSpk1V' as PublicKey<'vbondsKbsC4QSLQQnn6ngZvkqfywn6KgEeQbkGSpk1V'>;

export function createValidatorBondsProgram(): Program {
  return {
    name: 'validatorBonds',
    publicKey: VALIDATOR_BONDS_PROGRAM_ID,
    getErrorFromCode(code: number, cause?: Error) {
      return getValidatorBondsErrorFromCode(code, this, cause);
    },
    getErrorFromName(name: string, cause?: Error) {
      return getValidatorBondsErrorFromName(name, this, cause);
    },
    isOnCluster() {
      return true;
    },
  };
}

export function getValidatorBondsProgram<T extends Program = Program>(
  context: Pick<Context, 'programs'>,
  clusterFilter?: ClusterFilter
): T {
  return context.programs.get<T>('validatorBonds', clusterFilter);
}

export function getValidatorBondsProgramId(
  context: Pick<Context, 'programs'>,
  clusterFilter?: ClusterFilter
): PublicKey {
  return context.programs.getPublicKey(
    'validatorBonds',
    VALIDATOR_BONDS_PROGRAM_ID,
    clusterFilter
  );
}
