/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Account,
  Context,
  Option,
  OptionOrNullable,
  Pda,
  PublicKey,
  RpcAccount,
  RpcGetAccountOptions,
  RpcGetAccountsOptions,
  assertAccountExists,
  deserializeAccount,
  gpaBuilder,
  publicKey as toPublicKey,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  bytes,
  mapSerializer,
  option,
  publicKey as publicKeySerializer,
  struct,
  u64,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  Bumps,
  BumpsArgs,
  Reserved150,
  Reserved150Args,
  getBumpsSerializer,
  getReserved150Serializer,
} from '../types';

/**
 * Settlement account for a particular config and merkle root
 * Settlement defines an insurance event happens and it's needed to be settled
 */

export type Settlement = Account<SettlementAccountData>;

export type SettlementAccountData = {
  discriminator: Array<number>;
  /** this settlement belongs under particular bond, i.e., under particular validator vote account */
  bond: PublicKey;
  /** stake account authority that manages the funded stake accounts */
  settlementAuthority: PublicKey;
  /** 256-bit merkle root to check the claims against */
  merkleRoot: Uint8Array;
  /** maximum number of funds that can ever be claimed from this [Settlement] */
  maxTotalClaim: bigint;
  /** maximum number of nodes that can ever be claimed from this [Settlement] */
  maxNumNodes: bigint;
  /** total funds that have been deposited to this [Settlement] */
  totalFunded: bigint;
  /** total funds that have been claimed from this [Settlement] */
  totalFundsClaimed: bigint;
  /** number of nodes that have been claimed from this [Settlement] */
  numNodesClaimed: bigint;
  /** epoch that the [Settlement] has been created at */
  epochCreatedAt: bigint;
  /** address that collects the rent exempt from the [Settlement] account when closed */
  rentCollector: PublicKey;
  /** address that may claim the rent exempt for creation of "split stake account" */
  splitRentCollector: Option<PublicKey>;
  splitRentAmount: bigint;
  /** PDA bumps */
  bumps: Bumps;
  /** reserve space for future extensions */
  reserved: Reserved150;
};

export type SettlementAccountDataArgs = {
  /** this settlement belongs under particular bond, i.e., under particular validator vote account */
  bond: PublicKey;
  /** stake account authority that manages the funded stake accounts */
  settlementAuthority: PublicKey;
  /** 256-bit merkle root to check the claims against */
  merkleRoot: Uint8Array;
  /** maximum number of funds that can ever be claimed from this [Settlement] */
  maxTotalClaim: number | bigint;
  /** maximum number of nodes that can ever be claimed from this [Settlement] */
  maxNumNodes: number | bigint;
  /** total funds that have been deposited to this [Settlement] */
  totalFunded: number | bigint;
  /** total funds that have been claimed from this [Settlement] */
  totalFundsClaimed: number | bigint;
  /** number of nodes that have been claimed from this [Settlement] */
  numNodesClaimed: number | bigint;
  /** epoch that the [Settlement] has been created at */
  epochCreatedAt: number | bigint;
  /** address that collects the rent exempt from the [Settlement] account when closed */
  rentCollector: PublicKey;
  /** address that may claim the rent exempt for creation of "split stake account" */
  splitRentCollector: OptionOrNullable<PublicKey>;
  splitRentAmount: number | bigint;
  /** PDA bumps */
  bumps: BumpsArgs;
  /** reserve space for future extensions */
  reserved: Reserved150Args;
};

export function getSettlementAccountDataSerializer(): Serializer<
  SettlementAccountDataArgs,
  SettlementAccountData
> {
  return mapSerializer<SettlementAccountDataArgs, any, SettlementAccountData>(
    struct<SettlementAccountData>(
      [
        ['discriminator', array(u8(), { size: 8 })],
        ['bond', publicKeySerializer()],
        ['settlementAuthority', publicKeySerializer()],
        ['merkleRoot', bytes({ size: 32 })],
        ['maxTotalClaim', u64()],
        ['maxNumNodes', u64()],
        ['totalFunded', u64()],
        ['totalFundsClaimed', u64()],
        ['numNodesClaimed', u64()],
        ['epochCreatedAt', u64()],
        ['rentCollector', publicKeySerializer()],
        ['splitRentCollector', option(publicKeySerializer())],
        ['splitRentAmount', u64()],
        ['bumps', getBumpsSerializer()],
        ['reserved', getReserved150Serializer()],
      ],
      { description: 'SettlementAccountData' }
    ),
    (value) => ({
      ...value,
      discriminator: [55, 11, 219, 33, 36, 136, 40, 182],
    })
  ) as Serializer<SettlementAccountDataArgs, SettlementAccountData>;
}

export function deserializeSettlement(rawAccount: RpcAccount): Settlement {
  return deserializeAccount(rawAccount, getSettlementAccountDataSerializer());
}

export async function fetchSettlement(
  context: Pick<Context, 'rpc'>,
  publicKey: PublicKey | Pda,
  options?: RpcGetAccountOptions
): Promise<Settlement> {
  const maybeAccount = await context.rpc.getAccount(
    toPublicKey(publicKey, false),
    options
  );
  assertAccountExists(maybeAccount, 'Settlement');
  return deserializeSettlement(maybeAccount);
}

export async function safeFetchSettlement(
  context: Pick<Context, 'rpc'>,
  publicKey: PublicKey | Pda,
  options?: RpcGetAccountOptions
): Promise<Settlement | null> {
  const maybeAccount = await context.rpc.getAccount(
    toPublicKey(publicKey, false),
    options
  );
  return maybeAccount.exists ? deserializeSettlement(maybeAccount) : null;
}

export async function fetchAllSettlement(
  context: Pick<Context, 'rpc'>,
  publicKeys: Array<PublicKey | Pda>,
  options?: RpcGetAccountsOptions
): Promise<Settlement[]> {
  const maybeAccounts = await context.rpc.getAccounts(
    publicKeys.map((key) => toPublicKey(key, false)),
    options
  );
  return maybeAccounts.map((maybeAccount) => {
    assertAccountExists(maybeAccount, 'Settlement');
    return deserializeSettlement(maybeAccount);
  });
}

export async function safeFetchAllSettlement(
  context: Pick<Context, 'rpc'>,
  publicKeys: Array<PublicKey | Pda>,
  options?: RpcGetAccountsOptions
): Promise<Settlement[]> {
  const maybeAccounts = await context.rpc.getAccounts(
    publicKeys.map((key) => toPublicKey(key, false)),
    options
  );
  return maybeAccounts
    .filter((maybeAccount) => maybeAccount.exists)
    .map((maybeAccount) => deserializeSettlement(maybeAccount as RpcAccount));
}

export function getSettlementGpaBuilder(
  context: Pick<Context, 'rpc' | 'programs'>
) {
  const programId = context.programs.getPublicKey(
    'validatorBonds',
    'vbondsKbsC4QSLQQnn6ngZvkqfywn6KgEeQbkGSpk1V'
  );
  return gpaBuilder(context, programId)
    .registerFields<{
      discriminator: Array<number>;
      bond: PublicKey;
      settlementAuthority: PublicKey;
      merkleRoot: Uint8Array;
      maxTotalClaim: number | bigint;
      maxNumNodes: number | bigint;
      totalFunded: number | bigint;
      totalFundsClaimed: number | bigint;
      numNodesClaimed: number | bigint;
      epochCreatedAt: number | bigint;
      rentCollector: PublicKey;
      splitRentCollector: OptionOrNullable<PublicKey>;
      splitRentAmount: number | bigint;
      bumps: BumpsArgs;
      reserved: Reserved150Args;
    }>({
      discriminator: [0, array(u8(), { size: 8 })],
      bond: [8, publicKeySerializer()],
      settlementAuthority: [40, publicKeySerializer()],
      merkleRoot: [72, bytes({ size: 32 })],
      maxTotalClaim: [104, u64()],
      maxNumNodes: [112, u64()],
      totalFunded: [120, u64()],
      totalFundsClaimed: [128, u64()],
      numNodesClaimed: [136, u64()],
      epochCreatedAt: [144, u64()],
      rentCollector: [152, publicKeySerializer()],
      splitRentCollector: [184, option(publicKeySerializer())],
      splitRentAmount: [null, u64()],
      bumps: [null, getBumpsSerializer()],
      reserved: [null, getReserved150Serializer()],
    })
    .deserializeUsing<Settlement>((account) => deserializeSettlement(account))
    .whereField('discriminator', [55, 11, 219, 33, 36, 136, 40, 182]);
}
