/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  publicKey,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type CancelWithdrawRequestInstructionAccounts = {
  bond: PublicKey | Pda;
  validatorVoteAccount: PublicKey | Pda;
  /** validator vote account owner or bond authority may ask for cancelling */
  authority?: Signer;
  withdrawRequest: PublicKey | Pda;
  rentCollector?: PublicKey | Pda;
};

// Instruction.
export function cancelWithdrawRequest(
  context: Pick<Context, 'identity' | 'programs'>,
  input: CancelWithdrawRequestInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'validatorBonds',
    'vbondsKbsC4QSLQQnn6ngZvkqfywn6KgEeQbkGSpk1V'
  );

  // Accounts.
  const resolvedAccounts = {
    bond: { index: 0, isWritable: true as boolean, value: input.bond ?? null },
    validatorVoteAccount: {
      index: 1,
      isWritable: false as boolean,
      value: input.validatorVoteAccount ?? null,
    },
    authority: {
      index: 2,
      isWritable: false as boolean,
      value: input.authority ?? null,
    },
    withdrawRequest: {
      index: 3,
      isWritable: true as boolean,
      value: input.withdrawRequest ?? null,
    },
    rentCollector: {
      index: 4,
      isWritable: true as boolean,
      value: input.rentCollector ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Default values.
  if (!resolvedAccounts.authority.value) {
    resolvedAccounts.authority.value = context.identity;
  }
  if (!resolvedAccounts.rentCollector.value) {
    resolvedAccounts.rentCollector.value = publicKey(
      'SysvarRent111111111111111111111111111111111'
    );
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = new Uint8Array();

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
