/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  bytes,
  mapSerializer,
  publicKey as publicKeySerializer,
  struct,
  u64,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type ClaimSettlementInstructionAccounts = {
  /** the config root account under which the settlement was created */
  config: PublicKey | Pda;
  bond: PublicKey | Pda;
  settlement: PublicKey | Pda;
  /** deduplication, one amount cannot be claimed twice */
  settlementClaim: PublicKey | Pda;
  /** a stake account which will be withdrawn */
  stakeAccount: PublicKey | Pda;
  /** account that will receive the funds on this claim */
  withdrawAuthority: PublicKey | Pda;
  /** authority that manages (owns == being withdrawer authority) all stakes account under the bonds program */
  bondsWithdrawerAuthority: PublicKey | Pda;
  /**
   * On claiming it's created a claim account that confirms the claim has happened
   * when the settlement withdrawal window expires the claim account is closed and rent gets back
   */

  rentPayer?: Signer;
  systemProgram?: PublicKey | Pda;
  stakeHistory: PublicKey | Pda;
  clock: PublicKey | Pda;
  stakeProgram: PublicKey | Pda;
};

// Data.
export type ClaimSettlementInstructionData = {
  discriminator: Array<number>;
  amount: bigint;
  proof: Array<Uint8Array>;
  staker: PublicKey;
  /** claim holder, withdraw_authority */
  withdrawer: PublicKey;
  voteAccount: PublicKey;
  claim: bigint;
};

export type ClaimSettlementInstructionDataArgs = {
  amount: number | bigint;
  proof: Array<Uint8Array>;
  staker: PublicKey;
  /** claim holder, withdraw_authority */
  withdrawer: PublicKey;
  voteAccount: PublicKey;
  claim: number | bigint;
};

export function getClaimSettlementInstructionDataSerializer(): Serializer<
  ClaimSettlementInstructionDataArgs,
  ClaimSettlementInstructionData
> {
  return mapSerializer<
    ClaimSettlementInstructionDataArgs,
    any,
    ClaimSettlementInstructionData
  >(
    struct<ClaimSettlementInstructionData>(
      [
        ['discriminator', array(u8(), { size: 8 })],
        ['amount', u64()],
        ['proof', array(bytes({ size: 32 }))],
        ['staker', publicKeySerializer()],
        ['withdrawer', publicKeySerializer()],
        ['voteAccount', publicKeySerializer()],
        ['claim', u64()],
      ],
      { description: 'ClaimSettlementInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [85, 208, 73, 229, 143, 98, 83, 212],
    })
  ) as Serializer<
    ClaimSettlementInstructionDataArgs,
    ClaimSettlementInstructionData
  >;
}

// Args.
export type ClaimSettlementInstructionArgs = ClaimSettlementInstructionDataArgs;

// Instruction.
export function claimSettlement(
  context: Pick<Context, 'payer' | 'programs'>,
  input: ClaimSettlementInstructionAccounts & ClaimSettlementInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'validatorBonds',
    'vbondsKbsC4QSLQQnn6ngZvkqfywn6KgEeQbkGSpk1V'
  );

  // Accounts.
  const resolvedAccounts = {
    config: {
      index: 0,
      isWritable: false as boolean,
      value: input.config ?? null,
    },
    bond: { index: 1, isWritable: false as boolean, value: input.bond ?? null },
    settlement: {
      index: 2,
      isWritable: true as boolean,
      value: input.settlement ?? null,
    },
    settlementClaim: {
      index: 3,
      isWritable: true as boolean,
      value: input.settlementClaim ?? null,
    },
    stakeAccount: {
      index: 4,
      isWritable: true as boolean,
      value: input.stakeAccount ?? null,
    },
    withdrawAuthority: {
      index: 5,
      isWritable: true as boolean,
      value: input.withdrawAuthority ?? null,
    },
    bondsWithdrawerAuthority: {
      index: 6,
      isWritable: false as boolean,
      value: input.bondsWithdrawerAuthority ?? null,
    },
    rentPayer: {
      index: 7,
      isWritable: true as boolean,
      value: input.rentPayer ?? null,
    },
    systemProgram: {
      index: 8,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
    stakeHistory: {
      index: 9,
      isWritable: false as boolean,
      value: input.stakeHistory ?? null,
    },
    clock: {
      index: 10,
      isWritable: false as boolean,
      value: input.clock ?? null,
    },
    stakeProgram: {
      index: 11,
      isWritable: false as boolean,
      value: input.stakeProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: ClaimSettlementInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.rentPayer.value) {
    resolvedAccounts.rentPayer.value = context.payer;
  }
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'splSystem',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getClaimSettlementInstructionDataSerializer().serialize(
    resolvedArgs as ClaimSettlementInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
