/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  TransactionBuilder,
  publicKey,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type CloseSettlementInstructionAccounts = {
  config: PublicKey | Pda;
  bond: PublicKey | Pda;
  /** settlement to close when expired */
  settlement: PublicKey | Pda;
  rentCollector?: PublicKey | Pda;
  splitRentCollector: PublicKey | Pda;
  bondsWithdrawerAuthority: PublicKey | Pda;
  /** a stake account to be used to return back the split rent exempt fee */
  stakeAccount: PublicKey | Pda;
  clock: PublicKey | Pda;
  stakeProgram: PublicKey | Pda;
  stakeHistory: PublicKey | Pda;
};

// Data.
export type CloseSettlementInstructionData = { discriminator: Array<number> };

export type CloseSettlementInstructionDataArgs = {};

export function getCloseSettlementInstructionDataSerializer(): Serializer<
  CloseSettlementInstructionDataArgs,
  CloseSettlementInstructionData
> {
  return mapSerializer<
    CloseSettlementInstructionDataArgs,
    any,
    CloseSettlementInstructionData
  >(
    struct<CloseSettlementInstructionData>(
      [['discriminator', array(u8(), { size: 8 })]],
      { description: 'CloseSettlementInstructionData' }
    ),
    (value) => ({ ...value, discriminator: [45, 247, 83, 183, 24, 102, 0, 68] })
  ) as Serializer<
    CloseSettlementInstructionDataArgs,
    CloseSettlementInstructionData
  >;
}

// Instruction.
export function closeSettlement(
  context: Pick<Context, 'programs'>,
  input: CloseSettlementInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'validatorBonds',
    'vbondsKbsC4QSLQQnn6ngZvkqfywn6KgEeQbkGSpk1V'
  );

  // Accounts.
  const resolvedAccounts = {
    config: {
      index: 0,
      isWritable: false as boolean,
      value: input.config ?? null,
    },
    bond: { index: 1, isWritable: false as boolean, value: input.bond ?? null },
    settlement: {
      index: 2,
      isWritable: true as boolean,
      value: input.settlement ?? null,
    },
    rentCollector: {
      index: 3,
      isWritable: true as boolean,
      value: input.rentCollector ?? null,
    },
    splitRentCollector: {
      index: 4,
      isWritable: true as boolean,
      value: input.splitRentCollector ?? null,
    },
    bondsWithdrawerAuthority: {
      index: 5,
      isWritable: false as boolean,
      value: input.bondsWithdrawerAuthority ?? null,
    },
    stakeAccount: {
      index: 6,
      isWritable: true as boolean,
      value: input.stakeAccount ?? null,
    },
    clock: {
      index: 7,
      isWritable: false as boolean,
      value: input.clock ?? null,
    },
    stakeProgram: {
      index: 8,
      isWritable: false as boolean,
      value: input.stakeProgram ?? null,
    },
    stakeHistory: {
      index: 9,
      isWritable: false as boolean,
      value: input.stakeHistory ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Default values.
  if (!resolvedAccounts.rentCollector.value) {
    resolvedAccounts.rentCollector.value = publicKey(
      'SysvarRent111111111111111111111111111111111'
    );
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getCloseSettlementInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
