/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Option,
  OptionOrNullable,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  option,
  publicKey as publicKeySerializer,
  struct,
  u64,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type ConfigureConfigInstructionAccounts = {
  /** config root account that will be configured */
  config: PublicKey | Pda;
  /** only the admin authority can change the config params */
  adminAuthority: Signer;
};

// Data.
export type ConfigureConfigInstructionData = {
  admin: Option<PublicKey>;
  operator: Option<PublicKey>;
  epochsToClaimSettlement: Option<bigint>;
  withdrawLockupEpochs: Option<bigint>;
};

export type ConfigureConfigInstructionDataArgs = {
  admin: OptionOrNullable<PublicKey>;
  operator: OptionOrNullable<PublicKey>;
  epochsToClaimSettlement: OptionOrNullable<number | bigint>;
  withdrawLockupEpochs: OptionOrNullable<number | bigint>;
};

export function getConfigureConfigInstructionDataSerializer(): Serializer<
  ConfigureConfigInstructionDataArgs,
  ConfigureConfigInstructionData
> {
  return struct<ConfigureConfigInstructionData>(
    [
      ['admin', option(publicKeySerializer())],
      ['operator', option(publicKeySerializer())],
      ['epochsToClaimSettlement', option(u64())],
      ['withdrawLockupEpochs', option(u64())],
    ],
    { description: 'ConfigureConfigInstructionData' }
  ) as Serializer<
    ConfigureConfigInstructionDataArgs,
    ConfigureConfigInstructionData
  >;
}

// Args.
export type ConfigureConfigInstructionArgs = ConfigureConfigInstructionDataArgs;

// Instruction.
export function configureConfig(
  context: Pick<Context, 'programs'>,
  input: ConfigureConfigInstructionAccounts & ConfigureConfigInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'validatorBonds',
    'vbondsKbsC4QSLQQnn6ngZvkqfywn6KgEeQbkGSpk1V'
  );

  // Accounts.
  const resolvedAccounts = {
    config: {
      index: 0,
      isWritable: true as boolean,
      value: input.config ?? null,
    },
    adminAuthority: {
      index: 1,
      isWritable: false as boolean,
      value: input.adminAuthority ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: ConfigureConfigInstructionArgs = { ...input };

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getConfigureConfigInstructionDataSerializer().serialize(
    resolvedArgs as ConfigureConfigInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
