/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Option,
  OptionOrNullable,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  option,
  publicKey as publicKeySerializer,
  struct,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';
import {
  HundredthBasisPoint,
  HundredthBasisPointArgs,
  getHundredthBasisPointSerializer,
} from '../types';

// Accounts.
export type ConfigureBondInstructionAccounts = {
  bond: PublicKey | Pda;
  /** validator vote account owner or bond authority may change the account */
  authority?: Signer;
  validatorVoteAccount: PublicKey | Pda;
};

// Data.
export type ConfigureBondInstructionData = {
  bondAuthority: Option<PublicKey>;
  revenueShareConfig: Option<HundredthBasisPoint>;
};

export type ConfigureBondInstructionDataArgs = {
  bondAuthority: OptionOrNullable<PublicKey>;
  revenueShareConfig: OptionOrNullable<HundredthBasisPointArgs>;
};

export function getConfigureBondInstructionDataSerializer(): Serializer<
  ConfigureBondInstructionDataArgs,
  ConfigureBondInstructionData
> {
  return struct<ConfigureBondInstructionData>(
    [
      ['bondAuthority', option(publicKeySerializer())],
      ['revenueShareConfig', option(getHundredthBasisPointSerializer())],
    ],
    { description: 'ConfigureBondInstructionData' }
  ) as Serializer<
    ConfigureBondInstructionDataArgs,
    ConfigureBondInstructionData
  >;
}

// Args.
export type ConfigureBondInstructionArgs = ConfigureBondInstructionDataArgs;

// Instruction.
export function configureBond(
  context: Pick<Context, 'identity' | 'programs'>,
  input: ConfigureBondInstructionAccounts & ConfigureBondInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'validatorBonds',
    'vbondsKbsC4QSLQQnn6ngZvkqfywn6KgEeQbkGSpk1V'
  );

  // Accounts.
  const resolvedAccounts = {
    bond: { index: 0, isWritable: true as boolean, value: input.bond ?? null },
    authority: {
      index: 1,
      isWritable: false as boolean,
      value: input.authority ?? null,
    },
    validatorVoteAccount: {
      index: 2,
      isWritable: false as boolean,
      value: input.validatorVoteAccount ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: ConfigureBondInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.authority.value) {
    resolvedAccounts.authority.value = context.identity;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getConfigureBondInstructionDataSerializer().serialize(
    resolvedArgs as ConfigureBondInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
