/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type DepositBondInstructionAccounts = {
  config: PublicKey | Pda;
  /** bond account to be deposited to with the provided stake account */
  bond: PublicKey | Pda;
  /** authority that the provided stake account will be assigned to, authority owner is the program */
  bondsStakeAuthority: PublicKey | Pda;
  /** stake account to be deposited */
  stakeAccount: PublicKey | Pda;
  /** authority signature permitting to change the stake_account authorities */
  stakeAuthority: Signer;
  clock: PublicKey | Pda;
  stakeHistory: PublicKey | Pda;
  stakeProgram: PublicKey | Pda;
};

// Instruction.
export function depositBond(
  context: Pick<Context, 'programs'>,
  input: DepositBondInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'validatorBonds',
    'vbondsKbsC4QSLQQnn6ngZvkqfywn6KgEeQbkGSpk1V'
  );

  // Accounts.
  const resolvedAccounts = {
    config: {
      index: 0,
      isWritable: false as boolean,
      value: input.config ?? null,
    },
    bond: { index: 1, isWritable: true as boolean, value: input.bond ?? null },
    bondsStakeAuthority: {
      index: 2,
      isWritable: false as boolean,
      value: input.bondsStakeAuthority ?? null,
    },
    stakeAccount: {
      index: 3,
      isWritable: false as boolean,
      value: input.stakeAccount ?? null,
    },
    stakeAuthority: {
      index: 4,
      isWritable: false as boolean,
      value: input.stakeAuthority ?? null,
    },
    clock: {
      index: 5,
      isWritable: false as boolean,
      value: input.clock ?? null,
    },
    stakeHistory: {
      index: 6,
      isWritable: false as boolean,
      value: input.stakeHistory ?? null,
    },
    stakeProgram: {
      index: 7,
      isWritable: false as boolean,
      value: input.stakeProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = new Uint8Array();

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
