/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  publicKey,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  publicKey as publicKeySerializer,
  struct,
  u64,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type InitConfigInstructionAccounts = {
  /** config root account to init */
  config: Signer;
  /** rent exempt payer for the config (root) account */
  rentPayer?: Signer;
  systemProgram?: PublicKey | Pda;
};

// Data.
export type InitConfigInstructionData = {
  adminAuthority: PublicKey;
  operatorAuthority: PublicKey;
  epochsToClaimSettlement: bigint;
  withdrawLockupEpochs: bigint;
};

export type InitConfigInstructionDataArgs = {
  adminAuthority: PublicKey;
  operatorAuthority: PublicKey;
  epochsToClaimSettlement: number | bigint;
  withdrawLockupEpochs: number | bigint;
};

export function getInitConfigInstructionDataSerializer(): Serializer<
  InitConfigInstructionDataArgs,
  InitConfigInstructionData
> {
  return struct<InitConfigInstructionData>(
    [
      ['adminAuthority', publicKeySerializer()],
      ['operatorAuthority', publicKeySerializer()],
      ['epochsToClaimSettlement', u64()],
      ['withdrawLockupEpochs', u64()],
    ],
    { description: 'InitConfigInstructionData' }
  ) as Serializer<InitConfigInstructionDataArgs, InitConfigInstructionData>;
}

// Args.
export type InitConfigInstructionArgs = InitConfigInstructionDataArgs;

// Instruction.
export function initConfig(
  context: Pick<Context, 'programs'>,
  input: InitConfigInstructionAccounts & InitConfigInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'validatorBonds',
    'vbondsKbsC4QSLQQnn6ngZvkqfywn6KgEeQbkGSpk1V'
  );

  // Accounts.
  const resolvedAccounts = {
    config: {
      index: 0,
      isWritable: true as boolean,
      value: input.config ?? null,
    },
    rentPayer: {
      index: 1,
      isWritable: true as boolean,
      value: input.rentPayer ?? null,
    },
    systemProgram: {
      index: 2,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: InitConfigInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'splSystem',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getInitConfigInstructionDataSerializer().serialize(
    resolvedArgs as InitConfigInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
