/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  publicKey as publicKeySerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type MergeInstructionAccounts = {
  /** the config root account under which the bond was created */
  config: PublicKey | Pda;
  sourceStake: PublicKey | Pda;
  destinationStake: PublicKey | Pda;
  stakerAuthority: PublicKey | Pda;
  stakeHistory: PublicKey | Pda;
  clock: PublicKey | Pda;
  stakeProgram: PublicKey | Pda;
};

// Data.
export type MergeInstructionData = {
  discriminator: Array<number>;
  settlement: PublicKey;
};

export type MergeInstructionDataArgs = { settlement: PublicKey };

export function getMergeInstructionDataSerializer(): Serializer<
  MergeInstructionDataArgs,
  MergeInstructionData
> {
  return mapSerializer<MergeInstructionDataArgs, any, MergeInstructionData>(
    struct<MergeInstructionData>(
      [
        ['discriminator', array(u8(), { size: 8 })],
        ['settlement', publicKeySerializer()],
      ],
      { description: 'MergeInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [148, 141, 236, 47, 174, 126, 69, 111],
    })
  ) as Serializer<MergeInstructionDataArgs, MergeInstructionData>;
}

// Args.
export type MergeInstructionArgs = MergeInstructionDataArgs;

// Instruction.
export function merge(
  context: Pick<Context, 'programs'>,
  input: MergeInstructionAccounts & MergeInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'validatorBonds',
    'vbondsKbsC4QSLQQnn6ngZvkqfywn6KgEeQbkGSpk1V'
  );

  // Accounts.
  const resolvedAccounts = {
    config: {
      index: 0,
      isWritable: false as boolean,
      value: input.config ?? null,
    },
    sourceStake: {
      index: 1,
      isWritable: true as boolean,
      value: input.sourceStake ?? null,
    },
    destinationStake: {
      index: 2,
      isWritable: true as boolean,
      value: input.destinationStake ?? null,
    },
    stakerAuthority: {
      index: 3,
      isWritable: false as boolean,
      value: input.stakerAuthority ?? null,
    },
    stakeHistory: {
      index: 4,
      isWritable: false as boolean,
      value: input.stakeHistory ?? null,
    },
    clock: {
      index: 5,
      isWritable: false as boolean,
      value: input.clock ?? null,
    },
    stakeProgram: {
      index: 6,
      isWritable: false as boolean,
      value: input.stakeProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: MergeInstructionArgs = { ...input };

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getMergeInstructionDataSerializer().serialize(
    resolvedArgs as MergeInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
