/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type ResetInstructionAccounts = {
  /** the config root account under which the bond was created */
  config: PublicKey | Pda;
  bond: PublicKey | Pda;
  settlement: PublicKey | Pda;
  /** stake account belonging to authority of the settlement */
  stakeAccount: PublicKey | Pda;
  settlementAuthority: PublicKey | Pda;
  /** authority that manages (owns being withdrawer authority) all stakes account under the bonds program */
  bondsWithdrawerAuthority: PublicKey | Pda;
  stakeHistory: PublicKey | Pda;
  clock: PublicKey | Pda;
  stakeProgram: PublicKey | Pda;
};

// Data.
export type ResetInstructionData = { discriminator: Array<number> };

export type ResetInstructionDataArgs = {};

export function getResetInstructionDataSerializer(): Serializer<
  ResetInstructionDataArgs,
  ResetInstructionData
> {
  return mapSerializer<ResetInstructionDataArgs, any, ResetInstructionData>(
    struct<ResetInstructionData>(
      [['discriminator', array(u8(), { size: 8 })]],
      { description: 'ResetInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [23, 81, 251, 84, 138, 183, 240, 214],
    })
  ) as Serializer<ResetInstructionDataArgs, ResetInstructionData>;
}

// Instruction.
export function reset(
  context: Pick<Context, 'programs'>,
  input: ResetInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'validatorBonds',
    'vbondsKbsC4QSLQQnn6ngZvkqfywn6KgEeQbkGSpk1V'
  );

  // Accounts.
  const resolvedAccounts = {
    config: {
      index: 0,
      isWritable: false as boolean,
      value: input.config ?? null,
    },
    bond: { index: 1, isWritable: false as boolean, value: input.bond ?? null },
    settlement: {
      index: 2,
      isWritable: false as boolean,
      value: input.settlement ?? null,
    },
    stakeAccount: {
      index: 3,
      isWritable: true as boolean,
      value: input.stakeAccount ?? null,
    },
    settlementAuthority: {
      index: 4,
      isWritable: false as boolean,
      value: input.settlementAuthority ?? null,
    },
    bondsWithdrawerAuthority: {
      index: 5,
      isWritable: false as boolean,
      value: input.bondsWithdrawerAuthority ?? null,
    },
    stakeHistory: {
      index: 6,
      isWritable: false as boolean,
      value: input.stakeHistory ?? null,
    },
    clock: {
      index: 7,
      isWritable: false as boolean,
      value: input.clock ?? null,
    },
    stakeProgram: {
      index: 8,
      isWritable: false as boolean,
      value: input.stakeProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getResetInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
