[package]
name = "merkle-tree"
version = "0.0.0"
edition = "2021"

[dependencies]
solana-program = { workspace = true }
fast-math = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
