agents:
  queue: "snapshots"

steps:
  - command: echo "--> Start of concurrency gate"
    concurrency_group: 'validator-bonds/claim-settlements'
    concurrency: 1

  - wait: ~

  - label: ":hammer_and_wrench: :rust: Build"
    commands:
    - '. "$HOME/.cargo/env"'
    - 'cargo build --release --bin list-claimable-epoch'
    - 'cargo build --release --bin claim-settlement'
    artifact_paths:
      - target/release/list-claimable-epoch
      - target/release/claim-settlement

  - wait: ~

  - label: ":campfire: List claimable epochs"
    env:
      # RUST_LOG: debug
    commands:
    - '. "$HOME/.cargo/env"'
    - 'buildkite-agent artifact download --include-retried-jobs target/release/list-claimable-epoch .'
    - 'chmod +x target/release/list-claimable-epoch'
    - 'claimable_epochs_json=$(./target/release/list-claimable-epoch --rpc-url $$RPC_URL)'
    - 'buildkite-agent meta-data set claimable_epochs_json "$$claimable_epochs_json"'

  - wait: ~

  - label: ":floppy_disk: :arrow_left: :cloud: Downloading all epochs merkle trees"
    env:
      gs_bucket: gs://marinade-validator-bonds-mainnet
    commands:
    - 'mkdir ./merkle-trees/'
    - 'claimable_epochs_json=$(buildkite-agent meta-data get claimable_epochs_json)'
    - 'claimable_epochs_num=$(echo "$$claimable_epochs_json" | jq "length")'
    - 'echo "Claimable epochs [$$claimable_epochs_num]: $$claimable_epochs_json"'
    - 'buildkite-agent meta-data set claimable_epochs_num "$$claimable_epochs_num"'
    - |
      if [ "$$claimable_epochs_num" -eq 0 ]; then
        echo "No claimable epochs found"
        exit 0
      fi
    - |
      for epoch in $(echo "$$claimable_epochs_json" | jq ".[]"); do
        gcloud storage cp "$$gs_bucket/$$epoch/settlement-merkle-trees.json" "./merkle-trees/$${epoch}_settlement-merkle-trees.json"
        gcloud storage cp "$$gs_bucket/$$epoch/settlements.json" "./merkle-trees/$${epoch}_settlements.json"
      done
    artifact_paths:
      - "./merkle-trees/*"

  - wait: ~

  - label: ":campfire: Claim settlements"
    env:
      RUST_LOG: info,solana_transaction_builder_executor=debug,solana_transaction_builder=debug,builder_executor=debug,solana_transaction_executor=debug,settlement_pipelines=debug,claim_settlement=debug
      # RUST_BACKTRACE: full
    commands:
    - |
      claimable_epochs_num=$(buildkite-agent meta-data get claimable_epochs_num)
      [ "$$claimable_epochs_num" -eq 0 ] && echo 'No settlement to claim from' && exit 0
    - 'buildkite-agent artifact download --include-retried-jobs "merkle-trees/*" .'
    - '. "$HOME/.cargo/env"'
    - 'buildkite-agent artifact download --include-retried-jobs target/release/claim-settlement .'
    - 'chmod +x target/release/claim-settlement'
    - 'echo "UNKNOWN ERROR" > ./claiming-report.txt'
    - |
      set -o pipefail
      ./target/release/claim-settlement \
        --rpc-url $$RPC_URL \
        --merkle-trees-dir "./merkle-trees/" \
        --operator-authority "$$VALIDATOR_BONDS_OPERATOR_AUTHORITY" \
        --fee-payer "$$VALIDATOR_BONDS_RANDOM_TX_FEE_PAYER" \
        --rent-payer "$$VALIDATOR_BONDS_RANDOM_RENT_PAYER" \
        | tee ./claiming-report.txt
    artifact_paths:
    - "./claiming-report.txt"
  
  - wait: ~
    continue_on_failure: true

  - label: ":mega: Notification settlements claiming"
    commands:
    - 'buildkite-agent artifact download --include-retried-jobs claiming-report.txt .'
    - 'claimable_epochs_json=$(buildkite-agent meta-data get claimable_epochs_json)'
    - |
      claimable_epochs=$(echo "$$claimable_epochs_json" | jq ". | join(\",\")" | tr -d '"')
      curl "$$DISCORD_WEBHOOK_VALIDATOR_BONDS" \
        -F 'payload_json={
            "content": "Claim Settlements for epochs: '"$$claimable_epochs"'",
            "url": "'"$$BUILDKITE_BUILD_URL"'",
            "color": "8388863"
        }' \
        -F "file1=@./claiming-report.txt"

  - wait: ~

  - command: echo "End of concurrency gate <--"
    concurrency_group: 'validator-bonds/claim-settlements'
    concurrency: 1
