agents:
  queue: "snapshots"

env:
  gs_bucket: gs://marinade-validator-bonds-mainnet

steps:
  - label: ":closed_lock_with_key: Concurrency gate lock"
    command: echo "--> Start of concurrency gate"
    concurrency_group: 'validator-bonds/close-settlements'
    concurrency: 1

  - wait: ~

  - label: ":hammer_and_wrench: :rust: Build"
    commands:
    - '. "$HOME/.cargo/env"'
    - 'cargo build --release --bin list-settlement'
    - 'cargo build --release --bin close-settlement'
    artifact_paths:
      - target/release/list-settlement
      - target/release/close-settlement

  - label: " Loading past settlements data"
    env:
      config_epochs_non_closable: 3 # configured onchain in config
      past_epochs_to_load: 5
      # epoch when the contract v2 was deployed, using different structure of merkle tree than v1
      starting_epoch_contract_v2: 640
    commands:
    - |
      set -x
      current_epoch=$(curl --silent "$$RPC_URL" -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"getEpochInfo"}' | jq '.result.epoch')
      epochs_end_index=$((current_epoch - config_epochs_non_closable))
      epochs_start_index=$((epochs_end_index - past_epochs_to_load))
    - 'mkdir ./merkle-trees/'
    - |
      if [[ $$epochs_start_index -lt 1 ]]; then
        echo "No found any epoch to start to load settlement JSON files"
        exit 1
      fi
    - |
      for epoch in $(seq $$epochs_start_index $$epochs_end_index); do
        if [[ $$epoch -lt $$starting_epoch_contract_v2 ]]; then
          echo "Skipping epoch $$epoch, because it's before the contract v2 deployment epoch $$starting_epoch_contract_v2"
          continue
        fi
        for merkle_tree_file in $(gcloud storage ls "$gs_bucket/$$epoch/*settlement-merkle-trees.json"); do
          base_name=$(basename "$$merkle_tree_file")
          gcloud storage cp "$$merkle_tree_file" "./merkle-trees/$${epoch}_$${base_name}"
        done
      done
    artifact_paths:
      - "./merkle-trees/*"

  - wait: ~

  - label: ":campfire: List past settlements"
    env:
      RUST_LOG: info,solana_transaction_builder_executor=debug,solana_transaction_builder=debug,solana_transaction_executor=debug,list_settlement=debug
    commands:
    - '. "$HOME/.cargo/env"'
    - 'buildkite-agent artifact download --include-retried-jobs "merkle-trees/*" .'
    - 'buildkite-agent artifact download --include-retried-jobs target/release/list-settlement .'
    - 'chmod +x target/release/list-settlement'
    - './target/release/list-settlement -u $$RPC_URL -m ./merkle-trees/* --out ./past-settlements.json'
    artifact_paths:
      - "./past-settlements.json"

  - wait: ~

  - label: ":campfire::arrow_right: Close settlements"
    env:
      RUST_LOG: info,solana_transaction_builder_executor=debug,solana_transaction_builder=debug,solana_transaction_executor=debug,close_settlement=debug
      # RUST_BACKTRACE: full
    commands:
    - '. "$HOME/.cargo/env"'
    - 'prior_build_number=$(($$BUILDKITE_RETRY_COUNT - 1))'
    - 'buildkite-agent artifact download --include-retried-jobs close-execution-report.$$prior_build_number . || true'
    - |
      cp "close-execution-report.$$prior_build_number" "close-execution-report.$$BUILDKITE_RETRY_COUNT" || true
      rm -f "close-execution-report.$$prior_build_number"
      echo "#ATTEMPT $$BUILDKITE_RETRY_COUNT" | tee -a "./close-execution-report.$$BUILDKITE_RETRY_COUNT"
    - 'buildkite-agent artifact download --include-retried-jobs target/release/close-settlement .'
    - 'buildkite-agent artifact download --include-retried-jobs past-settlements.json .'
    - 'chmod +x target/release/close-settlement'
    - |
      set -o pipefail
      ./target/release/close-settlement \
        --rpc-url $$RPC_URL \
        --operator-authority "$$VALIDATOR_BONDS_OPERATOR_AUTHORITY" \
        --fee-payer "$$PSR_TX_FEE_WALLET" \
        --marinade-wallet "$$PSR_MARINADE_DAO_FUNDER_WALLET" \
        --past-settlements ./past-settlements.json | tee -a "./close-execution-report.$$BUILDKITE_RETRY_COUNT"
    key: 'close-settlement'
    artifact_paths:
      - "./close-execution-report.*"
    retry:
      automatic:
        - exit_status: 100
          limit: 5

  - label: ":memo: Notification setup: Close Settlements"
    commands:
     - 'mkdir ./reports'
     - 'buildkite-agent artifact download --include-retried-jobs "close-execution-report.*" ./reports/ || echo "No report ERROR" > ./reports/close-execution-report.error'
     - 'report_path="./reports/$(ls -v1 reports/ | tail -n 1)"'
     - 'cp "$$report_path" ./close-report.txt'
     - 'buildkite-agent meta-data set attempts_count "$(grep -c ATTEMPT ./close-report.txt)"'
    artifact_paths:
    - "./close-report.txt"
    key: 'notification'
    depends_on: "close-settlement"
    allow_dependency_failure: true

  - wait: ~

  - label: ":mega: Notification Closing"
    commands:
    - 'build_result=$(buildkite-agent step get "outcome" --step "close-settlement")'
    - |
      if [[ -z "$$build_result" || "$$build_result" =~ "failed" ]]; then
        notification_result="FAILED"
        notification_color="15158332"
      else
        notification_result="SUCCEEDED"
        notification_color="52224"
      fi
    - |
      attempts_count=$(buildkite-agent meta-data get attempts_count || echo "UNKNOWN")
      buildkite-agent artifact download --include-retried-jobs close-report.txt . || echo 'UNKNOWN ERROR' > './close-report.txt'
      curl "$$DISCORD_WEBHOOK_VALIDATOR_BONDS" \
        -F 'payload_json={
            "embeds":[{
              "title": "Close Settlements '"$$notification_result"', '"$$attempts_count"' attempts",
              "url": "'"$$BUILDKITE_BUILD_URL"'",
              "color": "'"$$notification_color"'"
            }]
        }' \
        -F "file1=@./close-report.txt"
    depends_on: "notification"
    allow_dependency_failure: true

  - wait: ~

  - label: ":unlock: Concurrency gate unlock"
    command: echo "End of concurrency gate <--"
    concurrency_group: 'validator-bonds/close-settlements'
    concurrency: 1
