agents:
  queue: "snapshots"

steps:
  - label: ":hammer_and_wrench: :rust: Build"
    commands:
    - source "$HOME/.cargo/env"
    - cargo build --release --bin bonds-collector --bin validator-bonds-api-cli
    artifact_paths:
      - target/release/bonds-collector
      - target/release/validator-bonds-api-cli

  - input: "What is the Bonds Config type to collect?"
    fields:
      - select: "Claim type"
        key: "claim_type"
        options:
          - label: "Bidding Bonds Config"
            value: "bid"
          - label: "Institutional Bonds Config"
            value: "institutional"
    if: "build.env('CLAIM_TYPE') == null"
    blocked_state: running

  - wait: ~

  - label: ":closed_lock_with_key: Concurrency gate lock"
    command: echo "--> Start of concurrency gate"
    concurrency_group: 'validator-bonds/collect-bonds-${CLAIM_TYPE}'
    concurrency: 1

  - wait: ~

  - label: ":microscope: Collect Bonds"
    key: collect-bonds
    env:
      RPC_URL: "$$RPC_URL"
    commands:
    - |
      claim_type=${CLAIM_TYPE:-$(buildkite-agent meta-data get claim_type)}
      bond_type=$([[ "$$claim_type" == "bid" ]] && echo "bidding" || echo "institutional")
    - buildkite-agent artifact download --include-retried-jobs target/release/bonds-collector .
    - chmod +x target/release/bonds-collector
    - |
      ./target/release/bonds-collector collect-bonds \
        --bond-type $$bond_type > bonds.yaml
    artifact_paths:
      - bonds.yaml

  - wait: ~

  - label: ":microscope: Store Bonds"
    commands:
    - buildkite-agent artifact download --include-retried-jobs target/release/validator-bonds-api-cli .
    - buildkite-agent artifact download --include-retried-jobs bonds.yaml .
    - chmod +x target/release/validator-bonds-api-cli
    - curl https://truststore.pki.rds.amazonaws.com/eu-west-1/eu-west-1-bundle.pem -o ./eu-west-1-bundle.pem
    - |
      ./target/release/validator-bonds-api-cli \
        store-bonds --postgres-url "$$POSTGRES_URL" --postgres-ssl-root-cert ./eu-west-1-bundle.pem --input-file bonds.yaml

  - label: ":unlock: Concurrency gate unlock"
    command: echo "End of concurrency gate <--"
    concurrency_group: 'validator-bonds/collect-bonds-${CLAIM_TYPE}'
    concurrency: 1


  - group: ":memo: Annotations"
    steps:
      - label: ":memo: Annotate retry parameters"
        dependent_on: collect-bonds
        allow_dependency_failure: true
        commands:
          - claim_type=${CLAIM_TYPE:-$(buildkite-agent meta-data get claim_type)}
          - |
            cat <<- EOF | buildkite-agent annotate --style info --context "general-info"
            ### Retry environment variables
            If you need to retry the build, use the following parameters:
            
            \`\`\`
            CLAIM_TYPE=$$claim_type
            \`\`\`
            EOF
