agents:
  queue: "snapshots"

steps:
  - label: ":hammer_and_wrench: :rust: Build"
    commands:
    - '. "$HOME/.cargo/env"'
    - 'cargo build --release --bin validator-bonds-cli --bin validator-bonds-api-cli'
    artifact_paths:
      - target/release/validator-bonds-cli
      - target/release/validator-bonds-api-cli

  - wait: ~

  - label: ":gear: Setup"
    commands:
    - '. "$HOME/.cargo/env"'

  - wait: ~

  - command: echo "--> Start of concurrency gate"
    concurrency_group: 'validator-bonds/collect-bonds'
    concurrency: 1

  - wait: ~

  - label: ":microscope: Collect Bonds"
    commands:
    - 'buildkite-agent artifact download --include-retried-jobs target/release/validator-bonds-cli .'
    - 'chmod +x target/release/validator-bonds-cli'
    - |
      ./target/release/validator-bonds-cli \
        collect-bonds -u "$RPC_URL" > bonds.yaml
    artifact_paths:
      - bonds.yaml

  - wait: ~

  - label: ":microscope: Store Bonds"
    commands:
    - 'buildkite-agent artifact download --include-retried-jobs target/release/validator-bonds-api-cli .'
    - 'buildkite-agent artifact download --include-retried-jobs bonds.yaml .'
    - 'chmod +x target/release/validator-bonds-api-cli'
    - |
      ./target/release/validator-bonds-api-cli \
        store-bonds --postgres-url "$POSTGRES_URL" --input-file bonds.yaml

  - command: echo "End of concurrency gate <--"
    concurrency_group: 'validator-bonds/collect-bonds'
    concurrency: 1
