agents:
  queue: "snapshots"

steps:
  - command: echo "--> Start of concurrency gate"
    concurrency_group: 'validator-bonds/fetch'
    concurrency: 1

  - input: "Which epoch to fetch?"
    fields:
      - text: "Epoch"
        key: "epoch"
        format: "[0-9]+"
    if: "build.env('EPOCH') == null"

  - wait: ~

  - label: ":mega: Notification"
    commands:
    - |
      epoch=${EPOCH:-$(buildkite-agent meta-data get epoch)}
      curl "$$DISCORD_WEBHOOK_VALIDATOR_BONDS" -H "Content-Type: application/json" -d '{
        "embeds": [
          {
            "title": "Preparing claims for Validator Bonds ('"$$epoch"').",
            "url": "'"$$BUILDKITE_BUILD_URL"'",
            "color": "8388863"
          }
        ]
      }'

  - label: ":file_folder: Prepare snapshot directory"
    env:
      target_dir: /mnt/storage-1/snapshots
    commands:
    - 'mkdir -p /mnt/storage-1/snapshots'
    - 'epoch=${EPOCH:-$(buildkite-agent meta-data get epoch)}'
    - 'snapshot_dir=$(mktemp --directory -p "$$target_dir" "snapshot-$$epoch-$(date +%s)-XXXXXX")'
    - 'buildkite-agent meta-data set snapshot_dir "$$snapshot_dir"'

  - wait: ~

  - label: ":cloud: :arrow_right: :floppy_disk: Fetch genesis"
    commands:
    - 'snapshot_dir=$(buildkite-agent meta-data get snapshot_dir)'
    - './scripts/fetch-genesis.bash "$$snapshot_dir"'

  - label: ":cloud: :arrow_right: :floppy_disk: Fetch snapshot"
    commands:
    - 'snapshot_dir=$(buildkite-agent meta-data get snapshot_dir)'
    - 'epoch=${EPOCH:-$(buildkite-agent meta-data get epoch)}'
    - './scripts/fetch-jito-snapshot.bash "$$epoch" "$$snapshot_dir"'

  - wait: ~

  - label: ":gear: Setup trigger"
    commands:
    - 'snapshot_dir=$(buildkite-agent meta-data get snapshot_dir)'
    - |
      cat <<EOF | buildkite-agent pipeline upload
      steps:
        - trigger: "prepare-claims"
          label: ":rocket: Trigger: Prepare claims ($$snapshot_dir)"
          async: false
          build:
            branch: $$BUILDKITE_BRANCH
            env:
              SNAPSHOT_DIR: $$snapshot_dir
      EOF

  - wait: ~

  - command: echo "End of concurrency gate <--"
    concurrency_group: 'validator-bonds/fetch'
    concurrency: 1
