agents:
  queue: "snapshots"

steps:
  - input: "Which epoch to fetch?"
    fields:
      - text: "Epoch"
        key: "epoch"
        format: "[0-9]+"
    if: "build.env('EPOCH') == null"

  # - label: ":calendar: Get epoch"
  #   env:
  #     target_dir: /mnt/storage-1/snapshots
  #   commands:
  #   - 'mkdir -p /mnt/storage-1/snapshots'
  #   - 'PATH="/var/lib/buildkite-agent/.local/share/solana/install/active_release/bin:$PATH"'
  #   - 'current_epoch=$(solana epoch || exit 1)'
  #   - 'epoch=$((current_epoch - 1))'


  #   - 'buildkite-agent meta-data set epoch "$$epoch"'
  #   if: "build.env('EPOCH') != null"

  - wait: ~

  - label: ":file_folder: Prepare snapshot directory"
    env:
      target_dir: /mnt/storage-1/snapshots
    commands:
    - 'mkdir -p /mnt/storage-1/snapshots'
    - 'epoch=${EPOCH:-$(buildkite-agent meta-data get epoch)}'
    - 'snapshot_dir=$(mktemp --directory -p "$$target_dir" "snapshot-$$epoch-$(date +%s)-XXXXXX")'
    - 'buildkite-agent meta-data set snapshot_dir "$$snapshot_dir"'

  - wait: ~

  - label: ":cloud: :arrow_right: :floppy_disk: Fetch genesis"
    commands:
    - 'snapshot_dir=$(buildkite-agent meta-data get snapshot_dir)'
    - './scripts/fetch-genesis.bash "$$snapshot_dir"'

  - label: ":cloud: :arrow_right: :floppy_disk: Fetch snapshot"
    commands:
    - 'snapshot_dir=$(buildkite-agent meta-data get snapshot_dir)'
    - 'epoch=${EPOCH:-$(buildkite-agent meta-data get epoch)}'
    - './scripts/fetch-jito-snapshot.bash "$$epoch" "$$snapshot_dir"'
