agents:
  queue: "snapshots"

steps:
  - label: ":file_folder: Prepare workspace"
    env:
      target_dir: /mnt/storage-1/snapshots
    commands:
    - 'mkdir -p /mnt/storage-1/snapshots'
    - 'PATH="/var/lib/buildkite-agent/.local/share/solana/install/active_release/bin:$PATH"'
    - 'epoch=$(solana epoch || exit 1)'
    - 'previous_epoch=$((epoch - 1))'

    - 'snapshot_dir=$(mktemp --directory -p "$$target_dir" "snapshot-$$previous_epoch-XXXXXX")'

    - 'buildkite-agent meta-data set snapshot_dir "$$snapshot_dir"'
    - 'buildkite-agent meta-data set previous_epoch "$$previous_epoch"'

  - wait: ~

  - label: ":cloud: :arrow_right: :floppy_disk: Fetch genesis"
    commands:
    - 'snapshot_dir=$(buildkite-agent meta-data get snapshot_dir)'
    - './scripts/fetch-genesis.bash "$$snapshot_dir"'

  - label: ":cloud: :arrow_right: :floppy_disk: Fetch snapshot"
    commands:
    - 'snapshot_dir=$(buildkite-agent meta-data get snapshot_dir)'
    - 'previous_epoch=$(buildkite-agent meta-data get previous_epoch)'
    - './scripts/fetch-jito-snapshot.bash "$$previous_epoch" "$$snapshot_dir"'
