agents:
  queue: "snapshots"

steps:
  # epoch number provided in env or prompted
  - input: "What is the epoch to init settlements for?"
    fields:
      - text: "Epoch"
        key: "epoch"
        format: "[0-9]+"
    if: "build.env('EPOCH') == null"

  - command: "echo 'Epoch is: $$EPOCH'"
    if: "build.env('EPOCH') != null"
  - block: "Confirm to get processed init settlements"
    prompt: "Please review the 'Unblock' if ready to proceed."
    if: "build.env('EPOCH') != null"

  - label: ":hammer_and_wrench: :rust: Build"
    commands:
    - '. "$HOME/.cargo/env"'
    - 'cargo build --release --bin init-settlement'
    artifact_paths:
      - target/release/init-settlement

  - wait: ~

  - label: ":mega: Notification initializing settlements"
    commands:
    - |
      epoch=${EPOCH:-$(buildkite-agent meta-data get epoch)}
      curl "$$DISCORD_WEBHOOK_VALIDATOR_BONDS" -H "Content-Type: application/json" -d '{
        "embeds": [
          {
            "title": "Initializing Settlements for Validator Bonds ('"$$epoch"').",
            "url": "'"$$BUILDKITE_BUILD_URL"'",
            "color": "8388863"
          }
        ]
      }'

  - label: ":gear: Setup"
    commands:
    - '. "$HOME/.cargo/env"'
    - 'epoch=$(buildkite-agent meta-data get epoch)'
    - 'buildkite-agent meta-data set epoch "$$epoch"'
    - 'echo "Epoch: $$epoch"'

  - wait: ~

  - command: echo "--> Start of concurrency gate"
    concurrency_group: 'validator-bonds/init-settlements'
    concurrency: 1

  - wait: ~

  - label: ":floppy_disk: :arrow_left: :cloud: Downloading merkle trees"
    env:
      gs_bucket: gs://marinade-validator-bonds-mainnet
    commands:
    - 'epoch=$(buildkite-agent meta-data get epoch)'
    - |
      gcloud storage cp "$$gs_bucket/$$epoch/settlement-merkle-trees.json" "."
      gcloud storage cp "$$gs_bucket/$$epoch/settlements.json" "."
    artifact_paths:
      - "./settlement-merkle-trees.json"
      - "./settlements.json"
  
  - wait: ~

  - label: ":campfire: Create settlements"
    env:
      RUST_LOG: trace
      RUST_BACKTRACE: full
    commands:
    - 'epoch=$(buildkite-agent meta-data get epoch)'
    - 'buildkite-agent artifact download --include-retried-jobs target/release/init-settlement .'
    - 'buildkite-agent artifact download --include-retried-jobs settlement-merkle-trees.json .'
    - 'buildkite-agent artifact download --include-retried-jobs settlements.json .'
    - 'chmod +x target/release/init-settlement'
    # TODO: MOVE api from devnet to rpc url
    - |
      ./target/release/init-settlement \
        --rpc-url https://api.devnet.solana.com \
        --input-merkle-tree-collection "./settlement-merkle-trees.json" \
        --input-settlement-collection "./settlements.json" \
        --operator-authority "$$VALIDATOR_BONDS_OPERATOR_AUTHORITY" \
        --fee-payer "$$VALIDATOR_BONDS_FUNDING_WALLET" \
        --epoch "$$epoch"
    retry:
      automatic:
        - exit_status: '*'
          limit: 10

  - wait: ~
    continue_on_failure: true

  # TODO: reporting data from create settlement has to be sent to discord
  - label: ":mega: Notification settlements initialized"
    commands:
    - |
      epoch=${EPOCH:-$(buildkite-agent meta-data get epoch)}
      curl "$$DISCORD_WEBHOOK_VALIDATOR_BONDS" -H "Content-Type: application/json" -d '{
        "embeds": [
          {
            "title": "Settlements Initialized for Validator Bonds ('"$$epoch"').",
            "url": "'"$$BUILDKITE_BUILD_URL"'",
            "color": "8388863"
          }
        ]
      }'

  - command: echo "End of concurrency gate <--"
    concurrency_group: 'validator-bonds/init-settlements'
    concurrency: 1
