agents:
  queue: "snapshots"

steps:
  # epoch number provided in ENV and then waiting for confirmation to proceed
  # or waiting to be prompted by the user after notification is sent
  - input: "What is the epoch to init settlements for?"
    fields:
      - text: "Epoch"
        key: "epoch"
        format: "[0-9]+"
    if: "build.env('EPOCH') == null"
  - command: "echo 'Epoch is: $EPOCH'"
    if: "build.env('EPOCH') != null"

  - wait: ~

  - label: ":mega: Notification initializing settlements"
    commands:
    - 'epoch=${EPOCH:-$(buildkite-agent meta-data get epoch)}'
    - 'buildkite-agent meta-data set epoch "$$epoch"'
    - 'echo "Epoch: $$epoch"'
    - |
      curl "$$DISCORD_WEBHOOK_VALIDATOR_BONDS" \
        -H "Content-Type: application/json" -d '{
        "embeds": [
          {
            "title": "Confirm Settlements Initialization for Validator Bonds ('"$$epoch"').",
            "description": "Please review the 'Unblock' if ready to proceed.",
            "url": "'"$$BUILDKITE_BUILD_URL"'",
            "color": "8388863"
          }
        ]
      }'

  - wait: ~
    
  - label: ":hammer_and_wrench: :rust: Build"
    commands:
    - '. "$HOME/.cargo/env"'
    - 'cargo build --release --bin init-settlement'
    artifact_paths:
      - target/release/init-settlement
  
  - label: ":floppy_disk: :arrow_left: :cloud: Downloading merkle trees"
    env:
      gs_bucket: gs://marinade-validator-bonds-mainnet
    commands:
    - 'epoch=$(buildkite-agent meta-data get epoch)'
    - |
      gcloud storage cp "$$gs_bucket/$$epoch/settlement-merkle-trees.json" "."
      gcloud storage cp "$$gs_bucket/$$epoch/settlements.json" "."
    key: 'download-json'
    artifact_paths:
      - "./settlement-merkle-trees.json"
      - "./settlements.json"  
      
  - label: "Settlement JSON listing"
    commands:
     - 'buildkite-agent artifact download --include-retried-jobs settlement-merkle-trees.json .'
     - 'buildkite-agent artifact download --include-retried-jobs settlements.json .'
     - 'bash ./scripts/settlement-json-listing.sh --settlements settlements.json --merkle-trees settlement-merkle-trees.json'
    depends_on: "download-json"
  
  - wait: ~

  - block: "Confirm to get processed init settlements"
    prompt: "Please review the 'Unblock' if ready to proceed."
    blocked_state: running

  - wait: ~

  - command: echo "--> Start of concurrency gate"
    concurrency_group: 'validator-bonds/init-settlements'
    concurrency: 1

  - wait: ~

  - label: ":campfire: Create settlements"
    env:
      RUST_LOG: info,solana_transaction_builder_executor=debug,solana_transaction_builder=debug,builder_executor=debug,solana_transaction_executor=debug,settlement_pipelines=debug,init_settlement=debug
      #  RUST_BACKTRACE: full
    commands:
    - '. "$HOME/.cargo/env"'
    - 'epoch=$(buildkite-agent meta-data get epoch)'
    - 'prior_build_number=$(($$BUILDKITE_RETRY_COUNT - 1))'
    - 'buildkite-agent artifact download --include-retried-jobs build-report.$$prior_build_number . || true'
    - |
      cp "build-report.$$prior_build_number" "build-report.$$BUILDKITE_RETRY_COUNT" || true
      rm -f "build-report.$$prior_build_number"
      echo "#ATTEMPT $$BUILDKITE_RETRY_COUNT" | tee -a "./build-report.$$BUILDKITE_RETRY_COUNT"
    - 'buildkite-agent artifact download --include-retried-jobs target/release/init-settlement .'
    - 'buildkite-agent artifact download --include-retried-jobs settlement-merkle-trees.json .'
    - 'buildkite-agent artifact download --include-retried-jobs settlements.json .'
    - 'chmod +x target/release/init-settlement'
    - |
      set -o pipefail
      ./target/release/init-settlement \
        --rpc-url $$RPC_URL \
        --input-merkle-tree-collection "./settlement-merkle-trees.json" \
        --input-settlement-collection "./settlements.json" \
        --operator-authority "$$VALIDATOR_BONDS_OPERATOR_AUTHORITY" \
        --fee-payer "$$VALIDATOR_BONDS_SETTLEMENTS_WALLET" \
        --rent-payer "$$VALIDATOR_BONDS_SETTLEMENTS_WALLET" \
        --epoch "$$epoch" | tee -a "./build-report.$$BUILDKITE_RETRY_COUNT"
    key: 'init-settlement'
    artifact_paths:
    - "./build-report.*"
    retry:
      automatic:
        - exit_status: 100
          limit: 5

  - label: "Notification setup"
    env:
      gs_bucket: gs://marinade-validator-bonds-mainnet
    commands:
     - 'epoch=$(buildkite-agent meta-data get epoch)'
     - |
       build_result=$(buildkite-agent step get "outcome" --step "init-settlement")
        if [[ -z "$$build_result" || "$$build_result" =~ "failed" ]]; then
          notification_result="FAILED"
          notification_color="15158332"
        else
          notification_result="SUCCEEDED"
          notification_color="52224"
        fi
     - 'buildkite-agent meta-data set notification_color "$$notification_color"'
     - 'buildkite-agent meta-data set notification_result "$$notification_result"'
     - 'echo "Notification result: $$notification_result, color: $$notification_color"'
     - 'mkdir ./reports'
     - 'buildkite-agent artifact download --include-retried-jobs "build-report.*" ./reports/'
     - 'report_path="./reports/$(ls -v1 reports/ | tail -n 1)"'
     - '[[ -f "$$report_path" ]] || echo "No report generated; UNKNOWN ERROR" >> "$$report_path"'
     - 'cp "$$report_path" ./init-report.txt'
     - 'gcloud storage cp ./init-report.txt "$$gs_bucket/$$epoch/init-settlement-report.$(date +%s).txt"'
     - 'buildkite-agent meta-data set attempts_count "$(grep -c ATTEMPT ./init-report.txt)"'
    artifact_paths:
    - "./init-report.txt"
    key: 'notification'
    depends_on: "init-settlement"
    allow_dependency_failure: true

  - wait: ~
    continue_on_failure: true

  - label: ":mega: Notification settlements initialized"
    commands:
    - 'epoch=$(buildkite-agent meta-data get epoch)'
    - 'notification_result=$(buildkite-agent meta-data get notification_result || echo "UNKNOWN")'
    - 'notification_color=$(buildkite-agent meta-data get notification_color || echo "15158332")'
    - 'attempts_count=$(buildkite-agent meta-data get attempts_count || echo "UNKNOWN")'
    - 'buildkite-agent artifact download --include-retried-jobs init-report.txt . || echo "UNKNOWN ERROR" > init-report.txt'
    - |
        curl "$$DISCORD_WEBHOOK_VALIDATOR_BONDS" \
        -F 'payload_json={
            "embeds":[{
              "title": "Init Settlements '"$notification_result"' for Validator Bonds ('"$$epoch"') after '"$$attempts_count"' attempts",
              "url": "'"$$BUILDKITE_BUILD_URL"'",
              "color": "'"$$notification_color"'"
            }]
        }' \
        -F "file1=@./init-report.txt"
    depends_on: "notification"
    allow_dependency_failure: true

  - command: echo "End of concurrency gate <--"
    concurrency_group: 'validator-bonds/init-settlements'
    concurrency: 1
