agents:
  queue: "snapshots"

env:
  gs_bucket: gs://marinade-validator-bonds-mainnet
  SLACK_API: https://slack.com/api/chat.postMessage
  SLACK_FEED: "feed-pipeline-sam-psr"

steps:
  - label: ":memo: Annotate retry parameters"
    commands:
      - |
        cat <<- EOF | buildkite-agent annotate --priority 6 --style info --context "general-info"
        ### Retry environment variables
        If you need to retry the build, use the following parameters:

        \`\`\`
        SLACK_FEED=$SLACK_FEED
        NOTIFY_FEED=${NOTIFY_FEED:-false}
        \`\`\`
        EOF

  - label: ":closed_lock_with_key: Concurrency gate lock"
    key: "concurrency-lock"
    command: echo "--> Start of concurrency gate"
    concurrency_group: "validator-bonds/merge-stakes"
    concurrency: 1

  - wait: ~

  - label: ":hammer_and_wrench: :rust: Build Merge Stakes"
    commands:
    - '. "$HOME/.cargo/env"'
    - 'cargo build --release --bin merge-stakes'
    artifact_paths:
      - target/release/merge-stakes

  - wait: ~

  - label: ":campfire::arrow_right: Merge Stakes: {{matrix}}"
    env:
      RPC_URL: "$$RPC_URL"
      RUST_LOG: info,solana_transaction_builder_executor=debug,solana_transaction_builder=debug,solana_transaction_executor=debug,merge_stakes=debug
    commands:
    - . "$HOME/.cargo/env"
    - command_name='merge-stakes'
    - buildkite-agent artifact download --include-retried-jobs target/release/$${command_name} .
    - chmod +x target/release/$${command_name}
    - source ./scripts/execute-handlers.sh
    - |
      echo "{{matrix}}" | tr ',' '\n' | while read -r address; do
        echo "Merging stakes for config address $$address"
        handle_command_execution "$$command_name" \
        ./target/release/$$command_name \
          --config $$address \
          --keypair "$$PSR_TX_FEE_WALLET"
      done
    key: "merge-stakes"
    matrix:
      - "vbMaRfmTCg92HWGzmd53APkMNpPnGVGZTUHwUJQkXAU"
      - "VbinSTyUEC8JXtzFteC4ruKSfs6dkQUUcY6wB1oJyjE"
    artifact_paths:
      - "./report.*.json"
    retry:
      automatic:
        - exit_status: 100
          limit: 5

  - label: ":memo: Notification setup: Merge Stakes"
    key: "notification-setup-merge-stakes"
    commands:
    - mkdir ./reports
    - command_name='merge-stakes'
    - |
      buildkite-agent artifact download --include-retried-jobs "report.$$command_name.*.json" ./reports/ || echo '{"command":"merge-stakes","status":{"success":false,"error_count":1},"summary":"No report found"}' > "./reports/report.$$command_name.0.json"
    - report_path="./reports/$(ls -v1 reports/ | tail -n 1)"
    - cp "$$report_path" ./$${command_name}-report.json
    - attempts_count=$$(ls -1 ./reports/report.$$command_name.*.json 2>/dev/null | wc -l)
    - buildkite-agent meta-data set --redacted-vars='' attempts_count "$$attempts_count"
    artifact_paths:
    - "./merge-stakes-report.json"
    depends_on: "merge-stakes"
    allow_dependency_failure: true

  - wait: ~

  - label: ":floppy_disk: :arrow_right: :cloud: Upload artifacts Merge Stakes"
    commands:
    - report_file='merge-stakes-report.json'
    - buildkite-agent artifact download --include-retried-jobs $${report_file} . || echo '"UNKNOWN ERROR"' > ./$${report_file}
    - cat ./merge-stakes-report.json
    - |
      current_epoch=$(curl --silent "$$RPC_URL" -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"getEpochInfo"}' | jq '.result.epoch')
    - report_epoch=$((current_epoch - 1))
    - |
      echo "Checking existence of path '$gs_bucket/$$report_epoch' to upload the report"
      if [[ -n "$$report_epoch" && $(gcloud storage ls "$gs_bucket/$$report_epoch" 2> /dev/null) ]]; then
        gcloud storage cp ./$${report_file} "$gs_bucket/$$report_epoch/buildkite/merge-stakes-report.$(date +%s).json"
      fi
    depends_on: "notification-setup-merge-stakes"
    allow_dependency_failure: true

  - label: ":mega: Notification Merge Stakes"
    commands:
    - source ./scripts/execute-handlers.sh
    - check_command_execution_status "merge-stakes" || true
    - attempts_count=$(buildkite-agent meta-data get attempts_count || echo "UNKNOWN")
    - |
      curl $SLACK_API -X POST -H 'Content-Type: application/json; charset=utf-8' \
        -H "Authorization: Bearer $$SLACK_BEARER_TOKEN" -d '{
        "channel": "'"${SLACK_FEED}"'",
        "attachments": [{
          "color": "'"$$notification_color"'",
          "title": "Merge Stakes '"$${notification_result}"', '"$$attempts_count"' attempts",
          "title_link": "'"$${BUILDKITE_BUILD_URL}/#$${BUILDKITE_JOB_ID}"'",
          "footer": "<'"$${BUILDKITE_BUILD_URL}/#$${BUILDKITE_JOB_ID}"'|View in Buildkite>"
        }]
      }'
    depends_on: "notification-setup-merge-stakes"
    allow_dependency_failure: true
    if: "build.env('NOTIFY_FEED') == 'true'"

  - wait: ~

  - label: ":unlock: Concurrency gate unlock"
    command: echo "End of concurrency gate <--"
    concurrency_group: 'validator-bonds/merge-stakes'
    concurrency: 1
