agents:
  queue: "snapshots"

env:
  gs_bucket: gs://marinade-validator-bonds-mainnet
  gs_bucket_etl: gs://marinade-stakes-etl-mainnet
  MARINADE_SCORING_API_URL: https://scoring.marinade.finance/api/v1
  SLACK_API: https://slack.com/api/chat.postMessage
  SLACK_FEED: "feed-pipeline-sam-psr"
  ds_sam_auction_github_api_link: "https://api.github.com/repos/marinade-finance/ds-sam-pipeline/contents/auctions/"
  ds_sam_auction_download_link: "https://raw.githubusercontent.com/marinade-finance/ds-sam-pipeline/main/auctions/"

steps:
  - label: ":hammer_and_wrench: :rust: Build CLI"
    commands:
    - '. "$HOME/.cargo/env"'
    - 'cargo build --release --bin bid-distribution-cli'
    artifact_paths:
      - target/release/bid-distribution-cli

  - input: "What is the epoch to generate settlements for?"
    fields:
      - text: "Epoch"
        key: "epoch"
        format: "[0-9]+"
    if: "build.env('EPOCH') == null"
    blocked_state: running

  - wait: ~

  - label: ":closed_lock_with_key: Concurrency gate lock"
    command: echo "--> Start of concurrency gate"
    concurrency_group: 'validator-bonds/prepare-bid-distribution'
    concurrency: 1

  - wait: ~

  - label: ":black_nib: Env variables setup: Prepare Bid Distribution"
    key: "setup-env-prepare-bid"
    commands:
    - |
      epoch=${EPOCH:-$(buildkite-agent meta-data get epoch)}
      buildkite-agent meta-data set --redacted-vars='' epoch "$$epoch"
      echo "Epoch: '$$epoch'"

  - label: ":memo: Annotate retry parameters"
    depends_on: "setup-env-prepare-bid"
    allow_dependency_failure: true
    commands:
      - epoch=${EPOCH:-$(buildkite-agent meta-data get epoch)}
      - |
        cat <<- EOF | buildkite-agent annotate --priority 6 --style info --context "general-info"
        ### Retry environment variables
        If you need to retry the build, use the following parameters:

        \`\`\`
        EPOCH=$$epoch
        MARINADE_SCORING_API_URL=$MARINADE_SCORING_API_URL
        SLACK_FEED=$SLACK_FEED
        NOTIFY_FEED=${NOTIFY_FEED:-false}
        \`\`\`
        EOF

  - wait: ~

  # Download all required input data in parallel
  - label: ":floppy_disk: :arrow_left: :cloud: Download SAM scores and stakes"
    key: "download-sam-stakes"
    commands:
    - epoch=$(buildkite-agent meta-data get epoch)
    - |
      curl -s "${MARINADE_SCORING_API_URL}/scores/sam?epoch=$$epoch" -o sam-scores.json
      if [ $(jq '. | length' ./sam-scores.json) -eq 0 ]; then
        echo "No SAM scores found for epoch $$epoch"
        exit 1
      fi
      gcloud storage cp "$gs_bucket/$$epoch/stakes.json" "."
    artifact_paths:
      - "./sam-scores.json"
      - "./stakes.json"

  - label: ":man-surfing: Download ETL rewards data"
    key: "download-etl"
    commands:
      - epoch=$(buildkite-agent meta-data get epoch)
      - mkdir -p ./rewards
      - |
        gcloud storage cp "$gs_bucket_etl/$$epoch/rewards_mev.json" ./rewards/mev.json
        gcloud storage cp "$gs_bucket_etl/$$epoch/rewards_validators_mev.json" ./rewards/validators_mev.json
        gcloud storage cp "$gs_bucket_etl/$$epoch/rewards_inflation.json" ./rewards/inflation.json
        gcloud storage cp "$gs_bucket_etl/$$epoch/rewards_validators_inflation.json" ./rewards/validators_inflation.json
        gcloud storage cp "$gs_bucket_etl/$$epoch/rewards_validators_blocks.json" ./rewards/validators_blocks.json
        gcloud storage cp "$gs_bucket_etl/$$epoch/rewards_priority_fee.json" ./rewards/jito_priority_fee.json
    artifact_paths:
      - './rewards/*.json'

  - label: ":cloud: :arrow_right: :floppy_disk: Download validators and past-validators"
    key: "download-validators"
    commands:
    - epoch=$(buildkite-agent meta-data get epoch)
    - |
      gcloud storage cp "$gs_bucket/$$epoch/validators.json" "."
      gcloud storage cp "$gs_bucket/$$epoch/past-validators.json" "." || echo "Previous validator data not available!"
    artifact_paths:
      - "./validators.json"
      - "./past-validators.json"

  - label: ":cloud: :arrow_right: :floppy_disk: Download DS SAM auction data"
    key: "download-ds-sam"
    commands:
      - epoch=$(buildkite-agent meta-data get epoch)
      # checking auction directory to work with
      - |
        epoch_auction_dirs=$(./scripts/gh_curl.bash "$$ds_sam_auction_github_api_link" |\
          jq -r '.[] | .name' | grep "$${epoch}\.")
        # epoch_auction_dirs list of dirs in format '<epoch>.<slot>', for example '653.12308'
        epoch_auction_dir=$(echo "$$epoch_auction_dirs" | sort -t. -k2 -n -r | head -n 1)
        if [[ -z "$$epoch_auction_dir" ]]; then
          echo "No auction data found for epoch $$epoch, directory listing: $$epoch_auction_dirs"
          exit 1
        fi
      # listing input and output files
      - |
        ds_sam_input_listing_link="$${ds_sam_auction_github_api_link}$${epoch_auction_dir}/inputs/"
        input_dir_files=$(./scripts/gh_curl.bash "$$ds_sam_input_listing_link" |\
          jq -r '.[] | .name')
        ds_sam_output_listing_link="$${ds_sam_auction_github_api_link}$${epoch_auction_dir}/outputs/"
        output_dir_files=$(./scripts/gh_curl.bash "$$ds_sam_output_listing_link" |\
          jq -r '.[] | .name' | grep '.json')
      # downloading files
      - |
        mkdir -p ./inputs
        for file in $$input_dir_files; do
          curl -O --output-dir './inputs' "$${ds_sam_auction_download_link}$${epoch_auction_dir}/inputs/$${file}"
        done
        mkdir -p ./outputs
        for file in $$output_dir_files; do
          curl -O --output-dir './outputs' "$${ds_sam_auction_download_link}$${epoch_auction_dir}/outputs/$${file}"
        done
    artifact_paths:
      - "./inputs/*"
      - "./outputs/*"

  - wait: ~

  # Generate PSR evaluation data
  - label: ":campfire: DS SAM generates PMPE bids data"
    key: "ds-sam-evaluation"
    commands:
      - buildkite-agent artifact download --include-retried-jobs validators.json .
      - buildkite-agent artifact download --include-retried-jobs past-validators.json . || echo "Previous validator data not available"
      - buildkite-agent artifact download --include-retried-jobs inputs/* .
      - buildkite-agent artifact download --include-retried-jobs outputs/* .
      - '[[ ! -f "./outputs/results.json" ]] && echo "results.json not found" && exit 2'
      - 'past_validators_arg=$( [[ -f ./past-validators.json ]] && echo "--snapshot-past-validators-file-path ../past-validators.json" || echo "" )'
      - git clone git@github.com:marinade-finance/ds-sam.git --depth 1
      - |
        cd ds-sam
        git status
        pnpm install
        pnpm -r build
      - |
        pnpm run cli -- analyze-revenues \
          $$past_validators_arg \
          --cache-dir-path "../inputs" \
          --sam-results-fixture-file-path "../outputs/results.json" \
          --snapshot-validators-file-path "../validators.json" \
          --results-file-path "../evaluation.json"
    artifact_paths:
      - "./evaluation.json"

  - wait: ~

  # Generate all settlements with unified CLI
  - label: ":scales: Generate All Settlements"
    key: "generate-settlements"
    env:
      RUST_LOG: info,bid_distribution=debug
    commands:
    - 'buildkite-agent artifact download --include-retried-jobs sam-scores.json .'
    - 'buildkite-agent artifact download --include-retried-jobs stakes.json .'
    - 'buildkite-agent artifact download --include-retried-jobs validators.json .'
    - 'buildkite-agent artifact download --include-retried-jobs evaluation.json .'
    - 'buildkite-agent artifact download --include-retried-jobs target/release/bid-distribution-cli .'
    - 'buildkite-agent artifact download --include-retried-jobs rewards/mev.json .'
    - 'buildkite-agent artifact download --include-retried-jobs rewards/validators_mev.json .'
    - 'buildkite-agent artifact download --include-retried-jobs rewards/inflation.json .'
    - 'buildkite-agent artifact download --include-retried-jobs rewards/validators_inflation.json .'
    - 'buildkite-agent artifact download --include-retried-jobs rewards/validators_blocks.json .'
    - 'buildkite-agent artifact download --include-retried-jobs rewards/jito_priority_fee.json .'
    - 'chmod +x target/release/bid-distribution-cli'
    - |
      ./target/release/bid-distribution-cli \
        --settlement-config settlement-config.yaml \
        --stake-meta-collection ./stakes.json \
        --sam-meta-collection ./sam-scores.json \
        --rewards-dir ./rewards \
        --validator-meta-collection ./validators.json \
        --revenue-expectation-collection ./evaluation.json \
        --output-settlement-collection "./bid-distribution-settlements.json" \
        --output-protected-event-collection "./protected-events.json"
    artifact_paths:
    - "./bid-distribution-settlements.json"
    - "./protected-events.json"

  - wait: ~

  - label: "Generate reports"
    commands:
    - buildkite-agent artifact download --include-retried-jobs bid-distribution-settlements.json .
    - |
      ./scripts/generate-discord-public-report.bash "./bid-distribution-settlements.json" "Bidding" > "./bid-distribution-discord-report.txt"
    artifact_paths:
      - "./bid-distribution-discord-report.txt"

  - wait: ~

  - label: ":floppy_disk: :arrow_right: :cloud: Upload artifacts"
    commands:
    - epoch=$(buildkite-agent meta-data get epoch)
    # Download outputs
    - buildkite-agent artifact download --include-retried-jobs bid-distribution-settlements.json .
    - buildkite-agent artifact download --include-retried-jobs bid-distribution-discord-report.txt .
    - buildkite-agent artifact download --include-retried-jobs protected-events.json .
    - buildkite-agent artifact download --include-retried-jobs evaluation.json .
    # Upload outputs
    - gcloud storage cp "./bid-distribution-settlements.json" "$gs_bucket/$$epoch/"
    - gcloud storage cp "settlement-config.yaml" "$gs_bucket/$$epoch/"
    - gcloud storage cp "./bid-distribution-discord-report.txt" "$gs_bucket/$$epoch/"
    # evaluation.json is pass-through from ds-sam (unchanged), kept under legacy name for downstream consumers
    - gcloud storage cp "./evaluation.json" "$gs_bucket/$$epoch/bid-psr-distribution-evaluation.json"
    # protected-events.json structure is unchanged, kept under legacy name for downstream consumers
    - gcloud storage cp "./protected-events.json" "$gs_bucket/$$epoch/bid-psr-distribution.json"

  - wait: ~

  - label: ":mega: Notification"
    commands:
      - |
        epoch=$(buildkite-agent meta-data get epoch)
        curl ${SLACK_API} -X POST -H 'Content-Type: application/json; charset=utf-8' \
          -H "Authorization: Bearer $$SLACK_BEARER_TOKEN" -d '{
            "channel": "'"$SLACK_FEED"'",
            "attachments": [
              {
                "color": "#8000ff",
                "title": "Settlement files for Validator Bonds (bid + psr) generated ('"$$epoch"').",
                "title_link": "'"$$BUILDKITE_BUILD_URL"'",
                "footer": "<'"$$BUILDKITE_BUILD_URL"'|View in Buildkite>"
              }
            ]
        }'
    if: "build.env('NOTIFY_FEED') == 'true'"

  - wait: ~

  - label: ":gear: Trigger merkle tree scheduler"
    commands:
    - |
      cat <<EOF | buildkite-agent pipeline upload
      steps:
        - trigger: "scheduler-merkle-tree"
          label: ":rocket: Trigger: Merkle Tree Scheduler"
          async: true
          build:
            branch: $$BUILDKITE_BRANCH
            env:
              NOTIFY_FEED: ${NOTIFY_FEED:-false}
              gs_bucket: $gs_bucket
      EOF

  - wait: ~

  - label: ":unlock: Concurrency gate unlock"
    command: echo "End of concurrency gate <--"
    concurrency_group: 'validator-bonds/prepare-bid-distribution'
    concurrency: 1
