agents:
  queue: "snapshots"

steps:
  - label: ":hammer_and_pick: :rust: Build"
    env:
      snapshots_dir: /mnt/storage-1/snapshots
    commands:
    - '. "$HOME/.cargo/env"'
    - 'snapshot_dir=$(ls -td -- $$snapshots_dir/*/ | head -n 1 || exit 1)'
    - 'echo "Snapshot dir: $$snapshot_dir"'
    - 'cargo build --release'
    - |
      ./target/release/snapshot-parser-cli \
        --ledger-path "$$snapshot_dir" \
        --output-validator-meta-collection "$$snapshot_dir/validators.json" \
        --output-stake-meta-collection "$$snapshot_dir/stakes.json"
    - |
      ./target/release/insurance-engie-cli \
        --validator-meta-collection "$$snapshot_dir/validators.json" \
        --stake-meta-collection "$$snapshot_dir/stakes.json" \
        --output-insured-event-collection "$$snapshot_dir/events.json" \
        --output-insurance-claim-collection "$$snapshot_dir/claims.json" \
        --output-merkle-tree-collection "$$snapshot_dir/claims_merkle.json" \
        --whitelist-stake-authority stWirqFCf2Uts1JBL1Jsd3r6VBWhgnpdPxCTe1MFjrq,4bZ6o3eUUNXhKuqjdCnCoPAoLgWiuLYixKaxoa8PpiKk,ex9CfkBZZd6Nv9XdnoDmmB45ymbu4arXVk7g5pWnt3N \
        --low-rewards-threshold-pct 0.9
    - |
      ./target/release/insurance-engine-cli \
        --validator-meta-collection "$$snapshot_dir/validators.json" \
        --stake-meta-collection "$$snapshot_dir/stakes.json" \
        --output-insured-event-collection "$$snapshot_dir/events2.json" \
        --output-insurance-claim-collection "$$snapshot_dir/claims2.json" \
        --output-merkle-tree-collection "$$snapshot_dir/claims_merkle2.json" \
        --low-rewards-threshold-pct 0.9
