agents:
  queue: "snapshots"

steps:
  - label: ":gear: :rust: Setup"
    env:
      snapshots_dir: /mnt/storage-1/snapshots
    commands:
    - '. "$HOME/.cargo/env"'
    - 'snapshot_dir=$(ls -td -- $$snapshots_dir/*/ | head -n 1 || exit 1)'
    - 'echo "Snapshot dir: $$snapshot_dir"'
    - 'previous_epoch=$(<<<"$$snapshot_dir" grep -oP '(?<=snapshot-)\d+' || exit 1)'
    - 'echo "Previous epoch: $$previous_epoch"'
    - 'buildkite-agent meta-data set snapshot_dir "$$snapshot_dir"'
    - 'buildkite-agent meta-data set previous_epoch "$$previous_epoch"'

  - label: ":hammer_and_wrench: :rust: Build"
    commands:
    - '. "$HOME/.cargo/env"'
    - 'cargo build --release'

  - wait: ~

  - label: ":microscope: Parse Snapshot"
    commands:
    - 'snapshot_dir=$(buildkite-agent meta-data get snapshot_dir)'
    - |
      ./target/release/snapshot-parser-cli \
        --ledger-path "$$snapshot_dir" \
        --output-validator-meta-collection "$$snapshot_dir/validators.json" \
        --output-stake-meta-collection "$$snapshot_dir/stakes.json"

  - wait: ~

  - label: ":scales: Evaluate Insured Events"
    commands:
    - 'snapshot_dir=$(buildkite-agent meta-data get snapshot_dir)'
    - |
      ./target/release/insurance-engine-cli \
        --validator-meta-collection "$$snapshot_dir/validators.json" \
        --stake-meta-collection "$$snapshot_dir/stakes.json" \
        --output-insured-event-collection "$$snapshot_dir/events.json" \
        --output-insurance-claim-collection "$$snapshot_dir/claims.json" \
        --output-merkle-tree-collection "$$snapshot_dir/claims_merkle.json" \
        --whitelist-stake-authority stWirqFCf2Uts1JBL1Jsd3r6VBWhgnpdPxCTe1MFjrq,4bZ6o3eUUNXhKuqjdCnCoPAoLgWiuLYixKaxoa8PpiKk,ex9CfkBZZd6Nv9XdnoDmmB45ymbu4arXVk7g5pWnt3N \
        --low-rewards-threshold-pct 0.9
    - |
      ./target/release/insurance-engine-cli \
        --validator-meta-collection "$$snapshot_dir/validators.json" \
        --stake-meta-collection "$$snapshot_dir/stakes.json" \
        --output-insured-event-collection "$$snapshot_dir/events_all.json" \
        --output-insurance-claim-collection "$$snapshot_dir/claims_all.json" \
        --output-merkle-tree-collection "$$snapshot_dir/claims_merkle_all.json" \
        --low-rewards-threshold-pct 0.9

  - block: ":rocket: Continue?"

  - label: ":floppy_disk: :arrow_right: :cloud: Upload artifacts"
    env:
      gs_bucket: gs://marinade-validator-bonds-mainnet
    commands:
    - 'snapshot_dir=$(buildkite-agent meta-data get snapshot_dir)'
    - 'previous_epoch=$(buildkite-agent meta-data get previous_epoch)'
    - 'gcloud storage cp "$$snapshot_dir/validators.json" "$$gs_bucket/$$previous_epoch/"'
    - 'gcloud storage cp "$$snapshot_dir/stakes.json" "$$gs_bucket/$$previous_epoch/"'
    - 'gcloud storage cp "$$snapshot_dir/events.json" "$$gs_bucket/$$previous_epoch/"'
    - 'gcloud storage cp "$$snapshot_dir/claims.json" "$$gs_bucket/$$previous_epoch/"'
    - 'gcloud storage cp "$$snapshot_dir/claims_merkle.json" "$$gs_bucket/$$previous_epoch/"'
    - 'gcloud storage cp "$$snapshot_dir/events_all.json" "$$gs_bucket/$$previous_epoch/"'
    - 'gcloud storage cp "$$snapshot_dir/claims_all.json" "$$gs_bucket/$$previous_epoch/"'
    - 'gcloud storage cp "$$snapshot_dir/claims_merkle_all.json" "$$gs_bucket/$$previous_epoch/"'

  - label: ":zap: Execute on-chain"
    commands:
    - 'echo TODO'
