agents:
  queue: "snapshots"

env:
  gs_bucket: gs://marinade-validator-bonds-mainnet
  gs_bucket_institutional: gs://marinade-institutional-staking-mainnet
  gs_snapshot_bucket: gs://marinade-solana-snapshot-mainnet
  SLACK_API: https://slack.com/api/chat.postMessage
  SLACK_FEED: "feed-institutional-staking"
  CLAIM_TYPE: "institutional-distribution"
  MARINADE_FEE_STAKE_AUTHORITY: BBaQsiRo744NAYaqL3nKRfgeJayoqVicEQsEnLpfsJ6x
  MARINADE_FEE_WITHDRAW_AUTHORITY: BBaQsiRo744NAYaqL3nKRfgeJayoqVicEQsEnLpfsJ6x
  # DAO share of the total Marinade (distributor) fee
  DAO_FEE_SPLIT_SHARE_BPS: 10000
  DAO_FEE_STAKE_AUTHORITY: mDAo14E6YJfEHcVZLcc235RVjviypmKMhftq7jeiLJz
  DAO_FEE_WITHDRAW_AUTHORITY: mDAo14E6YJfEHcVZLcc235RVjviypmKMhftq7jeiLJz
  VALIDATOR_BONDS_CONFIG: VbinSTyUEC8JXtzFteC4ruKSfs6dkQUUcY6wB1oJyjE
  INSTITUTIONAL_URL: 'https://institutional-staking.marinade.finance/v1/validators'

steps:
  - label: ":hammer_and_wrench: :rust: Build"
    commands:
    - '. "$HOME/.cargo/env"'
    - 'cargo build --release --bin institutional-distribution-cli'
    artifact_paths:
      - target/release/institutional-distribution-cli

  - input: "What is the epoch to generate settlements for?"
    fields:
      - text: "Epoch"
        key: "epoch"
        format: "[0-9]+"
    if: "build.env('EPOCH') == null"
    blocked_state: running

  - wait: ~

  - label: ":closed_lock_with_key: Concurrency gate lock"
    command: echo "--> Start of concurrency gate"
    concurrency_group: 'validator-bonds/prepare-institutional-distribution'
    concurrency: 1

  - wait: ~

  - label: ":black_nib: Env variables setup: Prepare Institutional Distribution"
    key: "setup-env-prepare-institutional"
    commands:
    - |
      epoch=${EPOCH:-$(buildkite-agent meta-data get epoch)}
      buildkite-agent meta-data set --redacted-vars='' epoch "$$epoch"
      echo "Epoch: '$$epoch'"

  - label: ":memo: Annotate retry parameters"
    depends_on: "setup-env-prepare-institutional"
    allow_dependency_failure: true
    commands:
      - epoch=${EPOCH:-$(buildkite-agent meta-data get epoch)}
      - |
        cat <<- EOF | buildkite-agent annotate --priority 6 --style info --context "general-info"
        ### Retry environment variables
        If you need to retry the build, use the following parameters:

        \`\`\`
        EPOCH=$$epoch
        CLAIM_TYPE=$CLAIM_TYPE
        INSTITUTIONAL_URL=$INSTITUTIONAL_URL
        MARINADE_FEE_STAKE_AUTHORITY=$MARINADE_FEE_STAKE_AUTHORITY
        MARINADE_FEE_WITHDRAW_AUTHORITY=$MARINADE_FEE_WITHDRAW_AUTHORITY
        DAO_FEE_SPLIT_SHARE_BPS=$DAO_FEE_SPLIT_SHARE_BPS
        DAO_FEE_STAKE_AUTHORITY=$DAO_FEE_STAKE_AUTHORITY
        DAO_FEE_WITHDRAW_AUTHORITY=$DAO_FEE_WITHDRAW_AUTHORITY
        SLACK_FEED=$SLACK_FEED
        NOTIFY_FEED=${NOTIFY_FEED:-false}
        \`\`\`
        EOF

  - wait: ~

  - label: ":floppy_disk: :arrow_left: :cloud: Downloading Input JSON data"
    key: "download-json"
    commands:
    - epoch=$(buildkite-agent meta-data get epoch)
    - gcloud storage cp "$gs_bucket_institutional/$$epoch/institutional-payouts.json" .
    - gcloud storage cp "$gs_snapshot_bucket/$$epoch/stakes.json" "."
    artifact_paths:
      - "./institutional-payouts.json"
      - "./stakes.json"

  - wait: ~

  - label: ":scales: Prepare Validator Bonds Merkle Tree"
    env:
      RUST_BACKTRACE: 1
    commands:
    - buildkite-agent artifact download --include-retried-jobs target/release/institutional-distribution-cli .
    - chmod +x target/release/institutional-distribution-cli
    - buildkite-agent artifact download --include-retried-jobs institutional-payouts.json .
    - buildkite-agent artifact download --include-retried-jobs stakes.json .
    - |
      ./target/release/institutional-distribution-cli \
        --institutional-payouts ./institutional-payouts.json \
        --stake-meta-collection ./stakes.json \
        --marinade-fee-stake-authority ${MARINADE_FEE_STAKE_AUTHORITY} \
        --marinade-fee-withdraw-authority ${MARINADE_FEE_WITHDRAW_AUTHORITY} \
        --dao-fee-split-share-bps ${DAO_FEE_SPLIT_SHARE_BPS} \
        --dao-fee-stake-authority ${DAO_FEE_STAKE_AUTHORITY} \
        --dao-fee-withdraw-authority ${DAO_FEE_WITHDRAW_AUTHORITY} \
        --validator-bonds-config ${VALIDATOR_BONDS_CONFIG} \
        --output-settlement-collection "./${CLAIM_TYPE}-settlements.json" \
        --output-merkle-tree-collection "./${CLAIM_TYPE}-settlement-merkle-trees.json" \
        --output-config "./${CLAIM_TYPE}-config.json"
    artifact_paths:
    - "./${CLAIM_TYPE}*.json"

  - wait: ~

  - label: "📓 Generating report"
    commands:
    - buildkite-agent artifact download --include-retried-jobs ${CLAIM_TYPE}-settlements.json .
    - |
      ./scripts/generate-discord-public-report.bash "./${CLAIM_TYPE}-settlements.json" "Institutional" > "./discord-public-report.txt"
    artifact_paths:
      - "./discord-public-report.txt"

  - label: "📓 Details from payouts data"
    commands:
    - buildkite-agent artifact download --include-retried-jobs institutional-payouts.json .
    - |
      jq '[.validators[].stakedAmounts | {
        institutionalEffective,
        institutionalActivating,
        institutionalDeactivating
      }] | {
        institutionalEffective: (map(.institutionalEffective | tonumber) | add / 1e9),
        institutionalActivating: (map(.institutionalActivating | tonumber) | add / 1e9),
        institutionalDeactivating: (map(.institutionalDeactivating | tonumber) | add / 1e9)
      }' ./institutional-payouts.json | jq -r 'to_entries | (.[] | " \(.key): \(.value)")' > './institutional-payouts-summary.txt'
    artifact_paths:
      - "./institutional-payouts-summary.txt"

  - wait: ~

  - label: ":floppy_disk: :arrow_right: :cloud: Upload artifacts Prepare Bid Distribution"
    commands:
      - epoch=$(buildkite-agent meta-data get epoch)
      - buildkite-agent artifact download --include-retried-jobs ${CLAIM_TYPE}-settlements.json .
      - buildkite-agent artifact download --include-retried-jobs ${CLAIM_TYPE}-settlement-merkle-trees.json .
      - buildkite-agent artifact download --include-retried-jobs ${CLAIM_TYPE}-config.json .
      - buildkite-agent artifact download --include-retried-jobs discord-public-report.txt .
      - gcloud storage cp "./${CLAIM_TYPE}-settlements.json" "$gs_bucket/$$epoch/"
      - gcloud storage cp "./${CLAIM_TYPE}-settlement-merkle-trees.json" "$gs_bucket/$$epoch/"
      - gcloud storage cp "./${CLAIM_TYPE}-config.json" "$gs_bucket/$$epoch/"
      - gcloud storage cp "./discord-public-report.txt" "$gs_bucket/$$epoch/${CLAIM_TYPE}-discord-public-report.txt"

  - label: ":mega: Notification"
    commands:
    - buildkite-agent artifact download --include-retried-jobs institutional-payouts-summary.txt .
    - institutional_payouts_summary=$(cat ./institutional-payouts-summary.txt)
    - |
      epoch=$(buildkite-agent meta-data get epoch)
      curl ${SLACK_API} -X POST -H 'Content-Type: application/json; charset=utf-8' \
        -H "Authorization: Bearer $$SLACK_BEARER_TOKEN" -d '{
          "channel": "'"$SLACK_FEED"'",
          "attachments": [
            {
              "color": "#8000ff",
              "title": "Claims for Validator Bonds ('"${CLAIM_TYPE}"') generated ('"$$epoch"').",
              "title_link": "'"$$BUILDKITE_BUILD_URL/#$${BUILDKITE_JOB_ID}"'",
              "text": "'"$$institutional_payouts_summary"'",
              "footer": "<'"$$BUILDKITE_BUILD_URL/#$${BUILDKITE_JOB_ID}"'|View in Buildkite>"
            }
          ]
      }'
    if: "build.env('NOTIFY_FEED') == 'true'"

  - wait: ~

  - label: ":gear: Setup init-settlements trigger"
    commands:
    - epoch=$(buildkite-agent meta-data get epoch)
    - |
      cat <<EOF | buildkite-agent pipeline upload
      steps:
        - trigger: "init-settlements"
          label: ":rocket: Trigger: Init settlements ($$epoch)/($CLAIM_TYPE)"
          async: true
          build:
            branch: $$BUILDKITE_BRANCH
            env:
              EPOCH: $$epoch
              CLAIM_TYPE: $CLAIM_TYPE
              NOTIFY_FEED: $NOTIFY_FEED
              SLACK_FEED: $SLACK_FEED
              NOTIFY_DISCORD_FEED: false
              INSTITUTIONAL_URL: $INSTITUTIONAL_URL
              gs_bucket: $gs_bucket
      EOF

  - wait: ~

  - label: ":unlock: Concurrency gate unlock"
    command: echo "End of concurrency gate <--"
    concurrency_group: 'validator-bonds/prepare-institutional-distribution'
    concurrency: 1
