agents:
  queue: "snapshots"

steps:
  - label: ":recycle: Pruning old snapshot directories"
    env:
      snapshots_dir: /mnt/storage-1/snapshots
    commands:
    - 'ls -td -- /mnt/storage-1/snapshots/*/ | awk "NR>1" | tee /dev/stderr | xargs rm -rf'

  - label: ":calendar: Schedule"
    commands:
    - |
      max_processed_epoch=$(gcloud storage ls "gs://marinade-validator-bonds-mainnet" | awk -F / '{print $4}' | sort -nr | head -n 1 || exit 1)
      max_available_epoch=$(gcloud storage ls "gs://jito-mainnet/**/*.tar.zst" | awk -F / '{print $4}' | sort -nr | head -n 1)
      echo max_processed_epoch: $$max_processed_epoch
      echo max_available_epoch: $$max_available_epoch
      (( $max_processed_epoch < $max_available_epoch )) && buildkite-agent env set "EPOCH=$$max_available_epoch"

  - wait: ~

  - trigger: "fetch-solana-snapshot"
    label: ":rocket: Trigger: Fetch Solana snapshot"
    async: false
    build:
      env:
        EPOCH: ${EPOCH}
    if: ${EPOCH}


  # - label: ":recycle: Pruning old snapshot directories"
  #   env:
  #     snapshots_dir: /mnt/storage-1/snapshots
  #   commands:
  #   - 'ls -td -- /mnt/storage-1/snapshots/*/ | awk "NR>1" | tee /dev/stderr | xargs rm -r'
