agents:
  queue: "snapshots"

env:
  gs_bucket: gs://marinade-validator-bonds-mainnet
  gs_bucket_snapshots: gs://marinade-solana-snapshot-mainnet
  gs_bucket_etl: gs://marinade-stakes-etl-mainnet

steps:
  - label: ":closed_lock_with_key: Concurrency gate lock"
    key: concurrency-lock
    command: echo "--> Start of concurrency gate"
    concurrency_group: 'validator-bonds/scheduler-bidding'
    concurrency: 1

  - wait: ~

  - label: ':shellcheck: Load available epochs'
    commands:
      - |
        max_processed_epoch=$(gcloud storage ls "${gs_bucket}/**/bid-psr-distribution.json" | awk -F / '{print $$4}' | sort -nr | head -n 1 || exit 1)  || exit 1
        max_processed_epoch="$${max_processed_epoch%%[^0-9]*}"
        max_available_epoch=$(gcloud storage ls "${gs_bucket_snapshots}/**/stakes.json" | awk -F / '{print $$4}' | sort -nr | head -n 1 || exit 2) || exit 2
        max_available_etl_epoch=$(gcloud storage ls "$gs_bucket_etl" | awk -F / '{print $$4}' | sort -nr | head -n 1) || exit 22
        echo "Bidding:: > max_processed_epoch: $$max_processed_epoch, max_available_epoch: $$max_available_epoch, max_available_etl_epoch: $$max_available_etl_epoch"
      - |
        buildkite-agent meta-data set max_processed_epoch "$$max_processed_epoch"
        buildkite-agent meta-data set max_available_epoch "$$max_available_epoch"
        buildkite-agent meta-data set max_available_etl_epoch "$$max_available_etl_epoch"

  - wait: ~

  - label: ":calendar: Schedule"
    commands:
      - max_processed_epoch=$(buildkite-agent meta-data get max_processed_epoch)
      - max_available_epoch=$(buildkite-agent meta-data get max_available_epoch)
      - max_available_etl_epoch=$(buildkite-agent meta-data get max_available_etl_epoch)
      - |
        if (( $$max_processed_epoch < $$max_available_epoch )) && (( $$max_available_etl_epoch >= $$max_available_epoch )); then
          epoch=$${max_available_epoch}
          gcloud storage cp "$gs_bucket_snapshots/$$epoch/past-validators.json" "$gs_bucket/$$epoch/"
          gcloud storage cp "$gs_bucket_snapshots/$$epoch/validators.json" "$gs_bucket/$$epoch/"
          gcloud storage cp "$gs_bucket_snapshots/$$epoch/stakes.json" "$gs_bucket/$$epoch/"
        
          cat <<EOF | buildkite-agent pipeline upload
            steps:
              - trigger: "prepare-bid-psr-distribution"
                label: ":rocket: Trigger: Prepare Bid PSR Distribution ($$epoch)"
                async: false
                build:
                  branch: $$BUILDKITE_BRANCH
                  env:
                    EPOCH: $$epoch
                    NOTIFY_FEED: $NOTIFY_FEED
                    gs_bucket: $gs_bucket
        EOF
  
          cat <<EOF | buildkite-agent pipeline upload
            steps:
              - trigger: "prepare-bid-distribution"
                label: ":rocket: Trigger: Prepare Bid Distribution ($$epoch)"
                async: false
                build:
                  branch: $$BUILDKITE_BRANCH
                  env:
                    EPOCH: $$epoch
                    NOTIFY_FEED: $NOTIFY_FEED
                    gs_bucket: $gs_bucket
        EOF

        fi
  
        echo Scheduling complete

  - wait: ~

  - label: ":unlock: Concurrency gate unlock"
    command: echo "End of concurrency gate <--"
    concurrency_group: 'validator-bonds/scheduler-bidding'
    concurrency: 1
