agents:
  queue: "snapshots"

env:
  gs_bucket: gs://marinade-validator-bonds-mainnet
  SETTLEMENTS_FILES: "bid-distribution-settlements.json" # comma separated
  VALIDATOR_BONDS_CONFIG: vbMaRfmTCg92HWGzmd53APkMNpPnGVGZTUHwUJQkXAU

steps:
  - label: ":closed_lock_with_key: Concurrency gate lock"
    key: concurrency-lock
    command: echo "--> Start of concurrency gate"
    concurrency_group: 'validator-bonds/scheduler-merkle-tree'
    concurrency: 1

  - wait: ~

  - label: ":shellcheck: Load available epochs"
    commands:
      - |
        set -o pipefail
        max_processed_epoch=$(gcloud storage ls "${gs_bucket}/**/unified-merkle-trees.json" | awk -F / '{print $$4}' | sort -nr | head -n 1 || echo "0")
        max_processed_epoch="$${max_processed_epoch%%[^0-9]*}"
        max_processed_epoch=$${max_processed_epoch:-0}

        max_available_epoch=-1
        echo "Working with settlements files: $SETTLEMENTS_FILES"
        IFS=',' read -ra settlement_files_entries <<< "$SETTLEMENTS_FILES"
        for entry in "$${settlement_files_entries[@]}"; do
          entry_max_available_epoch=$(gcloud storage ls "${gs_bucket}/**/$$entry" | awk -F / '{print $$4}' | sort -nr | head -n 1 || exit 23) || exit 23
          entry_max_available_epoch="$${entry_max_available_epoch%%[^0-9]*}"
          entry_max_available_epoch=$${entry_max_available_epoch:-0}
          if (( $$max_available_epoch == -1 )) || (( $$entry_max_available_epoch < $$max_available_epoch )); then
            max_available_epoch=$$entry_max_available_epoch
          fi
          echo "File '$$entry' has max available epoch: $$entry_max_available_epoch (current min of max epochs: $$max_available_epoch)"
        done
      - |
        echo "> max_processed_epoch: $$max_processed_epoch, max_available_epoch: $$max_available_epoch"
        buildkite-agent meta-data set max_processed_epoch "$$max_processed_epoch"
        buildkite-agent meta-data set max_available_epoch "$$max_available_epoch"

  - wait: ~

  - label: ":calendar: Schedule Unified Merkle Tree Generation"
    commands:
      - max_processed_epoch=$(buildkite-agent meta-data get max_processed_epoch)
      - max_available_epoch=$(buildkite-agent meta-data get max_available_epoch)
      - |
        if (( $$max_available_epoch > 0 )) && (( $$max_processed_epoch < $$max_available_epoch )); then
          epoch=$${max_available_epoch}
          cat <<EOF | buildkite-agent pipeline upload
            steps:
              - trigger: "generate-merkle-trees"
                label: ":rocket: Trigger: Generate Unified Merkle Trees ($$max_available_epoch)"
                async: false
                build:
                  branch: $$BUILDKITE_BRANCH
                  env:
                    EPOCH: $$max_available_epoch
                    NOTIFY_FEED: $NOTIFY_FEED
                    gs_bucket: $gs_bucket
                    VALIDATOR_BONDS_CONFIG: $VALIDATOR_BONDS_CONFIG
                    SETTLEMENTS_FILES: $SETTLEMENTS_FILES
        EOF
          echo "Scheduled unified merkle tree generation for epoch $$max_available_epoch"
        else
          echo "No new epochs to process (max_processed: $$max_processed_epoch, max_available: $$max_available_epoch)"
        fi

  - wait: ~

  - label: ":unlock: Concurrency gate unlock"
    command: echo "End of concurrency gate <--"
    concurrency_group: 'validator-bonds/scheduler-merkle-tree'
    concurrency: 1
