agents:
  queue: "snapshots"

steps:
  - command: echo "--> Start of concurrency gate"
    concurrency_group: 'validator-bonds/scheduler'
    concurrency: 1

  - wait: ~

  - label: ":calendar: Schedule"
    concurrency_group: 'validator-bonds/copy-parsed'
    concurrency: 1
    commands:
    - |
      max_processed_epoch=$(gcloud storage ls "gs://marinade-validator-bonds-mainnet" | awk -F / '{print $$4}' | sort -nr | head -n 1 || exit 1)
      max_processed_epoch="$${max_processed_epoch%%[^0-9]*}"
      max_available_epoch=$(gcloud storage ls "gs://marinade-solana-snapshot-mainnet/**/stakes.json" | awk -F / '{print $$4}' | sort -nr | head -n 1 || exit 1)
      echo max_processed_epoch: $$max_processed_epoch
      echo max_available_epoch: $$max_available_epoch
      (( $$max_processed_epoch < $$max_available_epoch )) && cat <<EOF | buildkite-agent pipeline upload
      steps:
        - trigger: "copy-parsed-snapshot"
          label: ":rocket: Trigger: Fetch parsed Solana snapshot ($$max_available_epoch)"
          async: false
          build:
            env:
              EPOCH: $$max_available_epoch
      EOF

      echo Scheduling complete

  - wait: ~

  - command: echo "End of concurrency gate <--"
    concurrency_group: 'validator-bonds/scheduler'
    concurrency: 1
