agents:
  queue: "snapshots"

steps:
  - command: echo "--> Start of concurrency gate"
    concurrency_group: 'validator-bonds/scheduler'
    concurrency: 1

  - wait: ~

  - label: ":recycle: Pruning old snapshot directories"
    concurrency_group: 'validator-bonds/fetch'
    concurrency: 1
    env:
      snapshots_dir: /mnt/storage-1/snapshots
    commands:
    - 'ls -td -- /mnt/storage-1/snapshots/*/ | awk "NR>1" | tee /dev/stderr | xargs rm -rf'

  - label: ":calendar: Schedule"
    concurrency_group: 'validator-bonds/fetch'
    concurrency: 1
    commands:
    - |
      max_processed_epoch=$(gcloud storage ls "gs://marinade-validator-bonds-mainnet" | awk -F / '{print $$4}' | sort -nr | head -n 1 || exit 1)
      max_available_epoch=$(gcloud storage ls "gs://jito-mainnet/**/*.tar.zst" | awk -F / '{print $$4}' | sort -nr | head -n 1)
      echo max_processed_epoch: $$max_processed_epoch
      echo max_available_epoch: $$max_available_epoch
      (( $$max_processed_epoch < $$max_available_epoch )) && cat <<EOF | buildkite-agent pipeline upload
      steps:
        - trigger: "fetch-and-parse-snapshot"
          label: ":rocket: Trigger: Fetch Solana snapshot ($$max_available_epoch)"
          async: false
          build:
            env:
              EPOCH: $$max_available_epoch
      EOF

      echo Scheduling complete

  - wait: ~

  - command: echo "End of concurrency gate <--"
    concurrency_group: 'validator-bonds/scheduler'
    concurrency: 1
