agents:
  queue: "snapshots"

env:
  gs_bucket: gs://marinade-validator-bonds-mainnet
  SLACK_API: https://slack.com/api/chat.postMessage
  command_name: 'verify-settlement'

# This pipeline is responsible for verifying the settlements of the past epochs
# It will download the past settlements from gcloud and checks their existence on-chain
# If unknown Settlement is found it may mean a mallicious actor stolen operator keypair and tries to withdraw funds.
# If that happens we need to act fast as the Validator Bonds emergency or operator authority may cancel any Settlement at any time.
# The Settlement cannot be claimed immediately, but it takes several slots (~ 1/2 of epoch) to get it permitted for claiming.
# See
#  * Config.slots_to_start_settlement_claiming
#  * programs/validator-bonds/src/instructions/settlement/claim_settlement.rs
#  * programs/validator-bonds/src/instructions/settlement/cancel_settlement.rs

steps:
  - label: ":closed_lock_with_key: Concurrency gate lock"
    command: echo "--> Start of concurrency gate"
    concurrency_group: 'validator-bonds/verify-settlements-${CLAIM_TYPE}'
    concurrency: 1

  - input: "What is the Bonds Config type to verify?"
    fields:
      - select: "Claim type"
        key: "claim_type"
        options:
          - label: "Unified Settlements"
            value: "unified"
          - label: "Institutional Settlements"
            value: "institutional"
    if: "build.env('CLAIM_TYPE') == null"
    blocked_state: running

  - wait: ~

  - label: ":hammer_and_wrench: :rust: Build"
    commands:
    - '. "$HOME/.cargo/env"'
    - 'cargo build --release --bin list-settlement'
    - 'cargo build --release --bin verify-settlement'
    artifact_paths:
      - target/release/verify-settlement
      - target/release/list-settlement

  - label: ":black_nib: Env variables setup: Verify Settlements"
    key: setup-env-verify
    commands:
    - |
      claim_type=${CLAIM_TYPE:-$(buildkite-agent meta-data get claim_type)}
      buildkite-agent meta-data set --redacted-vars='' claim_type "$$claim_type"
      config_pubkey=$(./scripts/bonds-config-pubkey.sh "$$claim_type")
      buildkite-agent meta-data set --redacted-vars='' config_pubkey "$$config_pubkey"
    - |
      slack_feed=${SLACK_FEED:-$(./scripts/bonds-slack-feed.sh "$$claim_type")}
      buildkite-agent meta-data set --redacted-vars='' slack_feed "$$slack_feed"
    - |
      echo "Claim Type: '$$claim_type'/'$$config_pubkey', Slack Feed: '$$slack_feed'"
    - |
      buildkite-agent meta-data set --redacted-vars='' non_funded_threshold "${NON_FUNDED_THRESHOLD:-7}"
      buildkite-agent meta-data set --redacted-vars='' non_existing_to_report "${NON_EXISTING_TO_REPORT:-0}"

  - label: ":memo: Annotate retry parameters"
    depends_on: setup-env-verify
    allow_dependency_failure: true
    commands:
      - claim_type=$(buildkite-agent meta-data get claim_type)
      - slack_feed=$(buildkite-agent meta-data get slack_feed)
      - non_funded_threshold=$(buildkite-agent meta-data get non_funded_threshold)
      - non_existing_to_report=$(buildkite-agent meta-data get non_existing_to_report)
      - |
        cat <<- EOF | buildkite-agent annotate --priority 6 --style info --context "general-info"
        ### Retry environment variables
        If you need to retry the build, use the following parameters:

        \`\`\`
        CLAIM_TYPE=$$claim_type
        SLACK_FEED=$$slack_feed
        NOTIFY_FEED=${NOTIFY_FEED:-false}
        NON_FUNDED_THRESHOLD=$$non_funded_threshold
        NON_EXISTING_TO_REPORT=$$non_existing_to_report
        \`\`\`
        EOF

  - wait: ~

  - label: " Loading past settlements json files"
    env:
      past_epochs_to_load: 5
    commands:
    - |
      current_epoch=$(curl --silent "$$RPC_URL" -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"getEpochInfo"}' | jq '.result.epoch')
      start_epoch=$((current_epoch - past_epochs_to_load))
    - |
      claim_type=$(buildkite-agent meta-data get claim_type)
      claim_type_prefix="$${claim_type%%-*}"
    - 'mkdir ./merkle-trees/'
    - |
      echo "Sequence printing: $(seq $$start_epoch $$current_epoch)"
      for epoch in $(seq $$start_epoch $$current_epoch); do
        for merkle_tree_file in $(gcloud storage ls "$gs_bucket/$$epoch/$${claim_type_prefix}*merkle-trees.json"); do
          base_name=$(basename "$$merkle_tree_file")
          gcloud storage cp "$$merkle_tree_file" "./merkle-trees/$${epoch}_$${base_name}"
        done
      done
    artifact_paths:
      - "./merkle-trees/*"

  - wait: ~

  - label: ":campfire: List past settlements"
    env:
      RPC_URL: "$$RPC_URL"
      RUST_LOG: info,solana_transaction_builder_executor=debug,solana_transaction_builder=debug,solana_transaction_executor=debug,list_settlement=debug
    commands:
    - . "$HOME/.cargo/env"
    - buildkite-agent artifact download --include-retried-jobs "merkle-trees/*" .
    - buildkite-agent artifact download --include-retried-jobs target/release/list-settlement .
    - chmod +x target/release/list-settlement
    - |
      ./target/release/list-settlement \
        -m ./merkle-trees/* \
        --config $(buildkite-agent meta-data get config_pubkey) \
        --out ./listed-settlements.json
    artifact_paths:
      - "./listed-settlements.json"

  - wait: ~

  - label: ":campfire::arrow_right: Verify settlements"
    key: "verify-settlement"
    env:
      RPC_URL: "$$RPC_URL"
      RUST_LOG: info,solana_transaction_builder_executor=debug,solana_transaction_builder=debug,solana_transaction_executor=debug,verify_settlement=debug
    commands:
    - . "$HOME/.cargo/env"
    - buildkite-agent artifact download --include-retried-jobs target/release/verify-settlement .
    - buildkite-agent artifact download --include-retried-jobs listed-settlements.json .
    - chmod +x target/release/verify-settlement
    - source ./scripts/execute-handlers.sh
    - |
      handle_command_execution "$$command_name" \
      ./target/release/verify-settlement \
        --config $(buildkite-agent meta-data get config_pubkey) \
        --listed-settlements ./listed-settlements.json
    artifact_paths:
      - "./report.*.json"
    retry:
      automatic:
        - exit_status: 100
          limit: 3

  - label: ":memo: Notification setup: Verify Settlements"
    commands:
     - |
       buildkite-agent artifact download --include-retried-jobs "report.$$command_name.*.json" . || \
         echo '{"command":"'$$command_name'","status":{"success":false,"error_count":1},"summary":"No report found"}' > "./report.$$command_name.0.json"
     - latest_report=$$(ls -v "report.$$command_name."[0-9]*.json 2>/dev/null | tail -n 1)
     - cp "$$latest_report" "./cumulative-report.json"
     - cp "$$latest_report" "./verify-report.json"
     - attempts_count=$$(ls -1 "report.$$command_name."[0-9]*.json 2>/dev/null | wc -l)
     - buildkite-agent meta-data set --redacted-vars="" attempts_count "$$attempts_count"
    artifact_paths:
      - "./cumulative-report.json"
      - "./verify-report.json"
    key: 'notification'
    depends_on: "verify-settlement"
    allow_dependency_failure: true

  - label: ":printer: Annotate Report"
    commands:
      - source ./scripts/execute-handlers.sh
      - annotate_execution_report "$$command_name"
    key: 'annotate-report-verify'
    depends_on: "verify-settlement"
    allow_dependency_failure: true

  - wait: ~

  - label: ":mega: Notification settlements verification"
    commands:
    - buildkite-agent artifact download --include-retried-jobs verify-report.json .
    - source ./scripts/execute-handlers.sh
    - check_command_execution_status "$$command_name" || true
    - slack_feed=$(buildkite-agent meta-data get slack_feed)
    - claim_type=$(buildkite-agent meta-data get claim_type)
    - non_funded_threshold=$(buildkite-agent meta-data get non_funded_threshold)
    - non_existing_to_report=$(buildkite-agent meta-data get non_existing_to_report)
    - chmod +x ./scripts/parse-verify-alerts.sh
    - source ./scripts/parse-verify-alerts.sh -f ./verify-report.json -n "$$non_funded_threshold" -e "$$non_existing_to_report" || alert_exit_code=$?
    - |
      if [ "$${alert_exit_code:-0}" -ne 0 ]; then
        curl $${SLACK_API} -X POST -H 'Content-type: application/json; charset=utf-8' \
            -H "Authorization: Bearer $$SLACK_BEARER_TOKEN" -d '{
              "channel": "'"$$slack_feed"'",
              "text": "🚨 Settlement Verification Alerts",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🚨 '"$${claim_type^^}"' Settlement Verification Alerts ('"$$total_alerts"' total)"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Summary:* '"$$unknown_count"' unknown | '"$$non_verified_count"' non-verified epochs | '"$$non_existing_count"' non-existing (threshold: '"$$non_existing_to_report"') | '"$$non_funded_count"' non-funded (threshold: '"$$non_funded_threshold"')"
                  }
                },
                {
                  "type": "divider"
                },'"$$alert_sections"',
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "<'"$${BUILDKITE_BUILD_URL}/#$${BUILDKITE_JOB_ID}"'|View in Buildkite>"
                    }
                  ]
                }
              ]
          }'
        echo
        echo "Alerts successfully posted to Slack: $$slack_feed. Marking the build as failed as a result of alerts."
        exit 42
      fi
    depends_on: "notification"
    allow_dependency_failure: true
    if: "build.env('NOTIFY_FEED') == 'true'"

  - wait: ~

  - label: ":unlock: Concurrency gate unlock"
    command: echo "End of concurrency gate <--"
    concurrency_group: 'validator-bonds/verify-settlements-${CLAIM_TYPE}'
    concurrency: 1
