/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js'

export type Bumps = {
  pda: number
  stakerAuthority: number
  settlementClaims: number
}

export type BumpsArgs = Bumps

export function getBumpsEncoder(): Encoder<BumpsArgs> {
  return getStructEncoder([
    ['pda', getU8Encoder()],
    ['stakerAuthority', getU8Encoder()],
    ['settlementClaims', getU8Encoder()],
  ])
}

export function getBumpsDecoder(): Decoder<Bumps> {
  return getStructDecoder([
    ['pda', getU8Decoder()],
    ['stakerAuthority', getU8Decoder()],
    ['settlementClaims', getU8Decoder()],
  ])
}

export function getBumpsCodec(): Codec<BumpsArgs, Bumps> {
  return combineCodec(getBumpsEncoder(), getBumpsDecoder())
}
