/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type Bumps = {
  pda: number;
  stakerAuthority: number;
  settlementClaims: number;
};

export type BumpsArgs = Bumps;

export function getBumpsEncoder(): FixedSizeEncoder<BumpsArgs> {
  return getStructEncoder([
    ['pda', getU8Encoder()],
    ['stakerAuthority', getU8Encoder()],
    ['settlementClaims', getU8Encoder()],
  ]);
}

export function getBumpsDecoder(): FixedSizeDecoder<Bumps> {
  return getStructDecoder([
    ['pda', getU8Decoder()],
    ['stakerAuthority', getU8Decoder()],
    ['settlementClaims', getU8Decoder()],
  ]);
}

export function getBumpsCodec(): FixedSizeCodec<BumpsArgs, Bumps> {
  return combineCodec(getBumpsEncoder(), getBumpsDecoder());
}
