/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Option,
  type OptionOrNullable,
  type ReadonlyUint8Array,
} from '@solana/kit';

export type CancelSettlementEvent = {
  bond: Address;
  settlement: Address;
  merkleRoot: ReadonlyUint8Array;
  maxTotalClaim: bigint;
  maxMerkleNodes: bigint;
  lamportsFunded: bigint;
  lamportsClaimed: bigint;
  merkleNodesClaimed: bigint;
  splitRentCollector: Option<Address>;
  splitRentRefund: Option<Address>;
  rentCollector: Address;
  authority: Address;
};

export type CancelSettlementEventArgs = {
  bond: Address;
  settlement: Address;
  merkleRoot: ReadonlyUint8Array;
  maxTotalClaim: number | bigint;
  maxMerkleNodes: number | bigint;
  lamportsFunded: number | bigint;
  lamportsClaimed: number | bigint;
  merkleNodesClaimed: number | bigint;
  splitRentCollector: OptionOrNullable<Address>;
  splitRentRefund: OptionOrNullable<Address>;
  rentCollector: Address;
  authority: Address;
};

export function getCancelSettlementEventEncoder(): Encoder<CancelSettlementEventArgs> {
  return getStructEncoder([
    ['bond', getAddressEncoder()],
    ['settlement', getAddressEncoder()],
    ['merkleRoot', fixEncoderSize(getBytesEncoder(), 32)],
    ['maxTotalClaim', getU64Encoder()],
    ['maxMerkleNodes', getU64Encoder()],
    ['lamportsFunded', getU64Encoder()],
    ['lamportsClaimed', getU64Encoder()],
    ['merkleNodesClaimed', getU64Encoder()],
    ['splitRentCollector', getOptionEncoder(getAddressEncoder())],
    ['splitRentRefund', getOptionEncoder(getAddressEncoder())],
    ['rentCollector', getAddressEncoder()],
    ['authority', getAddressEncoder()],
  ]);
}

export function getCancelSettlementEventDecoder(): Decoder<CancelSettlementEvent> {
  return getStructDecoder([
    ['bond', getAddressDecoder()],
    ['settlement', getAddressDecoder()],
    ['merkleRoot', fixDecoderSize(getBytesDecoder(), 32)],
    ['maxTotalClaim', getU64Decoder()],
    ['maxMerkleNodes', getU64Decoder()],
    ['lamportsFunded', getU64Decoder()],
    ['lamportsClaimed', getU64Decoder()],
    ['merkleNodesClaimed', getU64Decoder()],
    ['splitRentCollector', getOptionDecoder(getAddressDecoder())],
    ['splitRentRefund', getOptionDecoder(getAddressDecoder())],
    ['rentCollector', getAddressDecoder()],
    ['authority', getAddressDecoder()],
  ]);
}

export function getCancelSettlementEventCodec(): Codec<
  CancelSettlementEventArgs,
  CancelSettlementEvent
> {
  return combineCodec(
    getCancelSettlementEventEncoder(),
    getCancelSettlementEventDecoder()
  );
}
