/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Option,
  type OptionOrNullable,
} from '@solana/kit'
import {
  getSplitStakeDataDecoder,
  getSplitStakeDataEncoder,
  getU64ValueChangeDecoder,
  getU64ValueChangeEncoder,
  type SplitStakeData,
  type SplitStakeDataArgs,
  type U64ValueChange,
  type U64ValueChangeArgs,
} from '.'

export type ClaimWithdrawRequestEvent = {
  withdrawRequest: Address
  bond: Address
  voteAccount: Address
  stakeAccount: Address
  splitStake: Option<SplitStakeData>
  newStakeAccountOwner: Address
  withdrawingAmount: bigint
  withdrawnAmount: U64ValueChange
}

export type ClaimWithdrawRequestEventArgs = {
  withdrawRequest: Address
  bond: Address
  voteAccount: Address
  stakeAccount: Address
  splitStake: OptionOrNullable<SplitStakeDataArgs>
  newStakeAccountOwner: Address
  withdrawingAmount: number | bigint
  withdrawnAmount: U64ValueChangeArgs
}

export function getClaimWithdrawRequestEventEncoder(): Encoder<ClaimWithdrawRequestEventArgs> {
  return getStructEncoder([
    ['withdrawRequest', getAddressEncoder()],
    ['bond', getAddressEncoder()],
    ['voteAccount', getAddressEncoder()],
    ['stakeAccount', getAddressEncoder()],
    ['splitStake', getOptionEncoder(getSplitStakeDataEncoder())],
    ['newStakeAccountOwner', getAddressEncoder()],
    ['withdrawingAmount', getU64Encoder()],
    ['withdrawnAmount', getU64ValueChangeEncoder()],
  ])
}

export function getClaimWithdrawRequestEventDecoder(): Decoder<ClaimWithdrawRequestEvent> {
  return getStructDecoder([
    ['withdrawRequest', getAddressDecoder()],
    ['bond', getAddressDecoder()],
    ['voteAccount', getAddressDecoder()],
    ['stakeAccount', getAddressDecoder()],
    ['splitStake', getOptionDecoder(getSplitStakeDataDecoder())],
    ['newStakeAccountOwner', getAddressDecoder()],
    ['withdrawingAmount', getU64Decoder()],
    ['withdrawnAmount', getU64ValueChangeDecoder()],
  ])
}

export function getClaimWithdrawRequestEventCodec(): Codec<
  ClaimWithdrawRequestEventArgs,
  ClaimWithdrawRequestEvent
> {
  return combineCodec(
    getClaimWithdrawRequestEventEncoder(),
    getClaimWithdrawRequestEventDecoder(),
  )
}
