/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit'
import {
  getProductTypeConfigDecoder,
  getProductTypeConfigEncoder,
  getProductTypeDecoder,
  getProductTypeEncoder,
  type ProductType,
  type ProductTypeArgs,
  type ProductTypeConfig,
  type ProductTypeConfigArgs,
} from '.'

export type ConfigureBondProductEvent = {
  config: Address
  bondProduct: Address
  bond: Address
  voteAccount: Address
  productType: ProductType
  oldConfigData: ProductTypeConfig
  newConfigData: ProductTypeConfig
}

export type ConfigureBondProductEventArgs = {
  config: Address
  bondProduct: Address
  bond: Address
  voteAccount: Address
  productType: ProductTypeArgs
  oldConfigData: ProductTypeConfigArgs
  newConfigData: ProductTypeConfigArgs
}

export function getConfigureBondProductEventEncoder(): Encoder<ConfigureBondProductEventArgs> {
  return getStructEncoder([
    ['config', getAddressEncoder()],
    ['bondProduct', getAddressEncoder()],
    ['bond', getAddressEncoder()],
    ['voteAccount', getAddressEncoder()],
    ['productType', getProductTypeEncoder()],
    ['oldConfigData', getProductTypeConfigEncoder()],
    ['newConfigData', getProductTypeConfigEncoder()],
  ])
}

export function getConfigureBondProductEventDecoder(): Decoder<ConfigureBondProductEvent> {
  return getStructDecoder([
    ['config', getAddressDecoder()],
    ['bondProduct', getAddressDecoder()],
    ['bond', getAddressDecoder()],
    ['voteAccount', getAddressDecoder()],
    ['productType', getProductTypeDecoder()],
    ['oldConfigData', getProductTypeConfigDecoder()],
    ['newConfigData', getProductTypeConfigDecoder()],
  ])
}

export function getConfigureBondProductEventCodec(): Codec<
  ConfigureBondProductEventArgs,
  ConfigureBondProductEvent
> {
  return combineCodec(
    getConfigureBondProductEventEncoder(),
    getConfigureBondProductEventDecoder(),
  )
}
