/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit'

export type EmergencyResumeEvent = {
  config: Address
  adminAuthority: Address
  operatorAuthority: Address
  epochsToClaimSettlement: bigint
  withdrawLockupEpochs: bigint
  minimumStakeLamports: bigint
  pauseAuthority: Address
}

export type EmergencyResumeEventArgs = {
  config: Address
  adminAuthority: Address
  operatorAuthority: Address
  epochsToClaimSettlement: number | bigint
  withdrawLockupEpochs: number | bigint
  minimumStakeLamports: number | bigint
  pauseAuthority: Address
}

export function getEmergencyResumeEventEncoder(): FixedSizeEncoder<EmergencyResumeEventArgs> {
  return getStructEncoder([
    ['config', getAddressEncoder()],
    ['adminAuthority', getAddressEncoder()],
    ['operatorAuthority', getAddressEncoder()],
    ['epochsToClaimSettlement', getU64Encoder()],
    ['withdrawLockupEpochs', getU64Encoder()],
    ['minimumStakeLamports', getU64Encoder()],
    ['pauseAuthority', getAddressEncoder()],
  ])
}

export function getEmergencyResumeEventDecoder(): FixedSizeDecoder<EmergencyResumeEvent> {
  return getStructDecoder([
    ['config', getAddressDecoder()],
    ['adminAuthority', getAddressDecoder()],
    ['operatorAuthority', getAddressDecoder()],
    ['epochsToClaimSettlement', getU64Decoder()],
    ['withdrawLockupEpochs', getU64Decoder()],
    ['minimumStakeLamports', getU64Decoder()],
    ['pauseAuthority', getAddressDecoder()],
  ])
}

export function getEmergencyResumeEventCodec(): FixedSizeCodec<
  EmergencyResumeEventArgs,
  EmergencyResumeEvent
> {
  return combineCodec(
    getEmergencyResumeEventEncoder(),
    getEmergencyResumeEventDecoder(),
  )
}
