/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Option,
  type OptionOrNullable,
} from '@solana/kit'
import {
  getSplitStakeDataDecoder,
  getSplitStakeDataEncoder,
  type SplitStakeData,
  type SplitStakeDataArgs,
} from '.'

export type FundSettlementEvent = {
  bond: Address
  settlement: Address
  fundingAmount: bigint
  stakeAccount: Address
  lamportsFunded: bigint
  lamportsClaimed: bigint
  merkleNodesClaimed: bigint
  splitStakeAccount: Option<SplitStakeData>
  splitRentCollector: Option<Address>
  splitRentAmount: bigint
}

export type FundSettlementEventArgs = {
  bond: Address
  settlement: Address
  fundingAmount: number | bigint
  stakeAccount: Address
  lamportsFunded: number | bigint
  lamportsClaimed: number | bigint
  merkleNodesClaimed: number | bigint
  splitStakeAccount: OptionOrNullable<SplitStakeDataArgs>
  splitRentCollector: OptionOrNullable<Address>
  splitRentAmount: number | bigint
}

export function getFundSettlementEventEncoder(): Encoder<FundSettlementEventArgs> {
  return getStructEncoder([
    ['bond', getAddressEncoder()],
    ['settlement', getAddressEncoder()],
    ['fundingAmount', getU64Encoder()],
    ['stakeAccount', getAddressEncoder()],
    ['lamportsFunded', getU64Encoder()],
    ['lamportsClaimed', getU64Encoder()],
    ['merkleNodesClaimed', getU64Encoder()],
    ['splitStakeAccount', getOptionEncoder(getSplitStakeDataEncoder())],
    ['splitRentCollector', getOptionEncoder(getAddressEncoder())],
    ['splitRentAmount', getU64Encoder()],
  ])
}

export function getFundSettlementEventDecoder(): Decoder<FundSettlementEvent> {
  return getStructDecoder([
    ['bond', getAddressDecoder()],
    ['settlement', getAddressDecoder()],
    ['fundingAmount', getU64Decoder()],
    ['stakeAccount', getAddressDecoder()],
    ['lamportsFunded', getU64Decoder()],
    ['lamportsClaimed', getU64Decoder()],
    ['merkleNodesClaimed', getU64Decoder()],
    ['splitStakeAccount', getOptionDecoder(getSplitStakeDataDecoder())],
    ['splitRentCollector', getOptionDecoder(getAddressDecoder())],
    ['splitRentAmount', getU64Decoder()],
  ])
}

export function getFundSettlementEventCodec(): Codec<
  FundSettlementEventArgs,
  FundSettlementEvent
> {
  return combineCodec(
    getFundSettlementEventEncoder(),
    getFundSettlementEventDecoder(),
  )
}
