/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Option,
  type OptionOrNullable,
} from '@solana/kit'
import {
  getProductTypeDecoder,
  getProductTypeEncoder,
  type ProductType,
  type ProductTypeArgs,
} from '.'

export type InitBondProductEvent = {
  bondProduct: Address
  config: Address
  bond: Address
  voteAccount: Address
  productType: ProductType
  authority: Option<Address>
}

export type InitBondProductEventArgs = {
  bondProduct: Address
  config: Address
  bond: Address
  voteAccount: Address
  productType: ProductTypeArgs
  authority: OptionOrNullable<Address>
}

export function getInitBondProductEventEncoder(): Encoder<InitBondProductEventArgs> {
  return getStructEncoder([
    ['bondProduct', getAddressEncoder()],
    ['config', getAddressEncoder()],
    ['bond', getAddressEncoder()],
    ['voteAccount', getAddressEncoder()],
    ['productType', getProductTypeEncoder()],
    ['authority', getOptionEncoder(getAddressEncoder())],
  ])
}

export function getInitBondProductEventDecoder(): Decoder<InitBondProductEvent> {
  return getStructDecoder([
    ['bondProduct', getAddressDecoder()],
    ['config', getAddressDecoder()],
    ['bond', getAddressDecoder()],
    ['voteAccount', getAddressDecoder()],
    ['productType', getProductTypeDecoder()],
    ['authority', getOptionDecoder(getAddressDecoder())],
  ])
}

export function getInitBondProductEventCodec(): Codec<
  InitBondProductEventArgs,
  InitBondProductEvent
> {
  return combineCodec(
    getInitBondProductEventEncoder(),
    getInitBondProductEventDecoder(),
  )
}
