/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from '@solana/kit'

export type InitSettlementEvent = {
  bond: Address
  settlement: Address
  voteAccount: Address
  stakerAuthority: Address
  merkleRoot: ReadonlyUint8Array
  maxTotalClaim: bigint
  maxMerkleNodes: bigint
  epochCreatedFor: bigint
  slotCreatedAt: bigint
  rentCollector: Address
}

export type InitSettlementEventArgs = {
  bond: Address
  settlement: Address
  voteAccount: Address
  stakerAuthority: Address
  merkleRoot: ReadonlyUint8Array
  maxTotalClaim: number | bigint
  maxMerkleNodes: number | bigint
  epochCreatedFor: number | bigint
  slotCreatedAt: number | bigint
  rentCollector: Address
}

export function getInitSettlementEventEncoder(): FixedSizeEncoder<InitSettlementEventArgs> {
  return getStructEncoder([
    ['bond', getAddressEncoder()],
    ['settlement', getAddressEncoder()],
    ['voteAccount', getAddressEncoder()],
    ['stakerAuthority', getAddressEncoder()],
    ['merkleRoot', fixEncoderSize(getBytesEncoder(), 32)],
    ['maxTotalClaim', getU64Encoder()],
    ['maxMerkleNodes', getU64Encoder()],
    ['epochCreatedFor', getU64Encoder()],
    ['slotCreatedAt', getU64Encoder()],
    ['rentCollector', getAddressEncoder()],
  ])
}

export function getInitSettlementEventDecoder(): FixedSizeDecoder<InitSettlementEvent> {
  return getStructDecoder([
    ['bond', getAddressDecoder()],
    ['settlement', getAddressDecoder()],
    ['voteAccount', getAddressDecoder()],
    ['stakerAuthority', getAddressDecoder()],
    ['merkleRoot', fixDecoderSize(getBytesDecoder(), 32)],
    ['maxTotalClaim', getU64Decoder()],
    ['maxMerkleNodes', getU64Decoder()],
    ['epochCreatedFor', getU64Decoder()],
    ['slotCreatedAt', getU64Decoder()],
    ['rentCollector', getAddressDecoder()],
  ])
}

export function getInitSettlementEventCodec(): FixedSizeCodec<
  InitSettlementEventArgs,
  InitSettlementEvent
> {
  return combineCodec(
    getInitSettlementEventEncoder(),
    getInitSettlementEventDecoder(),
  )
}
