/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type MintBondEvent = {
  bond: Address;
  validatorIdentity: Address;
  validatorIdentityTokenAccount: Address;
  tokenMetadata: Address;
};

export type MintBondEventArgs = MintBondEvent;

export function getMintBondEventEncoder(): FixedSizeEncoder<MintBondEventArgs> {
  return getStructEncoder([
    ['bond', getAddressEncoder()],
    ['validatorIdentity', getAddressEncoder()],
    ['validatorIdentityTokenAccount', getAddressEncoder()],
    ['tokenMetadata', getAddressEncoder()],
  ]);
}

export function getMintBondEventDecoder(): FixedSizeDecoder<MintBondEvent> {
  return getStructDecoder([
    ['bond', getAddressDecoder()],
    ['validatorIdentity', getAddressDecoder()],
    ['validatorIdentityTokenAccount', getAddressDecoder()],
    ['tokenMetadata', getAddressDecoder()],
  ]);
}

export function getMintBondEventCodec(): FixedSizeCodec<
  MintBondEventArgs,
  MintBondEvent
> {
  return combineCodec(getMintBondEventEncoder(), getMintBondEventDecoder());
}
