/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getBytesDecoder,
  getBytesEncoder,
  getDiscriminatedUnionDecoder,
  getDiscriminatedUnionEncoder,
  getStructDecoder,
  getStructEncoder,
  getTupleDecoder,
  getTupleEncoder,
  getU32Decoder,
  getU32Encoder,
  type Codec,
  type Decoder,
  type Encoder,
  type GetDiscriminatedUnionVariant,
  type GetDiscriminatedUnionVariantContent,
  type ReadonlyUint8Array,
} from '@solana/kit'
import {
  getCommissionProductConfigDecoder,
  getCommissionProductConfigEncoder,
  type CommissionProductConfig,
  type CommissionProductConfigArgs,
} from '.'

/** Discriminated union for different product configurations */
export type ProductTypeConfig =
  | { __kind: 'Commission'; fields: readonly [CommissionProductConfig] }
  | { __kind: 'Custom'; fields: readonly [ReadonlyUint8Array] }

export type ProductTypeConfigArgs =
  | { __kind: 'Commission'; fields: readonly [CommissionProductConfigArgs] }
  | { __kind: 'Custom'; fields: readonly [ReadonlyUint8Array] }

export function getProductTypeConfigEncoder(): Encoder<ProductTypeConfigArgs> {
  return getDiscriminatedUnionEncoder([
    [
      'Commission',
      getStructEncoder([
        ['fields', getTupleEncoder([getCommissionProductConfigEncoder()])],
      ]),
    ],
    [
      'Custom',
      getStructEncoder([
        [
          'fields',
          getTupleEncoder([
            addEncoderSizePrefix(getBytesEncoder(), getU32Encoder()),
          ]),
        ],
      ]),
    ],
  ])
}

export function getProductTypeConfigDecoder(): Decoder<ProductTypeConfig> {
  return getDiscriminatedUnionDecoder([
    [
      'Commission',
      getStructDecoder([
        ['fields', getTupleDecoder([getCommissionProductConfigDecoder()])],
      ]),
    ],
    [
      'Custom',
      getStructDecoder([
        [
          'fields',
          getTupleDecoder([
            addDecoderSizePrefix(getBytesDecoder(), getU32Decoder()),
          ]),
        ],
      ]),
    ],
  ])
}

export function getProductTypeConfigCodec(): Codec<
  ProductTypeConfigArgs,
  ProductTypeConfig
> {
  return combineCodec(
    getProductTypeConfigEncoder(),
    getProductTypeConfigDecoder(),
  )
}

// Data Enum Helpers.
export function productTypeConfig(
  kind: 'Commission',
  data: GetDiscriminatedUnionVariantContent<
    ProductTypeConfigArgs,
    '__kind',
    'Commission'
  >['fields'],
): GetDiscriminatedUnionVariant<ProductTypeConfigArgs, '__kind', 'Commission'>
export function productTypeConfig(
  kind: 'Custom',
  data: GetDiscriminatedUnionVariantContent<
    ProductTypeConfigArgs,
    '__kind',
    'Custom'
  >['fields'],
): GetDiscriminatedUnionVariant<ProductTypeConfigArgs, '__kind', 'Custom'>
export function productTypeConfig<
  K extends ProductTypeConfigArgs['__kind'],
  Data,
>(kind: K, data?: Data) {
  return Array.isArray(data)
    ? { __kind: kind, fields: data }
    : { __kind: kind, ...(data ?? {}) }
}

export function isProductTypeConfig<K extends ProductTypeConfig['__kind']>(
  kind: K,
  value: ProductTypeConfig,
): value is ProductTypeConfig & { __kind: K } {
  return value.__kind === kind
}
