/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js'

export type SplitStakeData = { address: Address; amount: bigint }

export type SplitStakeDataArgs = { address: Address; amount: number | bigint }

export function getSplitStakeDataEncoder(): Encoder<SplitStakeDataArgs> {
  return getStructEncoder([
    ['address', getAddressEncoder()],
    ['amount', getU64Encoder()],
  ])
}

export function getSplitStakeDataDecoder(): Decoder<SplitStakeData> {
  return getStructDecoder([
    ['address', getAddressDecoder()],
    ['amount', getU64Decoder()],
  ])
}

export function getSplitStakeDataCodec(): Codec<
  SplitStakeDataArgs,
  SplitStakeData
> {
  return combineCodec(getSplitStakeDataEncoder(), getSplitStakeDataDecoder())
}
