/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit'
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from '@solana/program-client-core'
import { VALIDATOR_BONDS_PROGRAM_ADDRESS } from '../programs'

export const CANCEL_SETTLEMENT_DISCRIMINATOR = new Uint8Array([
  33, 241, 96, 62, 228, 178, 1, 120,
])

export function getCancelSettlementDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CANCEL_SETTLEMENT_DISCRIMINATOR,
  )
}

export type CancelSettlementInstruction<
  TProgram extends string = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountBond extends string | AccountMeta<string> = string,
  TAccountSettlement extends string | AccountMeta<string> = string,
  TAccountSettlementClaims extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountBondsWithdrawerAuthority extends string | AccountMeta<string> =
    string,
  TAccountRentCollector extends string | AccountMeta<string> = string,
  TAccountSplitRentCollector extends string | AccountMeta<string> = string,
  TAccountSplitRentRefundAccount extends string | AccountMeta<string> = string,
  TAccountClock extends string | AccountMeta<string> =
    'SysvarC1ock11111111111111111111111111111111',
  TAccountStakeProgram extends string | AccountMeta<string> =
    'Stake11111111111111111111111111111111111111',
  TAccountStakeHistory extends string | AccountMeta<string> =
    'SysvarStakeHistory1111111111111111111111111',
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountBond extends string
        ? ReadonlyAccount<TAccountBond>
        : TAccountBond,
      TAccountSettlement extends string
        ? WritableAccount<TAccountSettlement>
        : TAccountSettlement,
      TAccountSettlementClaims extends string
        ? WritableAccount<TAccountSettlementClaims>
        : TAccountSettlementClaims,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountBondsWithdrawerAuthority extends string
        ? ReadonlyAccount<TAccountBondsWithdrawerAuthority>
        : TAccountBondsWithdrawerAuthority,
      TAccountRentCollector extends string
        ? WritableAccount<TAccountRentCollector>
        : TAccountRentCollector,
      TAccountSplitRentCollector extends string
        ? WritableAccount<TAccountSplitRentCollector>
        : TAccountSplitRentCollector,
      TAccountSplitRentRefundAccount extends string
        ? WritableAccount<TAccountSplitRentRefundAccount>
        : TAccountSplitRentRefundAccount,
      TAccountClock extends string
        ? ReadonlyAccount<TAccountClock>
        : TAccountClock,
      TAccountStakeProgram extends string
        ? ReadonlyAccount<TAccountStakeProgram>
        : TAccountStakeProgram,
      TAccountStakeHistory extends string
        ? ReadonlyAccount<TAccountStakeHistory>
        : TAccountStakeHistory,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      ...TRemainingAccounts,
    ]
  >

export type CancelSettlementInstructionData = {
  discriminator: ReadonlyUint8Array
}

export type CancelSettlementInstructionDataArgs = {}

export function getCancelSettlementInstructionDataEncoder(): FixedSizeEncoder<CancelSettlementInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    value => ({ ...value, discriminator: CANCEL_SETTLEMENT_DISCRIMINATOR }),
  )
}

export function getCancelSettlementInstructionDataDecoder(): FixedSizeDecoder<CancelSettlementInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ])
}

export function getCancelSettlementInstructionDataCodec(): FixedSizeCodec<
  CancelSettlementInstructionDataArgs,
  CancelSettlementInstructionData
> {
  return combineCodec(
    getCancelSettlementInstructionDataEncoder(),
    getCancelSettlementInstructionDataDecoder(),
  )
}

export type CancelSettlementAsyncInput<
  TAccountConfig extends string = string,
  TAccountBond extends string = string,
  TAccountSettlement extends string = string,
  TAccountSettlementClaims extends string = string,
  TAccountAuthority extends string = string,
  TAccountBondsWithdrawerAuthority extends string = string,
  TAccountRentCollector extends string = string,
  TAccountSplitRentCollector extends string = string,
  TAccountSplitRentRefundAccount extends string = string,
  TAccountClock extends string = string,
  TAccountStakeProgram extends string = string,
  TAccountStakeHistory extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  config: Address<TAccountConfig>
  bond: Address<TAccountBond>
  /** settlement to close whenever the operator decides */
  settlement: Address<TAccountSettlement>
  settlementClaims?: Address<TAccountSettlementClaims>
  /** Cancelling is permitted only to emergency or operator authority */
  authority: TransactionSigner<TAccountAuthority>
  bondsWithdrawerAuthority?: Address<TAccountBondsWithdrawerAuthority>
  rentCollector: Address<TAccountRentCollector>
  splitRentCollector: Address<TAccountSplitRentCollector>
  /**
   * The stake account is funded to the settlement and credited to the bond's validator vote account.
   * The lamports are utilized to pay back the rent exemption of the split_stake_account
   */
  splitRentRefundAccount: Address<TAccountSplitRentRefundAccount>
  clock?: Address<TAccountClock>
  stakeProgram?: Address<TAccountStakeProgram>
  stakeHistory?: Address<TAccountStakeHistory>
  eventAuthority?: Address<TAccountEventAuthority>
  program: Address<TAccountProgram>
}

export async function getCancelSettlementInstructionAsync<
  TAccountConfig extends string,
  TAccountBond extends string,
  TAccountSettlement extends string,
  TAccountSettlementClaims extends string,
  TAccountAuthority extends string,
  TAccountBondsWithdrawerAuthority extends string,
  TAccountRentCollector extends string,
  TAccountSplitRentCollector extends string,
  TAccountSplitRentRefundAccount extends string,
  TAccountClock extends string,
  TAccountStakeProgram extends string,
  TAccountStakeHistory extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
>(
  input: CancelSettlementAsyncInput<
    TAccountConfig,
    TAccountBond,
    TAccountSettlement,
    TAccountSettlementClaims,
    TAccountAuthority,
    TAccountBondsWithdrawerAuthority,
    TAccountRentCollector,
    TAccountSplitRentCollector,
    TAccountSplitRentRefundAccount,
    TAccountClock,
    TAccountStakeProgram,
    TAccountStakeHistory,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CancelSettlementInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountBond,
    TAccountSettlement,
    TAccountSettlementClaims,
    TAccountAuthority,
    TAccountBondsWithdrawerAuthority,
    TAccountRentCollector,
    TAccountSplitRentCollector,
    TAccountSplitRentRefundAccount,
    TAccountClock,
    TAccountStakeProgram,
    TAccountStakeHistory,
    TAccountEventAuthority,
    TAccountProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VALIDATOR_BONDS_PROGRAM_ADDRESS

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    bond: { value: input.bond ?? null, isWritable: false },
    settlement: { value: input.settlement ?? null, isWritable: true },
    settlementClaims: {
      value: input.settlementClaims ?? null,
      isWritable: true,
    },
    authority: { value: input.authority ?? null, isWritable: false },
    bondsWithdrawerAuthority: {
      value: input.bondsWithdrawerAuthority ?? null,
      isWritable: false,
    },
    rentCollector: { value: input.rentCollector ?? null, isWritable: true },
    splitRentCollector: {
      value: input.splitRentCollector ?? null,
      isWritable: true,
    },
    splitRentRefundAccount: {
      value: input.splitRentRefundAccount ?? null,
      isWritable: true,
    },
    clock: { value: input.clock ?? null, isWritable: false },
    stakeProgram: { value: input.stakeProgram ?? null, isWritable: false },
    stakeHistory: { value: input.stakeHistory ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  }
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >

  // Resolve default values.
  if (!accounts.settlementClaims.value) {
    accounts.settlementClaims.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            99, 108, 97, 105, 109, 115, 95, 97, 99, 99, 111, 117, 110, 116,
          ]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            'settlement',
            accounts.settlement.value,
          ),
        ),
      ],
    })
  }
  if (!accounts.bondsWithdrawerAuthority.value) {
    accounts.bondsWithdrawerAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            98, 111, 110, 100, 115, 95, 97, 117, 116, 104, 111, 114, 105, 116,
            121,
          ]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            'config',
            accounts.config.value,
          ),
        ),
      ],
    })
  }
  if (!accounts.clock.value) {
    accounts.clock.value =
      'SysvarC1ock11111111111111111111111111111111' as Address<'SysvarC1ock11111111111111111111111111111111'>
  }
  if (!accounts.stakeProgram.value) {
    accounts.stakeProgram.value =
      'Stake11111111111111111111111111111111111111' as Address<'Stake11111111111111111111111111111111111111'>
  }
  if (!accounts.stakeHistory.value) {
    accounts.stakeHistory.value =
      'SysvarStakeHistory1111111111111111111111111' as Address<'SysvarStakeHistory1111111111111111111111111'>
  }
  if (!accounts.eventAuthority.value) {
    accounts.eventAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114,
            105, 116, 121,
          ]),
        ),
      ],
    })
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId')
  return Object.freeze({
    accounts: [
      getAccountMeta('config', accounts.config),
      getAccountMeta('bond', accounts.bond),
      getAccountMeta('settlement', accounts.settlement),
      getAccountMeta('settlementClaims', accounts.settlementClaims),
      getAccountMeta('authority', accounts.authority),
      getAccountMeta(
        'bondsWithdrawerAuthority',
        accounts.bondsWithdrawerAuthority,
      ),
      getAccountMeta('rentCollector', accounts.rentCollector),
      getAccountMeta('splitRentCollector', accounts.splitRentCollector),
      getAccountMeta('splitRentRefundAccount', accounts.splitRentRefundAccount),
      getAccountMeta('clock', accounts.clock),
      getAccountMeta('stakeProgram', accounts.stakeProgram),
      getAccountMeta('stakeHistory', accounts.stakeHistory),
      getAccountMeta('eventAuthority', accounts.eventAuthority),
      getAccountMeta('program', accounts.program),
    ],
    data: getCancelSettlementInstructionDataEncoder().encode({}),
    programAddress,
  } as CancelSettlementInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountBond,
    TAccountSettlement,
    TAccountSettlementClaims,
    TAccountAuthority,
    TAccountBondsWithdrawerAuthority,
    TAccountRentCollector,
    TAccountSplitRentCollector,
    TAccountSplitRentRefundAccount,
    TAccountClock,
    TAccountStakeProgram,
    TAccountStakeHistory,
    TAccountEventAuthority,
    TAccountProgram
  >)
}

export type CancelSettlementInput<
  TAccountConfig extends string = string,
  TAccountBond extends string = string,
  TAccountSettlement extends string = string,
  TAccountSettlementClaims extends string = string,
  TAccountAuthority extends string = string,
  TAccountBondsWithdrawerAuthority extends string = string,
  TAccountRentCollector extends string = string,
  TAccountSplitRentCollector extends string = string,
  TAccountSplitRentRefundAccount extends string = string,
  TAccountClock extends string = string,
  TAccountStakeProgram extends string = string,
  TAccountStakeHistory extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  config: Address<TAccountConfig>
  bond: Address<TAccountBond>
  /** settlement to close whenever the operator decides */
  settlement: Address<TAccountSettlement>
  settlementClaims: Address<TAccountSettlementClaims>
  /** Cancelling is permitted only to emergency or operator authority */
  authority: TransactionSigner<TAccountAuthority>
  bondsWithdrawerAuthority: Address<TAccountBondsWithdrawerAuthority>
  rentCollector: Address<TAccountRentCollector>
  splitRentCollector: Address<TAccountSplitRentCollector>
  /**
   * The stake account is funded to the settlement and credited to the bond's validator vote account.
   * The lamports are utilized to pay back the rent exemption of the split_stake_account
   */
  splitRentRefundAccount: Address<TAccountSplitRentRefundAccount>
  clock?: Address<TAccountClock>
  stakeProgram?: Address<TAccountStakeProgram>
  stakeHistory?: Address<TAccountStakeHistory>
  eventAuthority: Address<TAccountEventAuthority>
  program: Address<TAccountProgram>
}

export function getCancelSettlementInstruction<
  TAccountConfig extends string,
  TAccountBond extends string,
  TAccountSettlement extends string,
  TAccountSettlementClaims extends string,
  TAccountAuthority extends string,
  TAccountBondsWithdrawerAuthority extends string,
  TAccountRentCollector extends string,
  TAccountSplitRentCollector extends string,
  TAccountSplitRentRefundAccount extends string,
  TAccountClock extends string,
  TAccountStakeProgram extends string,
  TAccountStakeHistory extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
>(
  input: CancelSettlementInput<
    TAccountConfig,
    TAccountBond,
    TAccountSettlement,
    TAccountSettlementClaims,
    TAccountAuthority,
    TAccountBondsWithdrawerAuthority,
    TAccountRentCollector,
    TAccountSplitRentCollector,
    TAccountSplitRentRefundAccount,
    TAccountClock,
    TAccountStakeProgram,
    TAccountStakeHistory,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CancelSettlementInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountBond,
  TAccountSettlement,
  TAccountSettlementClaims,
  TAccountAuthority,
  TAccountBondsWithdrawerAuthority,
  TAccountRentCollector,
  TAccountSplitRentCollector,
  TAccountSplitRentRefundAccount,
  TAccountClock,
  TAccountStakeProgram,
  TAccountStakeHistory,
  TAccountEventAuthority,
  TAccountProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VALIDATOR_BONDS_PROGRAM_ADDRESS

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    bond: { value: input.bond ?? null, isWritable: false },
    settlement: { value: input.settlement ?? null, isWritable: true },
    settlementClaims: {
      value: input.settlementClaims ?? null,
      isWritable: true,
    },
    authority: { value: input.authority ?? null, isWritable: false },
    bondsWithdrawerAuthority: {
      value: input.bondsWithdrawerAuthority ?? null,
      isWritable: false,
    },
    rentCollector: { value: input.rentCollector ?? null, isWritable: true },
    splitRentCollector: {
      value: input.splitRentCollector ?? null,
      isWritable: true,
    },
    splitRentRefundAccount: {
      value: input.splitRentRefundAccount ?? null,
      isWritable: true,
    },
    clock: { value: input.clock ?? null, isWritable: false },
    stakeProgram: { value: input.stakeProgram ?? null, isWritable: false },
    stakeHistory: { value: input.stakeHistory ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  }
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >

  // Resolve default values.
  if (!accounts.clock.value) {
    accounts.clock.value =
      'SysvarC1ock11111111111111111111111111111111' as Address<'SysvarC1ock11111111111111111111111111111111'>
  }
  if (!accounts.stakeProgram.value) {
    accounts.stakeProgram.value =
      'Stake11111111111111111111111111111111111111' as Address<'Stake11111111111111111111111111111111111111'>
  }
  if (!accounts.stakeHistory.value) {
    accounts.stakeHistory.value =
      'SysvarStakeHistory1111111111111111111111111' as Address<'SysvarStakeHistory1111111111111111111111111'>
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId')
  return Object.freeze({
    accounts: [
      getAccountMeta('config', accounts.config),
      getAccountMeta('bond', accounts.bond),
      getAccountMeta('settlement', accounts.settlement),
      getAccountMeta('settlementClaims', accounts.settlementClaims),
      getAccountMeta('authority', accounts.authority),
      getAccountMeta(
        'bondsWithdrawerAuthority',
        accounts.bondsWithdrawerAuthority,
      ),
      getAccountMeta('rentCollector', accounts.rentCollector),
      getAccountMeta('splitRentCollector', accounts.splitRentCollector),
      getAccountMeta('splitRentRefundAccount', accounts.splitRentRefundAccount),
      getAccountMeta('clock', accounts.clock),
      getAccountMeta('stakeProgram', accounts.stakeProgram),
      getAccountMeta('stakeHistory', accounts.stakeHistory),
      getAccountMeta('eventAuthority', accounts.eventAuthority),
      getAccountMeta('program', accounts.program),
    ],
    data: getCancelSettlementInstructionDataEncoder().encode({}),
    programAddress,
  } as CancelSettlementInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountBond,
    TAccountSettlement,
    TAccountSettlementClaims,
    TAccountAuthority,
    TAccountBondsWithdrawerAuthority,
    TAccountRentCollector,
    TAccountSplitRentCollector,
    TAccountSplitRentRefundAccount,
    TAccountClock,
    TAccountStakeProgram,
    TAccountStakeHistory,
    TAccountEventAuthority,
    TAccountProgram
  >)
}

export type ParsedCancelSettlementInstruction<
  TProgram extends string = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>
  accounts: {
    config: TAccountMetas[0]
    bond: TAccountMetas[1]
    /** settlement to close whenever the operator decides */
    settlement: TAccountMetas[2]
    settlementClaims: TAccountMetas[3]
    /** Cancelling is permitted only to emergency or operator authority */
    authority: TAccountMetas[4]
    bondsWithdrawerAuthority: TAccountMetas[5]
    rentCollector: TAccountMetas[6]
    splitRentCollector: TAccountMetas[7]
    /**
     * The stake account is funded to the settlement and credited to the bond's validator vote account.
     * The lamports are utilized to pay back the rent exemption of the split_stake_account
     */
    splitRentRefundAccount: TAccountMetas[8]
    clock: TAccountMetas[9]
    stakeProgram: TAccountMetas[10]
    stakeHistory: TAccountMetas[11]
    eventAuthority: TAccountMetas[12]
    program: TAccountMetas[13]
  }
  data: CancelSettlementInstructionData
}

export function parseCancelSettlementInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCancelSettlementInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 14) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 14,
      },
    )
  }
  let accountIndex = 0
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
    accountIndex += 1
    return accountMeta
  }
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      bond: getNextAccount(),
      settlement: getNextAccount(),
      settlementClaims: getNextAccount(),
      authority: getNextAccount(),
      bondsWithdrawerAuthority: getNextAccount(),
      rentCollector: getNextAccount(),
      splitRentCollector: getNextAccount(),
      splitRentRefundAccount: getNextAccount(),
      clock: getNextAccount(),
      stakeProgram: getNextAccount(),
      stakeHistory: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
    },
    data: getCancelSettlementInstructionDataDecoder().decode(instruction.data),
  }
}
