/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';
import { VALIDATOR_BONDS_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CLAIM_SETTLEMENT_V1_DISCRIMINATOR = new Uint8Array([
  0, 13, 213, 236, 10, 199, 94, 48,
]);

export function getClaimSettlementV1DiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLAIM_SETTLEMENT_V1_DISCRIMINATOR
  );
}

export type ClaimSettlementV1Instruction<
  TProgram extends string = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
  TAccountSettlementClaimV1 extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSettlementClaimV1 extends string
        ? ReadonlyAccount<TAccountSettlementClaimV1>
        : TAccountSettlementClaimV1,
      ...TRemainingAccounts,
    ]
  >;

export type ClaimSettlementV1InstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type ClaimSettlementV1InstructionDataArgs = {};

export function getClaimSettlementV1InstructionDataEncoder(): FixedSizeEncoder<ClaimSettlementV1InstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLAIM_SETTLEMENT_V1_DISCRIMINATOR })
  );
}

export function getClaimSettlementV1InstructionDataDecoder(): FixedSizeDecoder<ClaimSettlementV1InstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getClaimSettlementV1InstructionDataCodec(): FixedSizeCodec<
  ClaimSettlementV1InstructionDataArgs,
  ClaimSettlementV1InstructionData
> {
  return combineCodec(
    getClaimSettlementV1InstructionDataEncoder(),
    getClaimSettlementV1InstructionDataDecoder()
  );
}

export type ClaimSettlementV1Input<
  TAccountSettlementClaimV1 extends string = string,
> = {
  settlementClaimV1: Address<TAccountSettlementClaimV1>;
};

export function getClaimSettlementV1Instruction<
  TAccountSettlementClaimV1 extends string,
  TProgramAddress extends Address = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
>(
  input: ClaimSettlementV1Input<TAccountSettlementClaimV1>,
  config?: { programAddress?: TProgramAddress }
): ClaimSettlementV1Instruction<TProgramAddress, TAccountSettlementClaimV1> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VALIDATOR_BONDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    settlementClaimV1: {
      value: input.settlementClaimV1 ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [getAccountMeta(accounts.settlementClaimV1)],
    data: getClaimSettlementV1InstructionDataEncoder().encode({}),
    programAddress,
  } as ClaimSettlementV1Instruction<
    TProgramAddress,
    TAccountSettlementClaimV1
  >);
}

export type ParsedClaimSettlementV1Instruction<
  TProgram extends string = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    settlementClaimV1: TAccountMetas[0];
  };
  data: ClaimSettlementV1InstructionData;
};

export function parseClaimSettlementV1Instruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedClaimSettlementV1Instruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 1) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { settlementClaimV1: getNextAccount() },
    data: getClaimSettlementV1InstructionDataDecoder().decode(instruction.data),
  };
}
