/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit'
import { VALIDATOR_BONDS_PROGRAM_ADDRESS } from '../programs'
import { getAccountMetaFactory, type ResolvedAccount } from '../shared'

export const EMERGENCY_PAUSE_DISCRIMINATOR = new Uint8Array([
  21, 143, 27, 142, 200, 181, 210, 255,
])

export function getEmergencyPauseDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    EMERGENCY_PAUSE_DISCRIMINATOR,
  )
}

export type EmergencyPauseInstruction<
  TProgram extends string = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
  TAccountConfig extends string | IAccountMeta<string> = string,
  TAccountPauseAuthority extends string | IAccountMeta<string> = string,
  TAccountEventAuthority extends string | IAccountMeta<string> = string,
  TAccountProgram extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountPauseAuthority extends string
        ? ReadonlySignerAccount<TAccountPauseAuthority> &
            IAccountSignerMeta<TAccountPauseAuthority>
        : TAccountPauseAuthority,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      ...TRemainingAccounts,
    ]
  >

export type EmergencyPauseInstructionData = {
  discriminator: ReadonlyUint8Array
}

export type EmergencyPauseInstructionDataArgs = {}

export function getEmergencyPauseInstructionDataEncoder(): Encoder<EmergencyPauseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    value => ({ ...value, discriminator: EMERGENCY_PAUSE_DISCRIMINATOR }),
  )
}

export function getEmergencyPauseInstructionDataDecoder(): Decoder<EmergencyPauseInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ])
}

export function getEmergencyPauseInstructionDataCodec(): Codec<
  EmergencyPauseInstructionDataArgs,
  EmergencyPauseInstructionData
> {
  return combineCodec(
    getEmergencyPauseInstructionDataEncoder(),
    getEmergencyPauseInstructionDataDecoder(),
  )
}

export type EmergencyPauseInput<
  TAccountConfig extends string = string,
  TAccountPauseAuthority extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  config: Address<TAccountConfig>
  pauseAuthority: TransactionSigner<TAccountPauseAuthority>
  eventAuthority: Address<TAccountEventAuthority>
  program: Address<TAccountProgram>
}

export function getEmergencyPauseInstruction<
  TAccountConfig extends string,
  TAccountPauseAuthority extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
>(
  input: EmergencyPauseInput<
    TAccountConfig,
    TAccountPauseAuthority,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress },
): EmergencyPauseInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountPauseAuthority,
  TAccountEventAuthority,
  TAccountProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VALIDATOR_BONDS_PROGRAM_ADDRESS

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    pauseAuthority: { value: input.pauseAuthority ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  }
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId')
  const instruction = {
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.pauseAuthority),
      getAccountMeta(accounts.eventAuthority),
      getAccountMeta(accounts.program),
    ],
    programAddress,
    data: getEmergencyPauseInstructionDataEncoder().encode({}),
  } as EmergencyPauseInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountPauseAuthority,
    TAccountEventAuthority,
    TAccountProgram
  >

  return instruction
}

export type ParsedEmergencyPauseInstruction<
  TProgram extends string = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>
  accounts: {
    config: TAccountMetas[0]
    pauseAuthority: TAccountMetas[1]
    eventAuthority: TAccountMetas[2]
    program: TAccountMetas[3]
  }
  data: EmergencyPauseInstructionData
}

export function parseEmergencyPauseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedEmergencyPauseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts')
  }
  let accountIndex = 0
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!
    accountIndex += 1
    return accountMeta
  }
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      pauseAuthority: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
    },
    data: getEmergencyPauseInstructionDataDecoder().decode(instruction.data),
  }
}
