/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit'
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from '@solana/program-client-core'
import { VALIDATOR_BONDS_PROGRAM_ADDRESS } from '../programs'
import {
  getProductTypeConfigDecoder,
  getProductTypeConfigEncoder,
  getProductTypeDecoder,
  getProductTypeEncoder,
  type ProductType,
  type ProductTypeArgs,
  type ProductTypeConfig,
  type ProductTypeConfigArgs,
} from '../types'

export const INIT_BOND_PRODUCT_DISCRIMINATOR = new Uint8Array([
  228, 35, 205, 119, 63, 209, 72, 56,
])

export function getInitBondProductDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INIT_BOND_PRODUCT_DISCRIMINATOR,
  )
}

export type InitBondProductInstruction<
  TProgram extends string = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountBond extends string | AccountMeta<string> = string,
  TAccountVoteAccount extends string | AccountMeta<string> = string,
  TAccountBondProduct extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountRentPayer extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    '11111111111111111111111111111111',
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountBond extends string
        ? WritableAccount<TAccountBond>
        : TAccountBond,
      TAccountVoteAccount extends string
        ? ReadonlyAccount<TAccountVoteAccount>
        : TAccountVoteAccount,
      TAccountBondProduct extends string
        ? WritableAccount<TAccountBondProduct>
        : TAccountBondProduct,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountRentPayer extends string
        ? WritableSignerAccount<TAccountRentPayer> &
            AccountSignerMeta<TAccountRentPayer>
        : TAccountRentPayer,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      ...TRemainingAccounts,
    ]
  >

export type InitBondProductInstructionData = {
  discriminator: ReadonlyUint8Array
  productType: ProductType
  configData: ProductTypeConfig
}

export type InitBondProductInstructionDataArgs = {
  productType: ProductTypeArgs
  configData: ProductTypeConfigArgs
}

export function getInitBondProductInstructionDataEncoder(): Encoder<InitBondProductInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['productType', getProductTypeEncoder()],
      ['configData', getProductTypeConfigEncoder()],
    ]),
    value => ({ ...value, discriminator: INIT_BOND_PRODUCT_DISCRIMINATOR }),
  )
}

export function getInitBondProductInstructionDataDecoder(): Decoder<InitBondProductInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['productType', getProductTypeDecoder()],
    ['configData', getProductTypeConfigDecoder()],
  ])
}

export function getInitBondProductInstructionDataCodec(): Codec<
  InitBondProductInstructionDataArgs,
  InitBondProductInstructionData
> {
  return combineCodec(
    getInitBondProductInstructionDataEncoder(),
    getInitBondProductInstructionDataDecoder(),
  )
}

export type InitBondProductAsyncInput<
  TAccountConfig extends string = string,
  TAccountBond extends string = string,
  TAccountVoteAccount extends string = string,
  TAccountBondProduct extends string = string,
  TAccountAuthority extends string = string,
  TAccountRentPayer extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  /** The config account that the bond belongs to */
  config: Address<TAccountConfig>
  bond?: Address<TAccountBond>
  voteAccount: Address<TAccountVoteAccount>
  /** The bond product account being created */
  bondProduct: Address<TAccountBondProduct>
  /**
   * permission-ed: the validator identity or bond authority signs the instruction, InitBondProductArgs applied
   * permission-less: no signature, default configuration for the bond product
   */
  authority?: TransactionSigner<TAccountAuthority>
  /** Rent payer for the bond product account creation */
  rentPayer: TransactionSigner<TAccountRentPayer>
  systemProgram?: Address<TAccountSystemProgram>
  eventAuthority?: Address<TAccountEventAuthority>
  program: Address<TAccountProgram>
  productType: InitBondProductInstructionDataArgs['productType']
  configData: InitBondProductInstructionDataArgs['configData']
}

export async function getInitBondProductInstructionAsync<
  TAccountConfig extends string,
  TAccountBond extends string,
  TAccountVoteAccount extends string,
  TAccountBondProduct extends string,
  TAccountAuthority extends string,
  TAccountRentPayer extends string,
  TAccountSystemProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
>(
  input: InitBondProductAsyncInput<
    TAccountConfig,
    TAccountBond,
    TAccountVoteAccount,
    TAccountBondProduct,
    TAccountAuthority,
    TAccountRentPayer,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitBondProductInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountBond,
    TAccountVoteAccount,
    TAccountBondProduct,
    TAccountAuthority,
    TAccountRentPayer,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VALIDATOR_BONDS_PROGRAM_ADDRESS

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    bond: { value: input.bond ?? null, isWritable: true },
    voteAccount: { value: input.voteAccount ?? null, isWritable: false },
    bondProduct: { value: input.bondProduct ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
    rentPayer: { value: input.rentPayer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  }
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >

  // Original args.
  const args = { ...input }

  // Resolve default values.
  if (!accounts.bond.value) {
    accounts.bond.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            98, 111, 110, 100, 95, 97, 99, 99, 111, 117, 110, 116,
          ]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            'config',
            accounts.config.value,
          ),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            'voteAccount',
            accounts.voteAccount.value,
          ),
        ),
      ],
    })
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>
  }
  if (!accounts.eventAuthority.value) {
    accounts.eventAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114,
            105, 116, 121,
          ]),
        ),
      ],
    })
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId')
  return Object.freeze({
    accounts: [
      getAccountMeta('config', accounts.config),
      getAccountMeta('bond', accounts.bond),
      getAccountMeta('voteAccount', accounts.voteAccount),
      getAccountMeta('bondProduct', accounts.bondProduct),
      getAccountMeta('authority', accounts.authority),
      getAccountMeta('rentPayer', accounts.rentPayer),
      getAccountMeta('systemProgram', accounts.systemProgram),
      getAccountMeta('eventAuthority', accounts.eventAuthority),
      getAccountMeta('program', accounts.program),
    ],
    data: getInitBondProductInstructionDataEncoder().encode(
      args as InitBondProductInstructionDataArgs,
    ),
    programAddress,
  } as InitBondProductInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountBond,
    TAccountVoteAccount,
    TAccountBondProduct,
    TAccountAuthority,
    TAccountRentPayer,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >)
}

export type InitBondProductInput<
  TAccountConfig extends string = string,
  TAccountBond extends string = string,
  TAccountVoteAccount extends string = string,
  TAccountBondProduct extends string = string,
  TAccountAuthority extends string = string,
  TAccountRentPayer extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  /** The config account that the bond belongs to */
  config: Address<TAccountConfig>
  bond: Address<TAccountBond>
  voteAccount: Address<TAccountVoteAccount>
  /** The bond product account being created */
  bondProduct: Address<TAccountBondProduct>
  /**
   * permission-ed: the validator identity or bond authority signs the instruction, InitBondProductArgs applied
   * permission-less: no signature, default configuration for the bond product
   */
  authority?: TransactionSigner<TAccountAuthority>
  /** Rent payer for the bond product account creation */
  rentPayer: TransactionSigner<TAccountRentPayer>
  systemProgram?: Address<TAccountSystemProgram>
  eventAuthority: Address<TAccountEventAuthority>
  program: Address<TAccountProgram>
  productType: InitBondProductInstructionDataArgs['productType']
  configData: InitBondProductInstructionDataArgs['configData']
}

export function getInitBondProductInstruction<
  TAccountConfig extends string,
  TAccountBond extends string,
  TAccountVoteAccount extends string,
  TAccountBondProduct extends string,
  TAccountAuthority extends string,
  TAccountRentPayer extends string,
  TAccountSystemProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
>(
  input: InitBondProductInput<
    TAccountConfig,
    TAccountBond,
    TAccountVoteAccount,
    TAccountBondProduct,
    TAccountAuthority,
    TAccountRentPayer,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitBondProductInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountBond,
  TAccountVoteAccount,
  TAccountBondProduct,
  TAccountAuthority,
  TAccountRentPayer,
  TAccountSystemProgram,
  TAccountEventAuthority,
  TAccountProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VALIDATOR_BONDS_PROGRAM_ADDRESS

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    bond: { value: input.bond ?? null, isWritable: true },
    voteAccount: { value: input.voteAccount ?? null, isWritable: false },
    bondProduct: { value: input.bondProduct ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
    rentPayer: { value: input.rentPayer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  }
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >

  // Original args.
  const args = { ...input }

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId')
  return Object.freeze({
    accounts: [
      getAccountMeta('config', accounts.config),
      getAccountMeta('bond', accounts.bond),
      getAccountMeta('voteAccount', accounts.voteAccount),
      getAccountMeta('bondProduct', accounts.bondProduct),
      getAccountMeta('authority', accounts.authority),
      getAccountMeta('rentPayer', accounts.rentPayer),
      getAccountMeta('systemProgram', accounts.systemProgram),
      getAccountMeta('eventAuthority', accounts.eventAuthority),
      getAccountMeta('program', accounts.program),
    ],
    data: getInitBondProductInstructionDataEncoder().encode(
      args as InitBondProductInstructionDataArgs,
    ),
    programAddress,
  } as InitBondProductInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountBond,
    TAccountVoteAccount,
    TAccountBondProduct,
    TAccountAuthority,
    TAccountRentPayer,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >)
}

export type ParsedInitBondProductInstruction<
  TProgram extends string = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>
  accounts: {
    /** The config account that the bond belongs to */
    config: TAccountMetas[0]
    bond: TAccountMetas[1]
    voteAccount: TAccountMetas[2]
    /** The bond product account being created */
    bondProduct: TAccountMetas[3]
    /**
     * permission-ed: the validator identity or bond authority signs the instruction, InitBondProductArgs applied
     * permission-less: no signature, default configuration for the bond product
     */
    authority?: TAccountMetas[4] | undefined
    /** Rent payer for the bond product account creation */
    rentPayer: TAccountMetas[5]
    systemProgram: TAccountMetas[6]
    eventAuthority: TAccountMetas[7]
    program: TAccountMetas[8]
  }
  data: InitBondProductInstructionData
}

export function parseInitBondProductInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitBondProductInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 9,
      },
    )
  }
  let accountIndex = 0
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
    accountIndex += 1
    return accountMeta
  }
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount()
    return accountMeta.address === VALIDATOR_BONDS_PROGRAM_ADDRESS
      ? undefined
      : accountMeta
  }
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      bond: getNextAccount(),
      voteAccount: getNextAccount(),
      bondProduct: getNextAccount(),
      authority: getNextOptionalAccount(),
      rentPayer: getNextAccount(),
      systemProgram: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
    },
    data: getInitBondProductInstructionDataDecoder().decode(instruction.data),
  }
}
