/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableSignerAccount,
} from '@solana/kit'
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from '@solana/program-client-core'
import { VALIDATOR_BONDS_PROGRAM_ADDRESS } from '../programs'

export const INIT_CONFIG_DISCRIMINATOR = new Uint8Array([
  23, 235, 115, 232, 168, 96, 1, 231,
])

export function getInitConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(INIT_CONFIG_DISCRIMINATOR)
}

export type InitConfigInstruction<
  TProgram extends string = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountRentPayer extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    '11111111111111111111111111111111',
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? WritableSignerAccount<TAccountConfig> &
            AccountSignerMeta<TAccountConfig>
        : TAccountConfig,
      TAccountRentPayer extends string
        ? WritableSignerAccount<TAccountRentPayer> &
            AccountSignerMeta<TAccountRentPayer>
        : TAccountRentPayer,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      ...TRemainingAccounts,
    ]
  >

export type InitConfigInstructionData = {
  discriminator: ReadonlyUint8Array
  adminAuthority: Address
  operatorAuthority: Address
  epochsToClaimSettlement: bigint
  withdrawLockupEpochs: bigint
  slotsToStartSettlementClaiming: bigint
}

export type InitConfigInstructionDataArgs = {
  adminAuthority: Address
  operatorAuthority: Address
  epochsToClaimSettlement: number | bigint
  withdrawLockupEpochs: number | bigint
  slotsToStartSettlementClaiming: number | bigint
}

export function getInitConfigInstructionDataEncoder(): FixedSizeEncoder<InitConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['adminAuthority', getAddressEncoder()],
      ['operatorAuthority', getAddressEncoder()],
      ['epochsToClaimSettlement', getU64Encoder()],
      ['withdrawLockupEpochs', getU64Encoder()],
      ['slotsToStartSettlementClaiming', getU64Encoder()],
    ]),
    value => ({ ...value, discriminator: INIT_CONFIG_DISCRIMINATOR }),
  )
}

export function getInitConfigInstructionDataDecoder(): FixedSizeDecoder<InitConfigInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['adminAuthority', getAddressDecoder()],
    ['operatorAuthority', getAddressDecoder()],
    ['epochsToClaimSettlement', getU64Decoder()],
    ['withdrawLockupEpochs', getU64Decoder()],
    ['slotsToStartSettlementClaiming', getU64Decoder()],
  ])
}

export function getInitConfigInstructionDataCodec(): FixedSizeCodec<
  InitConfigInstructionDataArgs,
  InitConfigInstructionData
> {
  return combineCodec(
    getInitConfigInstructionDataEncoder(),
    getInitConfigInstructionDataDecoder(),
  )
}

export type InitConfigAsyncInput<
  TAccountConfig extends string = string,
  TAccountRentPayer extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  config: TransactionSigner<TAccountConfig>
  /** rent exempt payer for the config account */
  rentPayer: TransactionSigner<TAccountRentPayer>
  systemProgram?: Address<TAccountSystemProgram>
  eventAuthority?: Address<TAccountEventAuthority>
  program: Address<TAccountProgram>
  adminAuthority: InitConfigInstructionDataArgs['adminAuthority']
  operatorAuthority: InitConfigInstructionDataArgs['operatorAuthority']
  epochsToClaimSettlement: InitConfigInstructionDataArgs['epochsToClaimSettlement']
  withdrawLockupEpochs: InitConfigInstructionDataArgs['withdrawLockupEpochs']
  slotsToStartSettlementClaiming: InitConfigInstructionDataArgs['slotsToStartSettlementClaiming']
}

export async function getInitConfigInstructionAsync<
  TAccountConfig extends string,
  TAccountRentPayer extends string,
  TAccountSystemProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
>(
  input: InitConfigAsyncInput<
    TAccountConfig,
    TAccountRentPayer,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitConfigInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountRentPayer,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VALIDATOR_BONDS_PROGRAM_ADDRESS

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    rentPayer: { value: input.rentPayer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  }
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >

  // Original args.
  const args = { ...input }

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>
  }
  if (!accounts.eventAuthority.value) {
    accounts.eventAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114,
            105, 116, 121,
          ]),
        ),
      ],
    })
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId')
  return Object.freeze({
    accounts: [
      getAccountMeta('config', accounts.config),
      getAccountMeta('rentPayer', accounts.rentPayer),
      getAccountMeta('systemProgram', accounts.systemProgram),
      getAccountMeta('eventAuthority', accounts.eventAuthority),
      getAccountMeta('program', accounts.program),
    ],
    data: getInitConfigInstructionDataEncoder().encode(
      args as InitConfigInstructionDataArgs,
    ),
    programAddress,
  } as InitConfigInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountRentPayer,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >)
}

export type InitConfigInput<
  TAccountConfig extends string = string,
  TAccountRentPayer extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  config: TransactionSigner<TAccountConfig>
  /** rent exempt payer for the config account */
  rentPayer: TransactionSigner<TAccountRentPayer>
  systemProgram?: Address<TAccountSystemProgram>
  eventAuthority: Address<TAccountEventAuthority>
  program: Address<TAccountProgram>
  adminAuthority: InitConfigInstructionDataArgs['adminAuthority']
  operatorAuthority: InitConfigInstructionDataArgs['operatorAuthority']
  epochsToClaimSettlement: InitConfigInstructionDataArgs['epochsToClaimSettlement']
  withdrawLockupEpochs: InitConfigInstructionDataArgs['withdrawLockupEpochs']
  slotsToStartSettlementClaiming: InitConfigInstructionDataArgs['slotsToStartSettlementClaiming']
}

export function getInitConfigInstruction<
  TAccountConfig extends string,
  TAccountRentPayer extends string,
  TAccountSystemProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
>(
  input: InitConfigInput<
    TAccountConfig,
    TAccountRentPayer,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitConfigInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountRentPayer,
  TAccountSystemProgram,
  TAccountEventAuthority,
  TAccountProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VALIDATOR_BONDS_PROGRAM_ADDRESS

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    rentPayer: { value: input.rentPayer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  }
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >

  // Original args.
  const args = { ...input }

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId')
  return Object.freeze({
    accounts: [
      getAccountMeta('config', accounts.config),
      getAccountMeta('rentPayer', accounts.rentPayer),
      getAccountMeta('systemProgram', accounts.systemProgram),
      getAccountMeta('eventAuthority', accounts.eventAuthority),
      getAccountMeta('program', accounts.program),
    ],
    data: getInitConfigInstructionDataEncoder().encode(
      args as InitConfigInstructionDataArgs,
    ),
    programAddress,
  } as InitConfigInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountRentPayer,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >)
}

export type ParsedInitConfigInstruction<
  TProgram extends string = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>
  accounts: {
    config: TAccountMetas[0]
    /** rent exempt payer for the config account */
    rentPayer: TAccountMetas[1]
    systemProgram: TAccountMetas[2]
    eventAuthority: TAccountMetas[3]
    program: TAccountMetas[4]
  }
  data: InitConfigInstructionData
}

export function parseInitConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    )
  }
  let accountIndex = 0
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
    accountIndex += 1
    return accountMeta
  }
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      rentPayer: getNextAccount(),
      systemProgram: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
    },
    data: getInitConfigInstructionDataDecoder().decode(instruction.data),
  }
}
