/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { VALIDATOR_BONDS_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const INIT_BOND_DISCRIMINATOR = new Uint8Array([
  95, 93, 93, 181, 221, 36, 126, 64,
]);

export function getInitBondDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(INIT_BOND_DISCRIMINATOR);
}

export type InitBondInstruction<
  TProgram extends string = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountVoteAccount extends string | AccountMeta<string> = string,
  TAccountValidatorIdentity extends string | AccountMeta<string> = string,
  TAccountBond extends string | AccountMeta<string> = string,
  TAccountRentPayer extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountVoteAccount extends string
        ? ReadonlyAccount<TAccountVoteAccount>
        : TAccountVoteAccount,
      TAccountValidatorIdentity extends string
        ? ReadonlySignerAccount<TAccountValidatorIdentity> &
            AccountSignerMeta<TAccountValidatorIdentity>
        : TAccountValidatorIdentity,
      TAccountBond extends string
        ? WritableAccount<TAccountBond>
        : TAccountBond,
      TAccountRentPayer extends string
        ? WritableSignerAccount<TAccountRentPayer> &
            AccountSignerMeta<TAccountRentPayer>
        : TAccountRentPayer,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitBondInstructionData = {
  discriminator: ReadonlyUint8Array;
  bondAuthority: Address;
  cpmpe: bigint;
  maxStakeWanted: bigint;
};

export type InitBondInstructionDataArgs = {
  bondAuthority: Address;
  cpmpe: number | bigint;
  maxStakeWanted: number | bigint;
};

export function getInitBondInstructionDataEncoder(): FixedSizeEncoder<InitBondInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['bondAuthority', getAddressEncoder()],
      ['cpmpe', getU64Encoder()],
      ['maxStakeWanted', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: INIT_BOND_DISCRIMINATOR })
  );
}

export function getInitBondInstructionDataDecoder(): FixedSizeDecoder<InitBondInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['bondAuthority', getAddressDecoder()],
    ['cpmpe', getU64Decoder()],
    ['maxStakeWanted', getU64Decoder()],
  ]);
}

export function getInitBondInstructionDataCodec(): FixedSizeCodec<
  InitBondInstructionDataArgs,
  InitBondInstructionData
> {
  return combineCodec(
    getInitBondInstructionDataEncoder(),
    getInitBondInstructionDataDecoder()
  );
}

export type InitBondInput<
  TAccountConfig extends string = string,
  TAccountVoteAccount extends string = string,
  TAccountValidatorIdentity extends string = string,
  TAccountBond extends string = string,
  TAccountRentPayer extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  /** the config account under which the bond is created */
  config: Address<TAccountConfig>;
  voteAccount: Address<TAccountVoteAccount>;
  /**
   * permission-ed: the validator identity signs the instruction, InitBondArgs applied
   * permission-less: no signature, default init bond configuration
   */
  validatorIdentity?: TransactionSigner<TAccountValidatorIdentity>;
  bond: Address<TAccountBond>;
  /** rent exempt payer of validator bond account creation */
  rentPayer: TransactionSigner<TAccountRentPayer>;
  systemProgram?: Address<TAccountSystemProgram>;
  eventAuthority: Address<TAccountEventAuthority>;
  program: Address<TAccountProgram>;
  bondAuthority: InitBondInstructionDataArgs['bondAuthority'];
  cpmpe: InitBondInstructionDataArgs['cpmpe'];
  maxStakeWanted: InitBondInstructionDataArgs['maxStakeWanted'];
};

export function getInitBondInstruction<
  TAccountConfig extends string,
  TAccountVoteAccount extends string,
  TAccountValidatorIdentity extends string,
  TAccountBond extends string,
  TAccountRentPayer extends string,
  TAccountSystemProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
>(
  input: InitBondInput<
    TAccountConfig,
    TAccountVoteAccount,
    TAccountValidatorIdentity,
    TAccountBond,
    TAccountRentPayer,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress }
): InitBondInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountVoteAccount,
  TAccountValidatorIdentity,
  TAccountBond,
  TAccountRentPayer,
  TAccountSystemProgram,
  TAccountEventAuthority,
  TAccountProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VALIDATOR_BONDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    voteAccount: { value: input.voteAccount ?? null, isWritable: false },
    validatorIdentity: {
      value: input.validatorIdentity ?? null,
      isWritable: false,
    },
    bond: { value: input.bond ?? null, isWritable: true },
    rentPayer: { value: input.rentPayer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.voteAccount),
      getAccountMeta(accounts.validatorIdentity),
      getAccountMeta(accounts.bond),
      getAccountMeta(accounts.rentPayer),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.eventAuthority),
      getAccountMeta(accounts.program),
    ],
    data: getInitBondInstructionDataEncoder().encode(
      args as InitBondInstructionDataArgs
    ),
    programAddress,
  } as InitBondInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountVoteAccount,
    TAccountValidatorIdentity,
    TAccountBond,
    TAccountRentPayer,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >);
}

export type ParsedInitBondInstruction<
  TProgram extends string = typeof VALIDATOR_BONDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** the config account under which the bond is created */
    config: TAccountMetas[0];
    voteAccount: TAccountMetas[1];
    /**
     * permission-ed: the validator identity signs the instruction, InitBondArgs applied
     * permission-less: no signature, default init bond configuration
     */
    validatorIdentity?: TAccountMetas[2] | undefined;
    bond: TAccountMetas[3];
    /** rent exempt payer of validator bond account creation */
    rentPayer: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
    eventAuthority: TAccountMetas[6];
    program: TAccountMetas[7];
  };
  data: InitBondInstructionData;
};

export function parseInitBondInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedInitBondInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === VALIDATOR_BONDS_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      voteAccount: getNextAccount(),
      validatorIdentity: getNextOptionalAccount(),
      bond: getNextAccount(),
      rentPayer: getNextAccount(),
      systemProgram: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
    },
    data: getInitBondInstructionDataDecoder().decode(instruction.data),
  };
}
