/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import { Program, ProgramError } from '@metaplex-foundation/umi';

type ProgramErrorConstructor = new (
  program: Program,
  cause?: Error
) => ProgramError;
const codeToErrorMap: Map<number, ProgramErrorConstructor> = new Map();
const nameToErrorMap: Map<string, ProgramErrorConstructor> = new Map();

/** InvalidProgramId: Program id in context does not match with the validator bonds id */
export class InvalidProgramIdError extends ProgramError {
  override readonly name: string = 'InvalidProgramId';

  readonly code: number = 0x1770; // 6000

  constructor(program: Program, cause?: Error) {
    super(
      'Program id in context does not match with the validator bonds id',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1770, InvalidProgramIdError);
nameToErrorMap.set('InvalidProgramId', InvalidProgramIdError);

/** InvalidAdminAuthority: Operation requires admin authority signature */
export class InvalidAdminAuthorityError extends ProgramError {
  override readonly name: string = 'InvalidAdminAuthority';

  readonly code: number = 0x1771; // 6001

  constructor(program: Program, cause?: Error) {
    super('Operation requires admin authority signature', program, cause);
  }
}
codeToErrorMap.set(0x1771, InvalidAdminAuthorityError);
nameToErrorMap.set('InvalidAdminAuthority', InvalidAdminAuthorityError);

/** InvalidWithdrawRequestAuthority: Invalid authority to operate with the withdraw request of validator bond account */
export class InvalidWithdrawRequestAuthorityError extends ProgramError {
  override readonly name: string = 'InvalidWithdrawRequestAuthority';

  readonly code: number = 0x1772; // 6002

  constructor(program: Program, cause?: Error) {
    super(
      'Invalid authority to operate with the withdraw request of validator bond account',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1772, InvalidWithdrawRequestAuthorityError);
nameToErrorMap.set(
  'InvalidWithdrawRequestAuthority',
  InvalidWithdrawRequestAuthorityError
);

/** InvalidOperatorAuthority: Operation requires operator authority signature */
export class InvalidOperatorAuthorityError extends ProgramError {
  override readonly name: string = 'InvalidOperatorAuthority';

  readonly code: number = 0x1773; // 6003

  constructor(program: Program, cause?: Error) {
    super('Operation requires operator authority signature', program, cause);
  }
}
codeToErrorMap.set(0x1773, InvalidOperatorAuthorityError);
nameToErrorMap.set('InvalidOperatorAuthority', InvalidOperatorAuthorityError);

/** InvalidVoteAccountProgramId: Provided vote account is not owned by the validator vote program */
export class InvalidVoteAccountProgramIdError extends ProgramError {
  override readonly name: string = 'InvalidVoteAccountProgramId';

  readonly code: number = 0x1774; // 6004

  constructor(program: Program, cause?: Error) {
    super(
      'Provided vote account is not owned by the validator vote program',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1774, InvalidVoteAccountProgramIdError);
nameToErrorMap.set(
  'InvalidVoteAccountProgramId',
  InvalidVoteAccountProgramIdError
);

/** InvalidSettlementAddress: Fail to create account address for Settlement */
export class InvalidSettlementAddressError extends ProgramError {
  override readonly name: string = 'InvalidSettlementAddress';

  readonly code: number = 0x1775; // 6005

  constructor(program: Program, cause?: Error) {
    super('Fail to create account address for Settlement', program, cause);
  }
}
codeToErrorMap.set(0x1775, InvalidSettlementAddressError);
nameToErrorMap.set('InvalidSettlementAddress', InvalidSettlementAddressError);

/** InvalidSettlementAuthorityAddress: Fail to create PDA address for Settlement Authority */
export class InvalidSettlementAuthorityAddressError extends ProgramError {
  override readonly name: string = 'InvalidSettlementAuthorityAddress';

  readonly code: number = 0x1776; // 6006

  constructor(program: Program, cause?: Error) {
    super(
      'Fail to create PDA address for Settlement Authority',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1776, InvalidSettlementAuthorityAddressError);
nameToErrorMap.set(
  'InvalidSettlementAuthorityAddress',
  InvalidSettlementAuthorityAddressError
);

/** InvalidBondsWithdrawerAuthorityAddress: Fail to create PDA address for Bonds Withdrawer Authority */
export class InvalidBondsWithdrawerAuthorityAddressError extends ProgramError {
  override readonly name: string = 'InvalidBondsWithdrawerAuthorityAddress';

  readonly code: number = 0x1777; // 6007

  constructor(program: Program, cause?: Error) {
    super(
      'Fail to create PDA address for Bonds Withdrawer Authority',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1777, InvalidBondsWithdrawerAuthorityAddressError);
nameToErrorMap.set(
  'InvalidBondsWithdrawerAuthorityAddress',
  InvalidBondsWithdrawerAuthorityAddressError
);

/** InvalidSettlementClaimAddress: Fail to create program address for SettlementClaim */
export class InvalidSettlementClaimAddressError extends ProgramError {
  override readonly name: string = 'InvalidSettlementClaimAddress';

  readonly code: number = 0x1778; // 6008

  constructor(program: Program, cause?: Error) {
    super('Fail to create program address for SettlementClaim', program, cause);
  }
}
codeToErrorMap.set(0x1778, InvalidSettlementClaimAddressError);
nameToErrorMap.set(
  'InvalidSettlementClaimAddress',
  InvalidSettlementClaimAddressError
);

/** InvalidBondAddress: Fail to create program address for Bond */
export class InvalidBondAddressError extends ProgramError {
  override readonly name: string = 'InvalidBondAddress';

  readonly code: number = 0x1779; // 6009

  constructor(program: Program, cause?: Error) {
    super('Fail to create program address for Bond', program, cause);
  }
}
codeToErrorMap.set(0x1779, InvalidBondAddressError);
nameToErrorMap.set('InvalidBondAddress', InvalidBondAddressError);

/** InvalidStakeOwner: Stake account's withdrawer does not match with the provided owner */
export class InvalidStakeOwnerError extends ProgramError {
  override readonly name: string = 'InvalidStakeOwner';

  readonly code: number = 0x177a; // 6010

  constructor(program: Program, cause?: Error) {
    super(
      "Stake account's withdrawer does not match with the provided owner",
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x177a, InvalidStakeOwnerError);
nameToErrorMap.set('InvalidStakeOwner', InvalidStakeOwnerError);

/** InvalidWithdrawRequestAddress: Fail to create program address for WithdrawRequest */
export class InvalidWithdrawRequestAddressError extends ProgramError {
  override readonly name: string = 'InvalidWithdrawRequestAddress';

  readonly code: number = 0x177b; // 6011

  constructor(program: Program, cause?: Error) {
    super('Fail to create program address for WithdrawRequest', program, cause);
  }
}
codeToErrorMap.set(0x177b, InvalidWithdrawRequestAddressError);
nameToErrorMap.set(
  'InvalidWithdrawRequestAddress',
  InvalidWithdrawRequestAddressError
);

/** HundrethBasisPointsOverflow: Value of hundredth basis points is too big */
export class HundrethBasisPointsOverflowError extends ProgramError {
  override readonly name: string = 'HundrethBasisPointsOverflow';

  readonly code: number = 0x177c; // 6012

  constructor(program: Program, cause?: Error) {
    super('Value of hundredth basis points is too big', program, cause);
  }
}
codeToErrorMap.set(0x177c, HundrethBasisPointsOverflowError);
nameToErrorMap.set(
  'HundrethBasisPointsOverflow',
  HundrethBasisPointsOverflowError
);

/** HundrethBasisPointsCalculation: Hundreth basis points calculation failure */
export class HundrethBasisPointsCalculationError extends ProgramError {
  override readonly name: string = 'HundrethBasisPointsCalculation';

  readonly code: number = 0x177d; // 6013

  constructor(program: Program, cause?: Error) {
    super('Hundreth basis points calculation failure', program, cause);
  }
}
codeToErrorMap.set(0x177d, HundrethBasisPointsCalculationError);
nameToErrorMap.set(
  'HundrethBasisPointsCalculation',
  HundrethBasisPointsCalculationError
);

/** HundrethBasisPointsParse: Hundreth basis points failure to parse the value */
export class HundrethBasisPointsParseError extends ProgramError {
  override readonly name: string = 'HundrethBasisPointsParse';

  readonly code: number = 0x177e; // 6014

  constructor(program: Program, cause?: Error) {
    super('Hundreth basis points failure to parse the value', program, cause);
  }
}
codeToErrorMap.set(0x177e, HundrethBasisPointsParseError);
nameToErrorMap.set('HundrethBasisPointsParse', HundrethBasisPointsParseError);

/** FailedToDeserializeVoteAccount: Cannot deserialize validator vote account data */
export class FailedToDeserializeVoteAccountError extends ProgramError {
  override readonly name: string = 'FailedToDeserializeVoteAccount';

  readonly code: number = 0x177f; // 6015

  constructor(program: Program, cause?: Error) {
    super('Cannot deserialize validator vote account data', program, cause);
  }
}
codeToErrorMap.set(0x177f, FailedToDeserializeVoteAccountError);
nameToErrorMap.set(
  'FailedToDeserializeVoteAccount',
  FailedToDeserializeVoteAccountError
);

/** BondChangeNotPermitted: Wrong authority for changing the validator bond account */
export class BondChangeNotPermittedError extends ProgramError {
  override readonly name: string = 'BondChangeNotPermitted';

  readonly code: number = 0x1780; // 6016

  constructor(program: Program, cause?: Error) {
    super(
      'Wrong authority for changing the validator bond account',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1780, BondChangeNotPermittedError);
nameToErrorMap.set('BondChangeNotPermitted', BondChangeNotPermittedError);

/** StakeNotDelegated: Provided stake cannot be used for bonds, it's not delegated */
export class StakeNotDelegatedError extends ProgramError {
  override readonly name: string = 'StakeNotDelegated';

  readonly code: number = 0x1781; // 6017

  constructor(program: Program, cause?: Error) {
    super(
      "Provided stake cannot be used for bonds, it's not delegated",
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1781, StakeNotDelegatedError);
nameToErrorMap.set('StakeNotDelegated', StakeNotDelegatedError);

/** BondStakeWrongDelegation: Provided stake is delegated to a wrong validator vote account */
export class BondStakeWrongDelegationError extends ProgramError {
  override readonly name: string = 'BondStakeWrongDelegation';

  readonly code: number = 0x1782; // 6018

  constructor(program: Program, cause?: Error) {
    super(
      'Provided stake is delegated to a wrong validator vote account',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1782, BondStakeWrongDelegationError);
nameToErrorMap.set('BondStakeWrongDelegation', BondStakeWrongDelegationError);

/** WithdrawRequestNotReady: Withdraw request has not elapsed the epoch lockup period yet */
export class WithdrawRequestNotReadyError extends ProgramError {
  override readonly name: string = 'WithdrawRequestNotReady';

  readonly code: number = 0x1783; // 6019

  constructor(program: Program, cause?: Error) {
    super(
      'Withdraw request has not elapsed the epoch lockup period yet',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1783, WithdrawRequestNotReadyError);
nameToErrorMap.set('WithdrawRequestNotReady', WithdrawRequestNotReadyError);

/** SettlementNotExpired: Settlement has not expired yet */
export class SettlementNotExpiredError extends ProgramError {
  override readonly name: string = 'SettlementNotExpired';

  readonly code: number = 0x1784; // 6020

  constructor(program: Program, cause?: Error) {
    super('Settlement has not expired yet', program, cause);
  }
}
codeToErrorMap.set(0x1784, SettlementNotExpiredError);
nameToErrorMap.set('SettlementNotExpired', SettlementNotExpiredError);

/** SettlementExpired: Settlement has already expired */
export class SettlementExpiredError extends ProgramError {
  override readonly name: string = 'SettlementExpired';

  readonly code: number = 0x1785; // 6021

  constructor(program: Program, cause?: Error) {
    super('Settlement has already expired', program, cause);
  }
}
codeToErrorMap.set(0x1785, SettlementExpiredError);
nameToErrorMap.set('SettlementExpired', SettlementExpiredError);

/** UninitializedStake: Stake is not initialized */
export class UninitializedStakeError extends ProgramError {
  override readonly name: string = 'UninitializedStake';

  readonly code: number = 0x1786; // 6022

  constructor(program: Program, cause?: Error) {
    super('Stake is not initialized', program, cause);
  }
}
codeToErrorMap.set(0x1786, UninitializedStakeError);
nameToErrorMap.set('UninitializedStake', UninitializedStakeError);

/** NoStakeOrNotFullyActivated: Stake account is not fully activated */
export class NoStakeOrNotFullyActivatedError extends ProgramError {
  override readonly name: string = 'NoStakeOrNotFullyActivated';

  readonly code: number = 0x1787; // 6023

  constructor(program: Program, cause?: Error) {
    super('Stake account is not fully activated', program, cause);
  }
}
codeToErrorMap.set(0x1787, NoStakeOrNotFullyActivatedError);
nameToErrorMap.set(
  'NoStakeOrNotFullyActivated',
  NoStakeOrNotFullyActivatedError
);

/** UnexpectedRemainingAccounts: Instruction context was provided with unexpected set of remaining accounts */
export class UnexpectedRemainingAccountsError extends ProgramError {
  override readonly name: string = 'UnexpectedRemainingAccounts';

  readonly code: number = 0x1788; // 6024

  constructor(program: Program, cause?: Error) {
    super(
      'Instruction context was provided with unexpected set of remaining accounts',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1788, UnexpectedRemainingAccountsError);
nameToErrorMap.set(
  'UnexpectedRemainingAccounts',
  UnexpectedRemainingAccountsError
);

/** SettlementNotClosed: Closing SettlementClaim requires the settlement being closed */
export class SettlementNotClosedError extends ProgramError {
  override readonly name: string = 'SettlementNotClosed';

  readonly code: number = 0x1789; // 6025

  constructor(program: Program, cause?: Error) {
    super(
      'Closing SettlementClaim requires the settlement being closed',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1789, SettlementNotClosedError);
nameToErrorMap.set('SettlementNotClosed', SettlementNotClosedError);

/** StakeAccountAlreadyFunded: Provided stake account has been already funded to a settlement */
export class StakeAccountAlreadyFundedError extends ProgramError {
  override readonly name: string = 'StakeAccountAlreadyFunded';

  readonly code: number = 0x178a; // 6026

  constructor(program: Program, cause?: Error) {
    super(
      'Provided stake account has been already funded to a settlement',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x178a, StakeAccountAlreadyFundedError);
nameToErrorMap.set('StakeAccountAlreadyFunded', StakeAccountAlreadyFundedError);

/** ClaimSettlementProofFailed: Settlement claim proof failed */
export class ClaimSettlementProofFailedError extends ProgramError {
  override readonly name: string = 'ClaimSettlementProofFailed';

  readonly code: number = 0x178b; // 6027

  constructor(program: Program, cause?: Error) {
    super('Settlement claim proof failed', program, cause);
  }
}
codeToErrorMap.set(0x178b, ClaimSettlementProofFailedError);
nameToErrorMap.set(
  'ClaimSettlementProofFailed',
  ClaimSettlementProofFailedError
);

/** StakeLockedUp: Provided stake account is locked-up */
export class StakeLockedUpError extends ProgramError {
  override readonly name: string = 'StakeLockedUp';

  readonly code: number = 0x178c; // 6028

  constructor(program: Program, cause?: Error) {
    super('Provided stake account is locked-up', program, cause);
  }
}
codeToErrorMap.set(0x178c, StakeLockedUpError);
nameToErrorMap.set('StakeLockedUp', StakeLockedUpError);

/** StakeAccountNotBigEnoughToSplit: Stake account is not big enough to split */
export class StakeAccountNotBigEnoughToSplitError extends ProgramError {
  override readonly name: string = 'StakeAccountNotBigEnoughToSplit';

  readonly code: number = 0x178d; // 6029

  constructor(program: Program, cause?: Error) {
    super('Stake account is not big enough to split', program, cause);
  }
}
codeToErrorMap.set(0x178d, StakeAccountNotBigEnoughToSplitError);
nameToErrorMap.set(
  'StakeAccountNotBigEnoughToSplit',
  StakeAccountNotBigEnoughToSplitError
);

/** ClaimAmountExceedsMaxTotalClaim: Claiming bigger amount than the max total claim */
export class ClaimAmountExceedsMaxTotalClaimError extends ProgramError {
  override readonly name: string = 'ClaimAmountExceedsMaxTotalClaim';

  readonly code: number = 0x178e; // 6030

  constructor(program: Program, cause?: Error) {
    super('Claiming bigger amount than the max total claim', program, cause);
  }
}
codeToErrorMap.set(0x178e, ClaimAmountExceedsMaxTotalClaimError);
nameToErrorMap.set(
  'ClaimAmountExceedsMaxTotalClaim',
  ClaimAmountExceedsMaxTotalClaimError
);

/** ClaimAmountExceedsMaxNumNodes: Claim exceeded number of claimable nodes in the merkle tree */
export class ClaimAmountExceedsMaxNumNodesError extends ProgramError {
  override readonly name: string = 'ClaimAmountExceedsMaxNumNodes';

  readonly code: number = 0x178f; // 6031

  constructor(program: Program, cause?: Error) {
    super(
      'Claim exceeded number of claimable nodes in the merkle tree',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x178f, ClaimAmountExceedsMaxNumNodesError);
nameToErrorMap.set(
  'ClaimAmountExceedsMaxNumNodes',
  ClaimAmountExceedsMaxNumNodesError
);

/** EmptySettlementMerkleTree: Empty merkle tree, nothing to be claimed */
export class EmptySettlementMerkleTreeError extends ProgramError {
  override readonly name: string = 'EmptySettlementMerkleTree';

  readonly code: number = 0x1790; // 6032

  constructor(program: Program, cause?: Error) {
    super('Empty merkle tree, nothing to be claimed', program, cause);
  }
}
codeToErrorMap.set(0x1790, EmptySettlementMerkleTreeError);
nameToErrorMap.set('EmptySettlementMerkleTree', EmptySettlementMerkleTreeError);

/** ClaimingStakeAccountLamportsInsufficient: Provided stake account has not enough lamports to cover the claim */
export class ClaimingStakeAccountLamportsInsufficientError extends ProgramError {
  override readonly name: string = 'ClaimingStakeAccountLamportsInsufficient';

  readonly code: number = 0x1791; // 6033

  constructor(program: Program, cause?: Error) {
    super(
      'Provided stake account has not enough lamports to cover the claim',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1791, ClaimingStakeAccountLamportsInsufficientError);
nameToErrorMap.set(
  'ClaimingStakeAccountLamportsInsufficient',
  ClaimingStakeAccountLamportsInsufficientError
);

/** StakeAccountNotFunded: Provided stake account is not funded under a settlement */
export class StakeAccountNotFundedError extends ProgramError {
  override readonly name: string = 'StakeAccountNotFunded';

  readonly code: number = 0x1792; // 6034

  constructor(program: Program, cause?: Error) {
    super(
      'Provided stake account is not funded under a settlement',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1792, StakeAccountNotFundedError);
nameToErrorMap.set('StakeAccountNotFunded', StakeAccountNotFundedError);

/** ValidatorVoteAccountOwnerMismatch: Owner of validator vote account does not match with the provided owner signature */
export class ValidatorVoteAccountOwnerMismatchError extends ProgramError {
  override readonly name: string = 'ValidatorVoteAccountOwnerMismatch';

  readonly code: number = 0x1793; // 6035

  constructor(program: Program, cause?: Error) {
    super(
      'Owner of validator vote account does not match with the provided owner signature',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1793, ValidatorVoteAccountOwnerMismatchError);
nameToErrorMap.set(
  'ValidatorVoteAccountOwnerMismatch',
  ValidatorVoteAccountOwnerMismatchError
);

/** VoteAccountMismatch: Bond vote account address does not match with the provided validator vote account */
export class VoteAccountMismatchError extends ProgramError {
  override readonly name: string = 'VoteAccountMismatch';

  readonly code: number = 0x1794; // 6036

  constructor(program: Program, cause?: Error) {
    super(
      'Bond vote account address does not match with the provided validator vote account',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1794, VoteAccountMismatchError);
nameToErrorMap.set('VoteAccountMismatch', VoteAccountMismatchError);

/** ConfigAccountMismatch: Bond config address does not match with the provided config account */
export class ConfigAccountMismatchError extends ProgramError {
  override readonly name: string = 'ConfigAccountMismatch';

  readonly code: number = 0x1795; // 6037

  constructor(program: Program, cause?: Error) {
    super(
      'Bond config address does not match with the provided config account',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1795, ConfigAccountMismatchError);
nameToErrorMap.set('ConfigAccountMismatch', ConfigAccountMismatchError);

/** WithdrawRequestVoteAccountMismatch: Withdraw request vote account address does not match with the provided validator vote account */
export class WithdrawRequestVoteAccountMismatchError extends ProgramError {
  override readonly name: string = 'WithdrawRequestVoteAccountMismatch';

  readonly code: number = 0x1796; // 6038

  constructor(program: Program, cause?: Error) {
    super(
      'Withdraw request vote account address does not match with the provided validator vote account',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1796, WithdrawRequestVoteAccountMismatchError);
nameToErrorMap.set(
  'WithdrawRequestVoteAccountMismatch',
  WithdrawRequestVoteAccountMismatchError
);

/** BondAccountMismatch: Bond account address does not match with the stored one */
export class BondAccountMismatchError extends ProgramError {
  override readonly name: string = 'BondAccountMismatch';

  readonly code: number = 0x1797; // 6039

  constructor(program: Program, cause?: Error) {
    super(
      'Bond account address does not match with the stored one',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1797, BondAccountMismatchError);
nameToErrorMap.set('BondAccountMismatch', BondAccountMismatchError);

/** SettlementAccountMismatch: Settlement account address does not match with the stored one */
export class SettlementAccountMismatchError extends ProgramError {
  override readonly name: string = 'SettlementAccountMismatch';

  readonly code: number = 0x1798; // 6040

  constructor(program: Program, cause?: Error) {
    super(
      'Settlement account address does not match with the stored one',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1798, SettlementAccountMismatchError);
nameToErrorMap.set('SettlementAccountMismatch', SettlementAccountMismatchError);

/** RentCollectorMismatch: Rent collector address does not match permitted rent collector */
export class RentCollectorMismatchError extends ProgramError {
  override readonly name: string = 'RentCollectorMismatch';

  readonly code: number = 0x1799; // 6041

  constructor(program: Program, cause?: Error) {
    super(
      'Rent collector address does not match permitted rent collector',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x1799, RentCollectorMismatchError);
nameToErrorMap.set('RentCollectorMismatch', RentCollectorMismatchError);

/** StakerAuthorityMismatch: Stake account's staker does not match with the provided authority */
export class StakerAuthorityMismatchError extends ProgramError {
  override readonly name: string = 'StakerAuthorityMismatch';

  readonly code: number = 0x179a; // 6042

  constructor(program: Program, cause?: Error) {
    super(
      "Stake account's staker does not match with the provided authority",
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x179a, StakerAuthorityMismatchError);
nameToErrorMap.set('StakerAuthorityMismatch', StakerAuthorityMismatchError);

/** SettlementAuthorityMismatch: Settlement stake account authority does not match with the provided stake account authority */
export class SettlementAuthorityMismatchError extends ProgramError {
  override readonly name: string = 'SettlementAuthorityMismatch';

  readonly code: number = 0x179b; // 6043

  constructor(program: Program, cause?: Error) {
    super(
      'Settlement stake account authority does not match with the provided stake account authority',
      program,
      cause
    );
  }
}
codeToErrorMap.set(0x179b, SettlementAuthorityMismatchError);
nameToErrorMap.set(
  'SettlementAuthorityMismatch',
  SettlementAuthorityMismatchError
);

/** StakeDelegationMismatch: Delegation of provided stake account mismatches */
export class StakeDelegationMismatchError extends ProgramError {
  override readonly name: string = 'StakeDelegationMismatch';

  readonly code: number = 0x179c; // 6044

  constructor(program: Program, cause?: Error) {
    super('Delegation of provided stake account mismatches', program, cause);
  }
}
codeToErrorMap.set(0x179c, StakeDelegationMismatchError);
nameToErrorMap.set('StakeDelegationMismatch', StakeDelegationMismatchError);

/**
 * Attempts to resolve a custom program error from the provided error code.
 * @category Errors
 */
export function getValidatorBondsErrorFromCode(
  code: number,
  program: Program,
  cause?: Error
): ProgramError | null {
  const constructor = codeToErrorMap.get(code);
  return constructor ? new constructor(program, cause) : null;
}

/**
 * Attempts to resolve a custom program error from the provided error name, i.e. 'Unauthorized'.
 * @category Errors
 */
export function getValidatorBondsErrorFromName(
  name: string,
  program: Program,
  cause?: Error
): ProgramError | null {
  const constructor = nameToErrorMap.get(name);
  return constructor ? new constructor(program, cause) : null;
}
