#!/usr/bin/env bash
#
# Regression test for settlement generation pipeline.
#
# Downloads input data from GCS / scoring API, runs bid-distribution-cli and
# merkle-generator-cli, then diffs the outputs against production results
# already stored in GCS.
#
# Files are cached in --data-dir so subsequent runs (e.g. after code changes)
# reuse previously downloaded data and only re-generate the "actual" outputs.
#
# Usage:
#   ./scripts/regression-test-settlements.sh \
#       --start-epoch 700 --end-epoch 702 --data-dir ./regression-data
#
# Cache directory layout per epoch (mirrors GCS naming where practical):
#
#   <data-dir>/<epoch>/inputs/stakes.json
#   <data-dir>/<epoch>/inputs/sam-scores.json
#   <data-dir>/<epoch>/inputs/validators.json
#   <data-dir>/<epoch>/inputs/evaluation.json            # GCS: bid-psr-distribution-evaluation.json
#   <data-dir>/<epoch>/inputs/rewards/mev.json           # GCS: rewards_mev.json
#   <data-dir>/<epoch>/inputs/rewards/validators_mev.json
#   <data-dir>/<epoch>/inputs/rewards/inflation.json
#   <data-dir>/<epoch>/inputs/rewards/validators_inflation.json
#   <data-dir>/<epoch>/inputs/rewards/validators_blocks.json
#   <data-dir>/<epoch>/inputs/rewards/jito_priority_fee.json  # GCS: rewards_priority_fee.json
#
#   expected/ — production outputs from GCS (old separate-pipeline format):
#   <data-dir>/<epoch>/expected/bid-distribution-settlements.json           # SAM settlements
#   <data-dir>/<epoch>/expected/bid-psr-distribution-settlements.json       # PSR settlements
#   <data-dir>/<epoch>/expected/bid-distribution-settlement-merkle-trees.json
#   <data-dir>/<epoch>/expected/bid-psr-distribution-settlement-merkle-trees.json
#
#   actual/ — generated by current (unified) code:
#   <data-dir>/<epoch>/actual/bid-distribution-settlements.json   # combined SAM+PSR
#   <data-dir>/<epoch>/actual/unified-merkle-trees.json           # combined merkle trees
#

set -euo pipefail

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
GS_BUCKET="gs://marinade-validator-bonds-mainnet"
GS_BUCKET_ETL="gs://marinade-stakes-etl-mainnet"
SCORING_API_URL="https://scoring.marinade.finance/api/v1"
DATA_DIR="./regression-data"
START_EPOCH=""
END_EPOCH=""
VALIDATOR_BONDS_CONFIG="vbMaRfmTCg92HWGzmd53APkMNpPnGVGZTUHwUJQkXAU"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --start-epoch)  START_EPOCH="$2";       shift 2 ;;
    --end-epoch)    END_EPOCH="$2";         shift 2 ;;
    --data-dir)     DATA_DIR="$2";          shift 2 ;;
    --scoring-api-url) SCORING_API_URL="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 [--start-epoch N] [--end-epoch N] [--data-dir DIR] [--scoring-api-url URL]"
      echo ""
      echo "  --start-epoch N       First epoch to test (default: auto-detect last 30 from GCS)"
      echo "  --end-epoch N         Last epoch to test  (default: auto-detect latest from GCS)"
      echo "  --data-dir DIR        Cache directory for downloaded data (default: ./regression-data)"
      echo "  --scoring-api-url URL SAM scoring API base URL"
      echo "                        (default: https://scoring.marinade.finance/api/v1)"
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# Auto-detect epoch range from GCS if not specified
# ---------------------------------------------------------------------------
auto_detect_epochs() {
  echo "Auto-detecting available epochs from GCS..."
  local epochs
  epochs=$(gcloud storage ls "$GS_BUCKET/" \
    | sed -n 's|.*'"$GS_BUCKET"'/\([0-9]\{1,\}\)/|\1|p' \
    | sort -n)

  if [[ -z "$epochs" ]]; then
    echo "ERROR: Could not list epochs from $GS_BUCKET"
    exit 1
  fi

  local latest
  latest=$(echo "$epochs" | tail -1)

  if [[ -z "$END_EPOCH" ]]; then
    END_EPOCH="$latest"
  fi
  if [[ -z "$START_EPOCH" ]]; then
    # Go back 30 epochs from END_EPOCH, but don't go below the earliest available
    local earliest
    earliest=$(echo "$epochs" | head -1)
    START_EPOCH=$(( END_EPOCH - 30 ))
    if (( START_EPOCH < earliest )); then
      START_EPOCH="$earliest"
    fi
  fi

  echo "Epoch range: $START_EPOCH .. $END_EPOCH"
}

if [[ -z "$START_EPOCH" || -z "$END_EPOCH" ]]; then
  auto_detect_epochs
fi

# ---------------------------------------------------------------------------
# Ensure binaries are built
# ---------------------------------------------------------------------------
BID_CLI="$REPO_ROOT/target/release/bid-distribution-cli"
MERKLE_CLI="$REPO_ROOT/target/release/merkle-generator-cli"

if [[ ! -x "$BID_CLI" || ! -x "$MERKLE_CLI" ]]; then
  echo "Binaries not found. Building..."
  (cd "$REPO_ROOT" && cargo build --release --bin bid-distribution-cli --bin merkle-generator-cli)
fi

SETTLEMENT_CONFIG="$REPO_ROOT/settlement-config.yaml"
if [[ ! -f "$SETTLEMENT_CONFIG" ]]; then
  echo "ERROR: settlement-config.yaml not found at $SETTLEMENT_CONFIG"
  exit 1
fi

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Download a file from GCS if it doesn't already exist locally.
#   gcs_cached_download <gcs_path> <local_path>
gcs_cached_download() {
  local gcs_path="$1"
  local local_path="$2"
  if [[ -f "$local_path" ]]; then
    return 0
  fi
  mkdir -p "$(dirname "$local_path")"
  if gcloud storage cp "$gcs_path" "$local_path" 2>/dev/null; then
    return 0
  else
    echo "  WARN: failed to download $gcs_path"
    return 1
  fi
}

# Download from an HTTP URL if the local file doesn't already exist.
#   http_cached_download <url> <local_path>
http_cached_download() {
  local url="$1"
  local local_path="$2"
  if [[ -f "$local_path" ]]; then
    return 0
  fi
  mkdir -p "$(dirname "$local_path")"
  if curl -sf "$url" -o "$local_path"; then
    return 0
  else
    echo "  WARN: failed to download $url"
    rm -f "$local_path"
    return 1
  fi
}

# ---------------------------------------------------------------------------
# Per-epoch processing
# ---------------------------------------------------------------------------
results=()

process_epoch() {
  local epoch="$1"
  local epoch_dir="$DATA_DIR/$epoch"
  local inputs_dir="$epoch_dir/inputs"
  local rewards_dir="$inputs_dir/rewards"
  local expected_dir="$epoch_dir/expected"
  local actual_dir="$epoch_dir/actual"

  echo ""
  echo "================================================================"
  echo "  Epoch $epoch"
  echo "================================================================"

  mkdir -p "$inputs_dir" "$rewards_dir" "$expected_dir" "$actual_dir"

  # ------- Download inputs (cached) ----------------------------------------

  echo "Downloading inputs (skipping cached files)..."
  local missing_input=false

  gcs_cached_download "$GS_BUCKET/$epoch/stakes.json" "$inputs_dir/stakes.json" \
    || missing_input=true

  http_cached_download "$SCORING_API_URL/scores/sam?epoch=$epoch" "$inputs_dir/sam-scores.json" \
    || missing_input=true

  gcs_cached_download "$GS_BUCKET/$epoch/validators.json" "$inputs_dir/validators.json" \
    || missing_input=true

  # evaluation.json is stored as bid-psr-distribution-evaluation.json in GCS
  gcs_cached_download "$GS_BUCKET/$epoch/bid-psr-distribution-evaluation.json" "$inputs_dir/evaluation.json" \
    || missing_input=true

  # Rewards: GCS names have rewards_ prefix, local names match Rust constants
  # GCS: rewards_mev.json             -> local: mev.json
  # GCS: rewards_validators_mev.json  -> local: validators_mev.json
  # GCS: rewards_inflation.json       -> local: inflation.json
  # GCS: rewards_validators_inflation.json -> local: validators_inflation.json
  # GCS: rewards_validators_blocks.json    -> local: validators_blocks.json
  # GCS: rewards_priority_fee.json         -> local: jito_priority_fee.json
  gcs_cached_download "$GS_BUCKET_ETL/$epoch/rewards_mev.json" "$rewards_dir/mev.json" \
    || missing_input=true
  gcs_cached_download "$GS_BUCKET_ETL/$epoch/rewards_validators_mev.json" "$rewards_dir/validators_mev.json" \
    || missing_input=true
  gcs_cached_download "$GS_BUCKET_ETL/$epoch/rewards_inflation.json" "$rewards_dir/inflation.json" \
    || missing_input=true
  gcs_cached_download "$GS_BUCKET_ETL/$epoch/rewards_validators_inflation.json" "$rewards_dir/validators_inflation.json" \
    || missing_input=true
  gcs_cached_download "$GS_BUCKET_ETL/$epoch/rewards_validators_blocks.json" "$rewards_dir/validators_blocks.json" \
    || missing_input=true
  gcs_cached_download "$GS_BUCKET_ETL/$epoch/rewards_priority_fee.json" "$rewards_dir/jito_priority_fee.json" \
    || missing_input=true

  if [[ "$missing_input" == "true" ]]; then
    echo "  SKIP: some input files missing for epoch $epoch"
    results+=("$epoch SKIP SKIP SKIP")
    return
  fi

  # ------- Download expected outputs (cached) -------------------------------
  # Production uses separate pipelines: bid-distribution (SAM) and
  # bid-psr-distribution (PSR).  We download both settlement files and both
  # merkle-tree files so we can compare them combined against the new unified
  # output.

  echo "Downloading expected outputs (skipping cached files)..."
  local missing_expected=false

  # Settlement files (separate per type in production)
  gcs_cached_download "$GS_BUCKET/$epoch/bid-distribution-settlements.json" \
    "$expected_dir/bid-distribution-settlements.json" \
    || missing_expected=true
  gcs_cached_download "$GS_BUCKET/$epoch/bid-psr-distribution-settlements.json" \
    "$expected_dir/bid-psr-distribution-settlements.json" \
    || missing_expected=true

  # Merkle tree files (separate per type in production)
  gcs_cached_download "$GS_BUCKET/$epoch/bid-distribution-settlement-merkle-trees.json" \
    "$expected_dir/bid-distribution-settlement-merkle-trees.json" \
    || missing_expected=true
  gcs_cached_download "$GS_BUCKET/$epoch/bid-psr-distribution-settlement-merkle-trees.json" \
    "$expected_dir/bid-psr-distribution-settlement-merkle-trees.json" \
    || missing_expected=true

  if [[ "$missing_expected" == "true" ]]; then
    echo "  SKIP: expected output files missing for epoch $epoch"
    results+=("$epoch SKIP SKIP SKIP")
    return
  fi

  # ------- Generate actual outputs ------------------------------------------

  echo "Running bid-distribution-cli..."
  # Always regenerate actual outputs (this is what we're testing)
  rm -f "$actual_dir/bid-distribution-settlements.json" \
        "$actual_dir/bid-distribution-config.json" \
        "$actual_dir/protected-events.json"

  if ! "$BID_CLI" \
      --settlement-config "$SETTLEMENT_CONFIG" \
      --stake-meta-collection "$inputs_dir/stakes.json" \
      --sam-meta-collection "$inputs_dir/sam-scores.json" \
      --rewards-dir "$rewards_dir" \
      --validator-meta-collection "$inputs_dir/validators.json" \
      --revenue-expectation-collection "$inputs_dir/evaluation.json" \
      --output-settlement-collection "$actual_dir/bid-distribution-settlements.json" \
      --output-config "$actual_dir/bid-distribution-config.json" \
      --output-protected-event-collection "$actual_dir/protected-events.json"; then
    echo "  FAIL: bid-distribution-cli exited with error"
    results+=("$epoch ERROR ERROR FAIL")
    return
  fi

  echo "Running merkle-generator-cli..."
  rm -f "$actual_dir/unified-merkle-trees.json"

  if ! "$MERKLE_CLI" \
      --input-settlement-files "$actual_dir/bid-distribution-settlements.json" \
      --output-merkle-trees "$actual_dir/unified-merkle-trees.json" \
      --validator-bonds-config "$VALIDATOR_BONDS_CONFIG"; then
    echo "  FAIL: merkle-generator-cli exited with error"
    results+=("$epoch ERROR ERROR FAIL")
    return
  fi

  # ------- Compare outputs --------------------------------------------------
  # Production had separate files per settlement type (SAM / PSR).  The new
  # unified CLI produces one combined file.  We compare by merging the old
  # separate settlements into one sorted list and doing the same for the new
  # output, then diffing.  For merkle trees we compare sorted merkle roots
  # across all files — if roots match the entire tree is identical.

  echo "Comparing outputs..."

  # -- Settlements comparison --
  # Merge expected settlements from both old files, sort by vote_account for
  # a stable comparison order.  Do the same for actual.
  local settlement_status="MATCH"
  local expected_settlements actual_settlements
  expected_settlements=$(jq -n --slurpfile sam "$expected_dir/bid-distribution-settlements.json" \
    --slurpfile psr "$expected_dir/bid-psr-distribution-settlements.json" \
    '($sam[0].settlements + $psr[0].settlements) | sort_by(.vote_account)' 2>/dev/null || echo "ERROR")
  actual_settlements=$(jq -S '.settlements | sort_by(.vote_account)' \
    "$actual_dir/bid-distribution-settlements.json" 2>/dev/null || echo "ERROR")

  if [[ "$expected_settlements" == "ERROR" || "$actual_settlements" == "ERROR" ]]; then
    settlement_status="ERROR"
  elif [[ "$expected_settlements" != "$actual_settlements" ]]; then
    settlement_status="DIFFER"
    # Print counts for debugging
    local exp_count act_count
    exp_count=$(echo "$expected_settlements" | jq 'length' 2>/dev/null || echo "?")
    act_count=$(echo "$actual_settlements" | jq 'length' 2>/dev/null || echo "?")
    echo "  Settlement counts: expected=$exp_count actual=$act_count"
  fi

  # -- Merkle roots comparison --
  # Combine merkle roots from both old files, sort, compare against unified.
  local merkle_status="MATCH"
  local actual_roots expected_roots
  expected_roots=$(jq -n \
    --slurpfile sam "$expected_dir/bid-distribution-settlement-merkle-trees.json" \
    --slurpfile psr "$expected_dir/bid-psr-distribution-settlement-merkle-trees.json" \
    '[($sam[0].merkle_trees + $psr[0].merkle_trees)[] | .merkle_root] | sort' \
    2>/dev/null || echo "ERROR")
  actual_roots=$(jq -S '[.merkle_trees[] | .merkle_root] | sort' \
    "$actual_dir/unified-merkle-trees.json" 2>/dev/null || echo "ERROR")

  if [[ "$actual_roots" == "ERROR" || "$expected_roots" == "ERROR" ]]; then
    merkle_status="ERROR"
  elif [[ "$actual_roots" != "$expected_roots" ]]; then
    merkle_status="DIFFER"
    local exp_root_count act_root_count
    exp_root_count=$(echo "$expected_roots" | jq 'length' 2>/dev/null || echo "?")
    act_root_count=$(echo "$actual_roots" | jq 'length' 2>/dev/null || echo "?")
    echo "  Merkle root counts: expected=$exp_root_count actual=$act_root_count"
  fi

  # -- Overall status --
  local overall="PASS"
  if [[ "$settlement_status" != "MATCH" || "$merkle_status" != "MATCH" ]]; then
    overall="FAIL"
  fi

  echo "  Settlements: $settlement_status | Merkle roots: $merkle_status | $overall"
  results+=("$epoch $settlement_status $merkle_status $overall")
}

# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------
echo "Regression test: epochs $START_EPOCH .. $END_EPOCH"
echo "Data directory : $DATA_DIR"
echo "Scoring API    : $SCORING_API_URL"
echo ""

for (( epoch = START_EPOCH; epoch <= END_EPOCH; epoch++ )); do
  process_epoch "$epoch"
done

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "================================================================"
echo "  Summary"
echo "================================================================"
printf "%-7s | %-13s | %-13s | %s\n" "Epoch" "Settlements" "Merkle Roots" "Status"
printf "%-7s-+-%-13s-+-%-13s-+-%s\n" "-------" "-------------" "-------------" "------"

any_fail=false
for entry in "${results[@]}"; do
  read -r ep sett merk status <<< "$entry"
  printf "%-7s | %-13s | %-13s | %s\n" "$ep" "$sett" "$merk" "$status"
  if [[ "$status" == "FAIL" || "$status" == "ERROR" ]]; then
    any_fail=true
  fi
done

echo ""
if [[ "$any_fail" == "true" ]]; then
  echo "RESULT: SOME EPOCHS FAILED"
  exit 1
else
  echo "RESULT: ALL EPOCHS PASSED"
  exit 0
fi
