/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Serializer,
  bytes,
  struct,
} from '@metaplex-foundation/umi/serializers';

export type CloseSettlementArgs = { merkleRoot: Uint8Array };

export type CloseSettlementArgsArgs = CloseSettlementArgs;

export function getCloseSettlementArgsSerializer(): Serializer<
  CloseSettlementArgsArgs,
  CloseSettlementArgs
> {
  return struct<CloseSettlementArgs>([['merkleRoot', bytes({ size: 32 })]], {
    description: 'CloseSettlementArgs',
  }) as Serializer<CloseSettlementArgsArgs, CloseSettlementArgs>;
}
