/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import { Serializer, struct, u8 } from '@metaplex-foundation/umi/serializers';

export type ResetStateArgs = { settlementStakeAuthorityBump: number };

export type ResetStateArgsArgs = ResetStateArgs;

export function getResetStateArgsSerializer(): Serializer<
  ResetStateArgsArgs,
  ResetStateArgs
> {
  return struct<ResetStateArgs>([['settlementStakeAuthorityBump', u8()]], {
    description: 'ResetStateArgs',
  }) as Serializer<ResetStateArgsArgs, ResetStateArgs>;
}
