name: Anchor Test

on: workflow_dispatch

jobs:
  anchor-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    container:
      image: tchambard/solana-test-validator:solana_2.3.7-anchor_0.31.1-light_0.27.0
      options: --user root

    steps:
      - name: ⚓ Info + Setup on Anchor
        run: |
          anchor --version
          mkdir -p "$HOME/.config/solana/"
          cp -r /home/ubuntu/.config/solana/install "$HOME/.config/solana/"
          find "$HOME/.config/"
          ls -la "$HOME/.config/solana/install"

      - name: 🏃‍♂️‍➡️ Checkout project
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: 👩‍🔧 Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4
        with:
          version: 10

      - name: 👨‍🔧 Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: 🌄 Set nightly toolchain
        run: rustup default nightly

      - name: 🎩 List rustup toolchains
        run: rustup toolchain list

      - name: 👓 Check solana config
        run: solana config get

      - name: 🧠 Cache Rust dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: 🧨 Running tests for project
        run: |
          pnpm install
          pnpm test
