name: Anchor Test

on: workflow_dispatch

jobs:
  anchor-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container:
      image: tchambard/solana-test-validator:solana_2.3.7-anchor_0.31.1-light_0.27.0
      options: --user root

    steps:
      - name: 🛀🏼 Maximize build space
        run: |
          cp /opt/.npm-global/bin/* /usr/bin
          cp /opt/.cargo/bin/* /usr/bin
          rm -rf /opt

      - name: ⚓ Info + Setup on Anchor
        run: |
          anchor --version
          mkdir -p "$HOME/.config/solana/"
          cp -r /home/ubuntu/.config/solana/install "$HOME/.config/solana/"
          find "$HOME/.config/"
          ls -la "$HOME/.config/solana/install"

      - name: 🏃‍♂️‍➡️ Checkout project
        uses: actions/checkout@v4

      - name: 👩‍🔧 Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: 👨‍🔧 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: 🌄 Set nightly toolchain
        run: rustup default nightly

      - name: 🎩 List rustup toolchains
        run: rustup toolchain list

      - name: 👓 Check solana config
        run: solana config get

      - name: 🧠 Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: 🧨 Running tests for project
        run: |
          pnpm install
          pnpm test
