name: Cargo lint and test

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

env:
  # Not needed in CI, should make things a bit faster
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  # Remove unnecessary WASM build artifacts
  WASM_BUILD_CLEAN_TARGET: 1
  # stripping symbols and optimizing for binary size
  RUSTFLAGS: -C strip=symbols -C opt-level=s

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: ⚙️ Install rust compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libudev-dev

      - name: 👨‍🔧 Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 👩‍🔧 Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 🦿 Install Rust tookchain
        uses: dtolnay/rust-toolchain@1.73.0
        with:
          components: rustfmt, clippy

      - name: 🦴 Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - run: pnpm install
      - run: pnpm lint
      - run: cargo test --release -- --nocapture
